### ISSUE TITLE
yarn add phenomic throws error!

### ISSUE THREAD

**Issue by almeynman** [MoOx/phenomic#1002]
yarn add throws `The engine "yarn" is incompatible with this module. Expected version ">=0.16.0".`

![image](https://cloud.githubusercontent.com/assets/6459157/24792755/24803404-1ba1-11e7-9da4-09042e88111f.png)

**Comment by MoOx** [comment]
Please read and try to understand the message. yarn needs to be >= 0.16 in order for phenomic to work correctly.
You are using yarn 0.15.1. Latest stable is 0.22.0. Please upgrade.

**Comment by almeynman** [comment]
Thanks for a quick reply! And sorry about a stupid question
