### ISSUE TITLE
how to remove console logs from production builds ?

### ISSUE THREAD

**Issue by iiitmanikanta** [MoOx/phenomic#1003]
i am trying to use [https://github.com/yahoo/strip-loader](https://github.com/yahoo/strip-loader) to remove console logs from prod. build...
i added the below config in webpack.config.js but it is not working..

```
        {
          test: /\.js$/,
          include: [
            path.resolve(__dirname, 'scripts'),
            path.resolve(__dirname, 'src')
          ],
          loaders: [
            WebpackStrip.loader('console.log'),
            'babel-loader?cacheDirectory',
            'eslint-loader' + (config.dev ? '?emitWarning' : '')
          ]
        },
```

**Comment by MoOx** [comment]
This is not related to phenomic at all. Please use issue for bug or question directly related to phenomic. You have StackOverflow for generic questions.
