### ISSUE TITLE
Global CSS for node_modules by default

### ISSUE THREAD

**Issue by kennu** [MoOx/phenomic#1010]
Every time I create a new Phenomic project, I need to separately enable global CSS support for node_modules, so that I can add bootstrap and font-awesome. So I'm wondering, is there some reason why not enable it by default?

**Comment by MoOx** [comment]
Because global CSS is by default a bad idea. Anyway, 1.0 won't have any assumption except that css files are global files, so you should be happy with that (because css modules won't be enabled by default as most people this days directly use css in js solutions that's does not use .css files)

**Comment by kennu** [comment]
Okay thanks, very interested to see 1.0. :-) I also think that local CSS modules are nice, but I don't think that packages installed as node_modules normally support them, so that is why I proposed this.

**Comment by MoOx** [comment]
I understand the proposition, but I am afraid this create confusion, more than the current solution is offering (there is already enough issue with 0.x :D)
