### ISSUE TITLE
Using Typefaces Package

### ISSUE THREAD

**Issue by MrLoh** [MoOx/phenomic#1014]
Phenomic is great. But sadly it doesn't seem to support the amazing typefaces packages, that let you import [typefaces](https://github.com/KyleAMathews/typefaces) like any other modules. 

I have no idea how phenomic works on the insight, does anyone have an idea how to make phenomic support typeface packages?

**Comment by montogeek** [comment]
I think it is already supported, just require it at the top of the entry file, then use it in your CSS: `.selector { font-family: 'font' }`

**Comment by MoOx** [comment]
You should probably adjust your webpack config, see https://github.com/MoOx/phenomic/blob/3759363133aab11863ad26d8eb59a602f112c587/themes/phenomic-theme-base/webpack.config.js#L111
