### ISSUE TITLE
Make PostCSS optional

### ISSUE THREAD

**Issue by MrLoh** [MoOx/phenomic#1015]
I love phenomic, but I am also a big fan of styled-components for my styles. 

It is a little annoying that phenomic is so deeply integrated with all the postCSS stuff (which is a great project), but unnecessary, when using something like styled components. 

It would be great if the CSS style would be a choise at the beginning. I removed all the PostCSS boilerplate in a recent commit, maybe that would be helpful for this. 

https://github.com/Cinuru/website/commit/f81c8c66e90685652e93866390a01a1f4697fe9b

Keep the great work goind.

**Comment by MoOx** [comment]
Current master branch doesn't have anything related to postcss ;)
So you will be happy!
We might add theme/template that might add some examples but nothing required at start!

**Comment by MrLoh** [comment]
oh, I didn't notice that. Then I'm really looking forward to the next release 😃

**Comment by MoOx** [comment]
BTW postcss has never been required, you can remove it from the boilerplate without any problem.
