### ISSUE TITLE
Upgrade to React Helmet v5

### ISSUE THREAD

**Issue by MrLoh** [MoOx/phenomic#1017]
Is there anything standing against an update to React Helmet v5, which allows for simple HTML head tag syntax, would certainly make it much easier to use for reeact beginners (and actually everyone).

**Comment by MoOx** [comment]
Closed by 1e6333b8ec2ed31650863bed5dfd071cc112d3e6 .

v1 won't handle react-helmet (userland), but it's ultra easy for you to add static rendering support (see the doc in the linked commit).
