### ISSUE TITLE
Using cssnano

### ISSUE THREAD

**Issue by SamuelBolduc** [MoOx/phenomic#1027]
Wouldn't it be a good idea to minify the generated CSS with cssnano? Google's PageSpeed Insights keeps complaining about un-minified CSS

**Comment by MoOx** [comment]
v1 won't make any assumption about how use style their app, so it will be up to you to handle this.

**Comment by thangngoc89** [comment]
I though webpack css loader already handle this by default

**Comment by axelboc** [comment]
@thangngoc89 turns out the latest version of [css-loader](https://github.com/webpack-contrib/css-loader) doesn't minify by default, so you just need to enable the `minimize` option:

```js
{
  loader: "css-loader",
  options: {
    minimize: config.production,
    ...
  }
}
```

Same deal with sourcemaps.

**Comment by thangngoc89** [comment]
@axelboc Yeah. First thing after I add css-loader was disable minimize and autoprefixer
