### ISSUE TITLE
Handling markdown assets

### ISSUE THREAD

**Issue by bgryszko** [MoOx/phenomic#147]
I'm wondering how statinamic could handle assets from markdown by webpack. I was able to create webpack loader by using `html-loader` + `markdown-it` but the problem in this solution is current `.json` files generation in https://github.com/MoOx/statinamic/blob/e7149484695d9b1790775f3e33dc99fb5db9758b/src/md-collection-loader/index.js#L78. I've tried using `Loader.exec` but run into this https://github.com/webpack/webpack/issues/667

Any ideas how this could be handled?

**Comment by thangngoc89** [comment]
I'm pretty sure @MoOx would love to have this implemented in the core https://github.com/MoOx/statinamic/pull/94#issuecomment-174336820

I'm not familiar with writing a webpack loader. Could you share what've you done ?

There might be some changes in markdown loader to support reload #11

**Comment by bgryszko** [comment]
Long story short, what I did is basically this:

```js
htmlLoader.call(this, markdown.render(content))
```

in my custom edited `md-collection-loader` but it emmits `.json` files like that:
```js
{
  body: "Text <img src=" + require(...) + " />"
}
```

which is obviously not what we want as we have to "compile" the code first. It seems that `Loader.exec` doesn't take webpack config and loaders.  The issue I have is only `json` file generation – I don't know yet how to emit the file correctly.

**Comment by MoOx** [comment]
You want to have a loader that will return a new url for some assets?

**Comment by bgryszko** [comment]
Exactly – but already "rendered" so we can generate json files as you do in md-collection-loader. As described here: https://github.com/webpack/webpack/issues/667 – we could use exec, but it doesn't take webpack config into consideration while compiling the emitted file.

**Comment by MoOx** [comment]
How css-loader does handle url()?

**Comment by thangngoc89** [comment]
Hum. I think this is useful for me atm. But I'm not a familiar with webpack internal so I'll try to integrate this with Statinamic internal API

**Comment by thangngoc89** [comment]
I think we should not depends on renderer but html. We can use rehype to get a HTML AST

**Comment by MoOx** [comment]
How to handle this when we will support reactdown?

**Comment by thangngoc89** [comment]
@MoOx When we use reactdown, it should just works. Like @bgryszko said, we need to require the actually markdown file somewhere and webpack will resolve the image link for us. This mean reactdown's approach. 

If we keeps our current approach, we have to parse and load those images ourself, not via webpack.

**Comment by MoOx** [comment]
Not sure to follow you. Currently markdown [files are require by webpack](https://github.com/MoOx/phenomic/blob/a48ccb958af6bae55ef9e8d74edde373fb01373a/themes/phenomic-theme-base/scripts/phenomic.browser.js#L17-L18). But this is not enough. We need to require() assets referenced in the files consumed by our loader to benefit of webpack core. Like css-loader does with url() https://github.com/webpack/css-loader/blob/5a9c1d13940194b78bff0e27284836557f962e5b/lib/loader.js#L68-L86

**Comment by thangngoc89** [comment]
By require I mean you do it like with css files, and not with `require.context` and load content via json

For ex: `require('./foo.md')`

Those lines of code above produce this: `require(../path/to/images)`
When you do `require('./someth.css)` webpack will resolve the above require statement to actual url with file-loader (or url-loader)

**Comment by MoOx** [comment]
> webpack will resolve the above require statement to actual url with file-loader (or url-loader)

yeah because of the code in css-loader above that tell webpack to use require on the content in url().

require.context is the same as require() when you call each items like here https://github.com/MoOx/phenomic/blob/a48ccb958af6bae55ef9e8d74edde373fb01373a/themes/phenomic-theme-base/scripts/phenomic.browser.js#L18

But maybe I am missing something related to the fact that we return custom type (json) at the end of the loader. But I am pretty sure we can find a way (maybe my creating another loader or something like that?)

**Comment by thangngoc89** [comment]
> But maybe I am missing something related to the fact that we return custom type (json) at the end of the loader. 

Yes. Because we return a public path to the markdown file, so when we require it, there is not require statement for webpack to resolve.

**Comment by MoOx** [comment]
Dawn, I just understood that css-loader only generate a string and that webpack will resolve require after... Well we will find a way... Will think about that after the incoming refactoring.

**Comment by thangngoc89** [comment]
> generate a string

Not a string. It generates a valid JS code with some require statement inside it.

**Comment by MoOx** [comment]
Yeah but generate code from a string ;)

**Comment by bloodyowl** [comment]
With #925, webpack will not used to process markdown anymore. All files not handled by any plugin will be transferred in `dist/assets`

**Comment by MoOx** [comment]
Closed per previous comment.
