### ISSUE TITLE
Smart Offline mode via Service Worker.

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#153]
- Keep pages data in localstorage
- invalidate the cache via a manifest when site is updated.

Ref https://github.com/MoOx/statinamic/pull/151#issuecomment-184595116

**Comment by thangngoc89** [comment]
This may help https://github.com/NekR/offline-plugin

**Comment by thangngoc89** [comment]
Here is the plan:

- [x] Appcache
- [ ] Service worker
- [ ] Don't download a data file twice. Keep it in localStorage.

**Comment by MoOx** [comment]
service worker and/or app cache are supposed to handle the download right?

**Comment by thangngoc89** [comment]
With service worker, we can control how browser download file. Appcache only kicks in whem offline

**Comment by MoOx** [comment]
It seems that the "offline" plugin might helps indeed. Did you take a look to it?

**Comment by thangngoc89** [comment]
I tried offline plugin. Not useful in ourcase since it only can index assets emited from webpack

**Comment by MoOx** [comment]
We emit json via webpack, so are you sure that's not relevant?

**Comment by thangngoc89** [comment]
We have assets file that will be copied with fs, index.html file generated by `url-to-html` , and "offline plugin" doesn't have a fallback option for service worker

**Comment by MoOx** [comment]
Maybe assets in the assets folder should be "optional" (cached when downloaded?)
For the index.html we can probably make an exception.
Just asking that to see if we can integrate serviceworker easily.

**Comment by thangngoc89** [comment]
Why all the troubles ? Just write a service worker logic and put it in.

**Comment by MoOx** [comment]
"Just write", ok then :)

**Comment by thangngoc89** [comment]
fyi, I'm working on service worker. A json file will never be downloaded twice.

**Comment by thangngoc89** [comment]
>  A json file will never be downloaded twice

Haha. Appcache is doing this for us. JSON files was loaded from cache already. No don't see the benefits of writing SW anymore. 

Compare browsers compatiable : [appcache](http://caniuse.com/#search=appcache) and [sw](http://caniuse.com/#search=serviceworker)

**Comment by MoOx** [comment]
appcache is brutal and cache "all the things". sw is a smarter method that will allow you to cache only things already request. For big sites, appcache make no sense (too long to cache everything) and sw will make much more sense.

**Comment by thangngoc89** [comment]
The simplest sw tutorial ever.
https://remysharp.com/2016/03/22/the-copy--paste-guide-to-your-first-service-worker

Will take a look at this in the next few days
