### ISSUE TITLE
og:url in boilerplate is incorrect

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#179]
As per discusstion in https://github.com/MoOx/statinamic/issues/104#issuecomment-184322087

`og:url` must be a absolute path.

This is doable by joining `__url` with `pkg.homepage` using join-uri utility. But you marked it as private API. Any thought ?

**Comment by MoOx** [comment]
Maybe we should offer a function to "absolutize" or "relativize" an url?

**Comment by MoOx** [comment]
Now we can inject the full base url easily since we can inject const in process.env.

PHENOMIC_USER_URL might be a solution.

**Comment by thangngoc89** [comment]
@MoOx can I make join-uri an public API ?

**Comment by MoOx** [comment]
We can, but not sure if having to use it in a single place justify this as a simple `+ "/" + ` might be enough.
If you really thing it's a good idea, you can put it in "phenomic/lib/utils/join-uri" (_utils private, utils public) ?

**Comment by thangngoc89** [comment]
See #432 . I'm too lazy to change all join-uri path :)
