### ISSUE TITLE
Remove raw and rawBody in json files

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#189]
I don't see any real benefit of keeping those field in json file. Removing them will make transition between pages faster

**Comment by MoOx** [comment]
I thought this might be handy for... I don't even remember.
Maybe we can remove that and allow to add it back via an option? I will revisit this when trying to use real markdown.

**Comment by thangngoc89** [comment]
I'll send a pr to disable this. md-collection-loader has a new query config. Which accept an array to specify which field should be included in JSON. Default to :

`emitField: ["rawBody", "raw", "body"]`

head will be always includede

**Comment by thangngoc89** [comment]
Should be implemented as a collection-loader plugin #260

**Comment by MoOx** [comment]
Will handle this in #260.
