### ISSUE TITLE
invalid checksum on 404 page of docs

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#195]

**Comment by thangngoc89** [comment]
Looks like this is related. Same <noscript /> tag https://github.com/MoOx/statinamic/issues/175

**Comment by MoOx** [comment]
Can't reproduce atm http://moox.io/statinamic/404.html, closing.

**Comment by thangngoc89** [comment]
I can reproduce this in dev mode, next branch

**Comment by MoOx** [comment]
Ok after a bit of investigation, this checksum error make totally sense.
If you compare prerendered, and client side rendered, you end up with the exact same markup.
The explanation is simple:

- generated page error is a page with the correct markup, but no data associated to the current url
- since there is no data associated to this url (not even an object containing errors data `{error` - we can not do that since a 404 page is by its nature, not associated with a given url), client side still try to render the page, so try to look for some data in collection
- during the clientside check, page is rendered with nothing for a small amount of ms (this is the first render, so react warn for a checksum issue)
- clientside can't find anything, so render a 404 too (now markup are the same).

Not sure how to "fix" this.

**Comment by thangngoc89** [comment]
Ok. That's make sense.

**Comment by MoOx** [comment]
This is not easy to handle because we use redux, so pages data are passed as props. So when we set a page to "not found" in PageContainer, we will render() the component without data (checksum issue), then will have new data from a props update, then we will have the correct "not found" error in order to make the proper render. We might use an internal state but I feel this is hacky. Maybe we should focus on dropping redux first?

**Comment by thangngoc89** [comment]
We are gonna replace hmr with the new reload solution. Do you think dropping redux store is still a good idea?

**Comment by MoOx** [comment]
True, but except the pages, all others data read only, and all ready in the context. Maybe we can replace redux with something simpler, private (since redux is not really used in the user code, except during the definition, right?)

**Comment by thangngoc89** [comment]
How about remove redux definition in the next version (and add a decrapted notice in docs). 

This will make removing redux easier since we only change private api

**Comment by MoOx** [comment]
Cannot reproduce anymore. Closing for now.

**Comment by thangngoc89** [comment]
If this is all about a `<noscript />` tag. This must be fixed with react 15.
