### ISSUE TITLE
<html lang> should be configurable

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#201]
For now "en" is hardcoded, which sucks.

**Comment by thangngoc89** [comment]
Where do you think we can put the configuration ?

**Comment by MoOx** [comment]
Support a "lang" field in package.json (like for other config) and also support a lang parameter in file metadata. We also need a way to change this on "runtime". I have a project that is multilingual and that know the current page language from the filename (starts with {lang}/)

**Comment by thangngoc89** [comment]
Put it in redux store ?

**Comment by MoOx** [comment]
This kind of data are read only, so it makes no sense to keep that in the store. That's why I moved all read only data in the context.

For my last point I have an idea: add an option for the content-loader called "defaultFrontMatter". This will accept a object or (and here that's the interesting part) a function so people can generate defaultFrontMatter depending on the filename and the already existing frontMatter, dynamically (eg: all files under /posts/ => add a meta "comment: true"). This solution will be really flexible and would solve my problem.

**Comment by thangngoc89** [comment]
Maybe even better,  have a plugins field (work like postcss,  or metalsmith) and we will pass mdObject (can't remember the new name) via this plugins chain and let plugins mutate this mdObject. Benefits:

- move descriptionRenderer to plugin --> flexible 
- maybe move renderer to plugin too
- plugin can return null and content-loader won't emit any file or add it to collection (solve #111)
...

**Comment by MoOx** [comment]
Hum. Good idea.
So we should make default "plugin" public (eg: statinamic/lib/content-loader/plugins/*) so people can reuse them as well as others.
"plugins" option seems a good and flexible idea. This way we can even provide some default plugins in the core.
mdObject => currently textData. Feel free to provide a better idea for the name.

**Comment by thangngoc89** [comment]
Don't have a good name for it yet.

**Comment by thangngoc89** [comment]
React-helmet 3.0.0 can configure this via `htmlAttributes` props.

Close in favor of https://github.com/MoOx/statinamic/pull/348

**Comment by MoOx** [comment]
This will still require some work from us since "en" is hardcoded for now.

**Comment by thangngoc89** [comment]
I planned to do it in #348. Reopen to keeping track of this.
