### ISSUE TITLE
Boilerplate: add favicon

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#207]

**Comment by MoOx** [comment]
react-helmet has been documented in 2665fc792badb334fa960bc90e3c3b1f1851976a

**Comment by MoOx** [comment]
Do you think we should add a generic favicon?! Note sure it's a good idea, but at the same time it seems legit. But if we do so, we should add sort of  apple-touch stuff? Should we?

**Comment by thangngoc89** [comment]
:+1: good point. But I think we should add phenomic's favicon. No need for a generic one. It's easier for new user to replace it :) . 

> we should add sort of apple-touch stuff

:+1: 

In fact, this is a full list of apple-touch icons. https://github.com/VinSpee/vinspee.me/blob/master/web_modules/LayoutContainer/index.js

**Comment by thangngoc89** [comment]
The implementation should be straight forward. You can use this commit as your guide https://github.com/MoOx/phenomic/commit/c7bd54951377f0eb523f4dbb67df4e1cae1e28e6

**Comment by MoOx** [comment]
I don't think it's "that" simple. I want to ship a best practice. So we should include favicons/ios/android/edge icons. So maybe use http://realfavicongenerator.net/ engine (I think there is siomething in node, we could even make a loader or a simple script to automate this).

**Comment by dab** [comment]
Started to look into this issue. Found https://github.com/jantimon/favicons-webpack-plugin
It's working fine, but slow down build process a lot. Will check for other node-based solutions. Also it can be good idea to check if icons already exists, so no need to regenerate it each time.
The other question here — how to inject links markup to our html. It can be done manually, if we will use some predefined and constant name for it, or we can use some generative approach?

**Comment by MoOx** [comment]
@dab feel free to take a look to https://realfavicongenerator.net/ node api (see link in the footer, upload a random image and grab the code)

**Comment by bloodyowl** [comment]
Going to be fixed with #925

**Comment by MoOx** [comment]
v1 will have a "public" folder feature.
