### ISSUE TITLE
document branch workflow

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#211]
TL;DR

- PR for docs of current version : master branch
- Anything else: next branch

---
and any PR should be sent to next ?

thangngoc89 23:05
yes

ben-eb 23:05

MoOx 23:06
next is default branch

ben-eb 23:06
yep, just making sure

MoOx 23:06
pr for docs of the current version => master

ben-eb 23:06
okay, no problem

MoOx 23:06
anything else next

**Comment by thangngoc89** [comment]
Development workflow 

`npm i && npm run predocs && cd docs && npm i && npm start`

Open other terminal and `npm run babelify -- --watch`

**Comment by MoOx** [comment]
Why do you use the last step? predocs create a symlink for lib to src.

**Comment by thangngoc89** [comment]
That explained why sometimes I forgot to run that command but it stills work

**Comment by thangngoc89** [comment]
What is the recommended workflow right now ? 

Maybe we can have a `npm run bootstrap` for setup development environment

and `npm run dev` for starting dev server (docs or boilerplate) ?

**Comment by MoOx** [comment]
## dev workflow

`npm i && npm test` should be enough 90%

## For docs

`npm i && npm run predocs && cd docs && npm i && npm start`. We should add an alias

## for default boilerplate

todo: make a similar workflow to work on  default boilerplate (meanwhile: see boilerplate/README.md that should be remove)

**Comment by thangngoc89** [comment]
`npm test` run test-boilerplate which will make a copy of boilerplate to `test-boilerplate` folder ? How can I suppose to work on a feature branch with boilerplate ? And since docs is using `lib`. Do I have to watch for file changes and run babelify on each changes ?

**Comment by MoOx** [comment]
Btw, we need to document a bit the CHANGELOG order: Fixed, Removed, Changed, Added.

**Comment by thangngoc89** [comment]
we can enforce it with remark-lint (I think).

**Comment by thangngoc89** [comment]
Also add a link to this page some where in the docs https://phenomic.io/contributing/ 

No way to access it

**Comment by MoOx** [comment]
A link has been added to the FAQ on next branch. We now just have to review git workflow.

master is not really used, so I was thinking about making master default again, and stop using a next branch. Versions are tagged anyway and if we want to patch previous versions we can cut a branch from a tag right?

**Comment by thangngoc89** [comment]
yeah. But when will docs be built ?

**Comment by MoOx** [comment]
we can switch to manual docs build in "npm run release" script, after the release. We use a manual step for now anyway.

**Comment by thangngoc89** [comment]
@MoOx too painful. `npmpub` add tag to github when do the releasing right ? Why not tell Travis to build and publish the website each time we add a new tag

**Comment by MoOx** [comment]
it's not painful, we can just do "npmpub && npm run docs-deploy" instead of just "npmpub". No big deal.

**Comment by thangngoc89** [comment]
Alright. It's your call :)

**Comment by thangngoc89** [comment]
How do you plan on keeping the theme up to date ? Each release of phenomic has some breaking changes. I'm tired of doing manually each time.

**Comment by MoOx** [comment]
> How do you plan on keeping the theme up to date ?

Which theme are you talking about?

Anway until 1.0, breaking changes are to ensure we do not contract a technical debt. The idea as you might notice, is to have a minimal public API but that allow maximum flexibility.
So on the long run, should not be a problem. Breaking changes are only in scripts/ for now, in order to reduce the boilerplate. I won't take time to "automate" things with codemod or something like that before 1.0.

**Comment by MoOx** [comment]
Closed in favor of #440
