### ISSUE TITLE
Decouple description generator from markdown engine

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#251]
Description is generated by strip-markdown plugin. Since content-loader is now decoupled from markdown,  we should decouple the description generator too.

I suggest we use my original approach,  get processed HTML,  strip tags and get description.

Or we can provide another callback to let user generare their own description.

**Comment by MoOx** [comment]
Totally.
Maybe, like current "renderer" option, we could have a "descriptionRenderer" option, with a default to what we are doing?

**Comment by thangngoc89** [comment]
:+1: for default option. How about descriptionGenerator?

**Comment by MoOx** [comment]
Not a fan about the term "generator".

**Comment by thangngoc89** [comment]
Okie. That's fine.

**Comment by thangngoc89** [comment]
Should be implemented as a collection-loader plugin. #260

**Comment by MoOx** [comment]
Will handle this in #260.
