### ISSUE TITLE
Improve UX for content updates when "offline" is used

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#277]
Vanila js code:

``` js
// Check if a new cache is available on page load.
window.addEventListener('load', function(e) {

  window.applicationCache.addEventListener('updateready', function(e) {
    if (window.applicationCache.status == window.applicationCache.UPDATEREADY) {
      // Browser downloaded a new app cache.
      if (confirm('A new version of this site is available. Load it?')) {
        window.location.reload();
      }
    } else {
      // Manifest didn't changed. Nothing new to server.
    }
  }, false);

}, false);
```

**Comment by MoOx** [comment]
It's not automatic?

**Comment by thangngoc89** [comment]
New version of website will be downloaded automatically. But it won't show up until you refreshed the page (which is likely never happens with a website built with React). So we need to listen to `window.applicationCache.UPDATEREADY` event and reload the page manually.

**Comment by MoOx** [comment]
How does a site is being tell that their is an update? Because for static server, there is no push or anything. Do browsers check the manifest every X minutes or something?

**Comment by thangngoc89** [comment]
No. Browser **always** download manifest.appcache everytime you visit a website with appcache enabled. If manifest.appcache is different from the previous version. Browser will download new files and notify us via `updateready` event.

**Comment by thangngoc89** [comment]
That's probably why [MDN marked appcache as decrapted](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache)

**Comment by thangngoc89** [comment]
@MoOx Actually, we can put those LoC to docs right now. But do you like using `confirm` ?

**Comment by thangngoc89** [comment]
poke @MoOx 

A screenshot 

![image](https://cloud.githubusercontent.com/assets/3049054/13883780/a8735534-ed5d-11e5-87aa-b6a499c309df.png)

**Comment by MoOx** [comment]
What about this brutal approach:

```js
window.addEventListener('load', function() {
  window.applicationCache.addEventListener('updateready', function() {
    if (window.applicationCache.status == window.applicationCache.UPDATEREADY) {
      window.location.reload();
    }
  }, false);
}, false);
```
UX: you open a new page, and just get a "weird" reload. Seems less shitty than a "click on yes please, because you are not going to click on no anyway".

**Comment by MoOx** [comment]
Ok so let go for something like this but without confirm()

**Comment by thangngoc89** [comment]
I suggest creating a general package for this (that append the confirm to `<body>`). 1 cons: global css

**Comment by MoOx** [comment]
I think some minimal inline styles will be more than enough.

**Comment by thangngoc89** [comment]
>  inline styles 

Are you planning on using React ?

**Comment by MoOx** [comment]
Not sure, but you can do inline styles without react :)

**Comment by thangngoc89** [comment]
Yeah yeah. I know.

**Comment by MoOx** [comment]
Is this relevant for SW?

**Comment by thangngoc89** [comment]
I dont know.  Have to test it

**Comment by kuzvac** [comment]
Yesterday i watched new series [Totally Tooling Tips](https://www.youtube.com/watch?v=OBfLvqA_E4A) (this series about Offline Support). They talked about how SW works. Maybe it will help.

**Comment by thangngoc89** [comment]
I confirm that SW does have this problem. A hard refresh is needed to get new HTML content

**Comment by MoOx** [comment]
From what I understand, we should change the cacheName each time we make a build. This will remove the previous data (according to the existing "activate" step) and the new data will be fetched.
Maybe we should inline the sw-register in the head (no http request, very small script), so the sw can be installed & activated as soon as possible?

**Comment by thangngoc89** [comment]
> we should inline the sw-register in the head

:+1: do it for manifest chunk too.

> change the cacheName each time we make a build

I did it already. It's `Date.now()`

> and the new data will be fetched.

Same problem here. New data will be fetched but `window.__COLLECTION__`, css and js files don't change.

**Comment by MoOx** [comment]
We need to choose a proper strategy listed in this cookbook https://jakearchibald.com/2014/offline-cookbook/ ("Serving suggestions") and find a way to offer multiples way to decide your approach.

**Comment by MoOx** [comment]
I got the problem with FF when releasing 0.12: I needed to clean my cache to get website up to date. This sucks. Will try to work on a patch asap.

**Comment by thangngoc89** [comment]
@MoOx is it because of appcache or SW ?

**Comment by MoOx** [comment]
I guess? No idea, I will have to do some tests. Firefox should ignore manifest if sw is registered.

**Comment by MoOx** [comment]
Currently this is a big issue on safari, where it's impossible to get page up to date if appcache is on. I will work on that asap.

**Comment by MoOx** [comment]
FYI, I added a banner on the doc, if someone can take a look on safari or IE to https://phenomic.io/ (eg: open the website now: you will get the "downloading" message, then it will hide, and go later (eg next release) and you will get the downloading message again, then a button to "refresh" (since appcache will first serve cached data). Tell me what you think.

**Comment by thangngoc89** [comment]
I saw it :+1:. Nice

**Comment by MoOx** [comment]
Removing "bug" label since it's not a bug technically speaking (you can "wait" for the update, even if that can be long).

That said, will take some times to make this as a reusable module.

**Comment by MoOx** [comment]
The same problem affect SW: we need to handle events: when the website update. Currently it's weird, it does not seems to be network first... Need to investigate on this.

**Comment by thangngoc89** [comment]
Yup. I noticed that. New blog posts weren't showed up

**Comment by MoOx** [comment]
For now no more offline feature in v1. We will review this later.
