### ISSUE TITLE
Support react-native-web

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#280]
Because that's fun.

https://github.com/necolas/react-native-web

**Comment by magsout** [comment]
👍

**Comment by MoOx** [comment]
I played a little with react-native-web recently, and will try to integrate required changes (will try for my personal website). Note that this can work without any change, but the change will allow to inline CSS in the HTML (which is considered good by google for perf).
The only difference with react and react-native-web is the way to start the app (ReactDOM.render / [AppRegistry.*](https://github.com/necolas/react-native-web/blob/master/docs/apis/AppRegistry.md#example)) so change will be minimal and easy to integrate via a flag.

**Comment by MoOx** [comment]
I renamed the issue to reflect the scope: allow AppRegistry to render your app.

**Comment by bloodyowl** [comment]
Going to be fixed with #925

**Comment by MoOx** [comment]
Done in master.
