### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#301]
We really need to discuss that. Since we started using BABEL_DISABLE_CACHE, everything is super slow.

First, using BABEL_DISABLE_CACHE for the static build is brutal: we should instead just "remove" the cache before doing the build, since during the build we are not modifying the files and can benefit from the cache, this should speed up things a lot (I hope).

Second, during development, maybe we should consider trying (again) a more smart cache cleaner that will remove (eg: when a css file change) the appropriate cache _only_ (not everything).
Maybe we should handle that in babel-plugin-webpack-loaders (poke @istarkov).

Any thoughts?

**Comment by istarkov** [comment]
As a fast idea to use something like this (for css, sass) instead of `BABEL_DISABLE_CACHE`

```bash
egrep -irl --include=*.{js,jsx} "(.css\'|.sass\')" $BABEL_CACHE_PATH | xargs rm
```

_where $BABEL_CACHE_PATH must be set to cache directory_

**Comment by istarkov** [comment]
But I'm not even sure that babel uses different files for cache ;-)

**Comment by istarkov** [comment]
Looks like it's just a single json file https://babeljs.io/docs/usage/require/

**Comment by istarkov** [comment]
May be this helps
```
# touch files to change access times, so if cache uses this information this can help
egrep -irl --include=*.{js,jsx} "(.css\'|.sass\')" ./src | touch
```

**Comment by MoOx** [comment]
Workaround: use a local babel cache directory, and remove it before static build (but the issue for the live server will still occurs, we might delete the babel cache on each prerender, that might make things still slow, but maybe a little less slower than it is for now)

Possible fixes:
- reconsider using a webpack builded file for the server, but this time with nodemon to reload the server when a file changes. That will make us have 2 servers: one for webpack build (client/server), one that use webpack server build refreshed via forever/nodemon. Now that there is less boilerplate, we might reconsider this option.
- drop the prerendering or make it optional. Maybe making this optional will make things faster with not a lot of effort.

**Comment by thangngoc89** [comment]
The first option is recommended (or was recommended) by webpack https://github.com/webpack/react-webpack-server-side-example

**Comment by thangngoc89** [comment]
This might be useful: https://github.com/trivago/parallel-webpack

We can use this approach to have static and client build in parallel.

**Comment by MoOx** [comment]
This is now my top priority and here is what I think we should do:

- remove dev server rendering for now
- have a fast start for dev server
- have a fast static build

By fast I mean 5/10 sec. Compared to what we have right now it will be like a huge improvement.
Client build take around 15s right now (for docs). Static build + generate files take around 30sec. Full build take around 50sec. We need to have a full build around 15s MAX. This is step 1.

Step 2: optimize all the things we can with this process (webpack build client and static build, static build is used to generate static files) to boost the maximum we can (maybe try to use react min + ignore with webpack, things like that).

Step 3: cache everything we can. Look here for info https://github.com/webpack/webpack/issues/250

Optional additional step (maybe in another release) is adding back dev server rendering. Currently our webpack instance is handled by a single express server.
We should try this: webpack dev server that handle client build (which include client server for generated assets) + an express server started from the generated static build, that is updated via nodemon/forever.

I am totally not a pro about node perf, so every comment or idea are welcome.

**Comment by MoOx** [comment]
I forgot to mention that we will remove babel-plugin-webpack-loaders during step 1 :)

**Comment by thangngoc89** [comment]
It sounds amazing. For static build, as I mentioned above, use parallel-webpack to have both commonjs and browser build as the same time. (generating HTML takes < 1 second)

For a faster rebuild circle during developing, break content-loader into 2 smaller loader2

- parser : cacheable, return the same result for the same file
- collection generator: uncacheable (do the rest of the job)
