### ISSUE TITLE
Consider dropping the usage of React context

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#304]
react-router did it.

Props should be enough. We should at least evaluate the idea, to make things (and tests) simpler.

I want a minimal API and context make things more complicated (no big deal but still).

**Comment by thangngoc89** [comment]
Is there reference about why react-router drop it ?

**Comment by MoOx** [comment]
https://github.com/reactjs/react-router/issues/2646 in the middle of the desc.

**Comment by thangngoc89** [comment]
I saw that they're moving multiple contexts into 1. Not dropping it entirely.

**Comment by MoOx** [comment]
Yeah but I am pretty sure we can do without those. Context is handy but not the silver bullet and make functional component not that functional :D
Will see that later.

**Comment by thangngoc89** [comment]
Oh. I have to agree with you about this. It's hard to test component with context.

**Comment by montogeek** [comment]
This should close https://github.com/MoOx/phenomic/issues/40, right?

**Comment by MoOx** [comment]
We should indeed, remove redux AND remove explicit context in favor of provider components.

**Comment by bloodyowl** [comment]
Going to be fixed with #925
