### ISSUE TITLE
Simplify labels

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#328]
Something like that https://github.com/putaindecode/putaindecode.io/labels

**Comment by thangngoc89** [comment]
Maybe using milestone instead of a todo list for next version?

**Comment by MoOx** [comment]
I prefer cutting release fast. Sorry if 0.8 and 0.9 was slow and painful. Will try to avoid this shit for newer release. Or maybe just one more time for #187...

**Comment by thangngoc89** [comment]
I'll prefer using milestone. It helps keeping track of what's going on.

**Comment by MoOx** [comment]
Labels updated.
