### ISSUE TITLE
FAQ: why this project over gatsby

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#329]
- gatsby require a global install, which is a bad practise (eg: you can't have 2 websites with differents versions easily) NOT SURE ABOUT THAT.
- gatsby is not really covered by tests (ouch) - very few right now, none when this project has been started
- gatsby is using it's own dependency for babel, react, react-dom, react-router, webpack, webpack loaders... So you are not really in control if you need to (and might have to wait for gatsby to bump version of those deps)
- gatsby does not seems to be flexible enough on some points
  - you can't use your normal webpack config and need to use a specific format to edit it
  - _you don't have any control on react-router (no custom routes)_
- gatsby doesn't have page data spliting. Everything is in the bundle. Phenomic on the other hand, generate json file file for each page so the js bundle is lightweight and no different than a normal React app (which make sense as soon as you have starts to have more than 10 pages). Pages data are loaded on demand

What gatsby don't have

- ~~phenomic support custom route~~ it does, it's ``path``.
- default boilerplate have a full component approach (eg: css modules)
- phenomic plan to have more built-in features like search, pages for tags, categories, author etc

Phenomic is under heavy development (check out contributors and activity graphs)
- https://github.com/MoOx/phenomic/graphs/contributors
- https://github.com/gatsbyjs/gatsby/graphs/contributors

**Comment by DominicTobias** [comment]
It does allow you to extend the config however you please though https://github.com/gatsbyjs/gatsby#how-to-use-your-own-webpack-loaders

**Comment by thangngoc89** [comment]
@DominicTobias you have a normal webpack config file with Phenomic. Edit it however you want. No need to learn different syntax ;)

**Comment by MoOx** [comment]
@DominicTobias whether it's new or I missed it, it's not as straight forward as normal webpack config. That's imo the reflect of gatsby: API seems awkard to me.

**Comment by DominicTobias** [comment]
Yeah I'm new to both just trying to understand the differences, I do also prefer more transparent control over config

**Comment by thangngoc89** [comment]
Gatsby do have some tests right now https://github.com/gatsbyjs/gatsby/tree/master/test

**Comment by MoOx** [comment]
Just a few, but better than nothing :)

**Comment by thangngoc89** [comment]
> gatsby require a global install

It's not true with gatsby > 0.9 . In facts, local install is the only way that you can make a website with gatsby right now.

**Comment by thangngoc89** [comment]
> gatsby is using it's own dependency for babel, react, react-dom, react-router 

I don't think this is a selling point. I think phenomic is different than gatsby at this point. Phenomic is like a framework and gatsby is like a tool.

**Comment by MoOx** [comment]
Install instruction tell to use -g https://github.com/gatsbyjs/gatsby#install

Ok for route.

Maybe @KyleAMathews can help us to have a more accurate answer.

**Comment by Maxhodges** [comment]
it's a shame these guys don't just collaborate. Phenomic development isn't really any "heavier" than Gatsby. 
![image](https://user-images.githubusercontent.com/957271/28400413-f0cd0f5c-6d4d-11e7-80f2-0fb774e48b59.png)

**Comment by MoOx** [comment]
It's not a shame. Both are now more different than ever. I will create an new FAQ with a response for this.
Gatsby is a bit younger and it most famous, but it does not mean it's "just better".
More details here for now #1122
