### ISSUE TITLE
doc: Add how to add a page

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#330]
you just have to add an .md file to have a new page but that may not be obvious :)

**Comment by thangngoc89** [comment]
And you have to navigate to the new page manually (or trigger a full page reload). We can't hot load it yet.

**Comment by MoOx** [comment]
maybe we should reload page if new entries are added to avoid this kind of issue? (we should be able to detect entry overthere https://github.com/MoOx/statinamic/blob/13ad6f235f2c240463246782499053f3d6f57321/src/client/hot-md.js - not sure but we should try).

**Comment by thangngoc89** [comment]
@MoOx I'm not sure. last time I check, webpack can't load the new file. Will test it
