### ISSUE TITLE
Consider bundle statinamic into a giant file when publishing

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#341]
I would love to avoid this kind of situation in the future. 

https://medium.com/@Rich_Harris/how-to-not-break-the-internet-with-this-one-weird-trick-e3e2d57fee28#.2abu3vn6z

**Comment by MoOx** [comment]
One downside (not mentionned) are patches. Semver helps you to have patches and new features automatically, even for deps, or deps of deps.

**Comment by thangngoc89** [comment]
Yup. But many people don't follow semver. Patches can break stuff (remember babel releases?  )

**Comment by MoOx** [comment]
Obviously, it was unintentional bug that has been fixed in a couple of hours. How many bugs have been fixed without us noticing those bugs? We don't know.

**Comment by thangngoc89** [comment]
This approach has it cons and pros. Instead of doing this,  I will try reduce the number of packages that statinamic depends on (like underscore.string,  only use 1 method of it).

When I'm looking for the posibility of implementing this. I wonder why did you encourage using modules in the first place ? (Like statinamic/lib/* ).

**Comment by MoOx** [comment]
>  I will try reduce the number of packages

I am always trying to avoid a package when I can.

> When I'm looking for the posibility of implementing this. I wonder why did you encourage using modules in the first place ? (Like statinamic/lib/* ). 

Sorry I don't understand what you want to mean with this sentence.

**Comment by thangngoc89** [comment]
I mean why not export everything in index.js instead of throwing an error ?

**Comment by MoOx** [comment]
This is to avoid client side script to have all statinamic modules.
But sure I will revisit this thing when api become stable.
