### ISSUE TITLE
How to get content of 2 markdown files in 1 component ?

### ISSUE THREAD

**Issue by gristel** [MoOx/phenomic#347]
Hi.
I would like to hear some opinions about creating 1 page that's split in 2 parts, that both have a separate lay-out, so the content would come from 2 different .md files.
I think this might be worth giving a thought?

I hope I explained what I'm trying to say well enough for all of you to understand what I mean :-)

Thanks!

**Comment by thangngoc89** [comment]
Hi, thanks for the interesting feature request. I think what you are asking for is: 

How to get content of 2 markdown files in 1 component. 

This is a hard problem to solve and maybe require a lot of refactor (and maybe re-architecture)

**Comment by MoOx** [comment]
The problem is that currently, md files are associated with an url. Not sure if you are trying to solve your problem with an accurate solution.

Can you explain what problem you are trying to solve underneath?

**Comment by MoOx** [comment]
poke @gristel.

**Comment by MoOx** [comment]
Assuming this was not a good approach to a specific problem. Feel free to continue the discussion if still relevant.
