### ISSUE TITLE
Allow Tabs and Trailing Semicolons in Linting

### ISSUE THREAD

**Issue by srsgores** [MoOx/phenomic#353]
I personally prefer using tabs instead of spaces to help me more easily identify levels of indentation, but this will not be permitted with the current linting process:

> C:\Users\seang\Documents\Github\project\web_modules\Header\index.js
>   11:1  error  Line 11 exceeds the maximum line length of 80  max-len
>   11:2  error  Mixed spaces and tabs                          no-mixed-spaces-and-tabs
>   12:1  error  Line 12 exceeds the maximum line length of 80  max-len
>   12:2  error  Mixed spaces and tabs                          no-mixed-spaces-and-tabs

Here is my formatted version of `Header\index.js` (I personally find this far more readable):

```
import React, {Component} from "react";
import {Link} from "react-router";
import SVG from "react-svg-inline";
import twitterSVG from "../icons/iconmonstr-twitter-1.svg";
import gitHubSVG from "../icons/iconmonstr-github-1.svg";

export default class Header extends Component {
	render() {
		return (
			<header className={styles.header}>
				<nav className={styles.nav}>
					<div className={styles.navPart1}>
						<Link className={styles.link} to="/">
							{"Home"}
						</Link>
						</div>
					<div className={ styles.navPart2}>
						<a href="https://twitter.com/Statinamic" className={ styles.link}>
							<SVG svg={twitterSVG}/>
							{"Twitter"}
						</a>
						<a href="https://github.com/MoOx/statinamic" className={styles.link}>
							<SVG svg={gitHubSVG}/>
								{"GitHub"}
						</a>
					</div>
				</nav>
			</header>
		);
	}
}
```

How can an author configure a statinamic project to use different linting settings, so that tabs and trailing semicolons are permitted?

**Comment by thangngoc89** [comment]
Default boilerplate of statinamic uses [eslint-config-i-am-meticulous](https://github.com/MoOx/eslint-config-i-am-meticulous). You can define your own rule or use some popular rule. See how to do it in the docs http://moox.io/statinamic/docs/advanced/good-practices/#javascript-linting

**Comment by MoOx** [comment]
You can currently (if you want to keep most rules that are used by default), just add a bit of config like this in your package.json:

```js
  "eslintConfig": {
    "parser": "babel-eslint",
    "extends": [
      "eslint-config-i-am-meticulous/react"
    ],
    // add the section below after the section above 
    "rules": {
      "indent": ["error", "tab"] 
    }
  },
```

See http://eslint.org/docs/rules/indent for more information about this rule.

You might also want to adjust http://eslint.org/docs/rules/max-len according to the errors you are showing.

When you made your changes, you can use `eslint --fix` (probably `eslint --ignore-path .gitignore --fix .` to ignore node_modules and all builded files) to auto fix all indentations according to your new rule.

I hope this instructions are correct and works for you..

**Comment by MoOx** [comment]
@srsgores is this ok?

**Comment by thangngoc89** [comment]
No activities. Close for now. Feel free to reopen it.

**Comment by Maxhodges** [comment]
@srsgores Spaces are mandated at our organization. Tabs are not consistent enough across editors and terminals and we got tired of having to reconfigure every editor and terminal in order to display source correctly. Spaces are my far the preference among JavaScript repos on github (a sample analysis of over 300 projects determined that only 13% used tabs. (60% used w spaces and 27% used 4 spaces)

**Comment by srsgores** [comment]
@maxhodges, the question was answered by @MoOx.  I was not asking for your justifications in your organization.

**Comment by Maxhodges** [comment]
Well to be honest no one asked if you personally perfect tabs did we?

**Comment by srsgores** [comment]
@Maxhodges, that's fair.  I was just trying to give some context.  We're all good now that @MoOx has explained the configuration of eslint 🌞 .

**Comment by MoOx** [comment]
Bikeshedding is not necessary at this point :)
