### ISSUE TITLE
[doc] HowTo

### ISSUE THREAD

**Issue by gristel** [MoOx/phenomic#354]
Hi.
I wanted to share my first 'article' about Statinamic. I will become some sort of tutorial on how to rebuild a website using Statinamic.
The first draft of the first article can be found here:
https://medium.com/@gristel/28653ed6d74b
Feel free to leave as many notes and comments as you like, before I publish it.

Thanks.

**Comment by MoOx** [comment]
That would be nicer to have this in the doc (to keep something up to date). Don't you think?
Also the name is going to change soon...

(Sent from my phone)

**Comment by thangngoc89** [comment]
Hi thanks for you article. It's very nice.

**Comment by gristel** [comment]
Well, the plan is to combine this with the docs.
For now, the medium blog is an "initial writing". Once it's finished, we can merge it with the docs?

**Comment by thangngoc89** [comment]
> we can merge it with the docs

Yes. Absolutely.

**Comment by gristel** [comment]
Edited draft with comment about postcss / cssnext

**Comment by MoOx** [comment]
Closing as it's not really an issue.
@gristel feel free to poke us with new post on gitter, you know the way ;)

Btw, you should update Statinamic to Phenomic :)
