### ISSUE TITLE
Modularize content folder

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#356]
Continue from #147 , but this time, make it a built-in Statinamic feature.

---

Currently, we have a folder that contains all assets for the website. And then we'll mount this folder to a route on dev mode. Or copy it to dist folder before Webpack build. [More info](https://github.com/MoOx/statinamic/blob/eb4e94ff4d4843a258a8f2fbda7087c173b66c28/src/configurator/validators/assets.js)

At first, it's sound like a good solution, but when your website get fat, it's horrible to manage all of those assets. You have to type absolutely url when embed a image. And it get worse when you change the route (trust me, brutal replacement is horrible).

So here is my proposal to "modularize" posts: 

For each post, we'll create a new folder looks like this: 

```
YYYY-MM-DD-my-awesome-post
|__index.md
|__my-image.jpg
```

`index.md` content: 

```md
---
route: my-awesome-post
---

<img src="./my-image.jpg" />
```

This is how to dist folder looks like: 

```
/my-awesome-post/
|_index.html
|_my-image.jpg
```

AFAIK there is no easy way to implement this atm in dev mode. Any thought ? @MoOx 

----

Update: [gatsby's implementation](https://github.com/gatsbyjs/gatsby/blob/b1200bcf729b99e817f02d6982eae2227e01b4d4/lib/utils/post-build.js#L18-L21)

**Comment by MoOx** [comment]
It's pretty easy and you can do this already.

- https://github.com/putaindecode/putaindecode.io/blob/381503c68be9c25403e40408f8dd1d2ede1e6089/scripts/index-client.js#L1-L3
- https://github.com/putaindecode/putaindecode.io/blob/381503c68be9c25403e40408f8dd1d2ede1e6089/scripts/webpack.config.babel.js#L64-L69

See #103

**Comment by MoOx** [comment]
Eg: https://github.com/putaindecode/putaindecode.io/tree/381503c68be9c25403e40408f8dd1d2ede1e6089/content/fr/articles/twitter/comme-lecteur-de-flux

**Comment by thangngoc89** [comment]
@MoOx awesome. I'm trying it.

**Comment by thangngoc89** [comment]
You webpack configuration doesn't sastify my proposal. It doesn't work if I define a different route in frontmatter. Jekyll convention is adding YYYY-MM-DD to filename to have a good post order out of the box (this is a good convention for a blog)

**Comment by gristel** [comment]
I've seen a few other static website generators following that convention. It makes sense to me.

**Comment by thangngoc89** [comment]
@gristel they follow Jekyll convention. Jekyll is the most popular static site generators

**Comment by MoOx** [comment]
> Your webpack configuration doesn't sastify my proposal.

I guess we need something that will follow the route. Not an easy thing to solve. That means we will need to parse url in the md to resolve those file via webpack? So that basically handling #147?

**Comment by thangngoc89** [comment]
> So that basically handling #147?

Maybe. But is it a good idea to make webpack loader stateful ?  I know it is stateful atm,  but it's just the collection

**Comment by MoOx** [comment]
It's called "content-loader", so it's not stupid to use it to resolve path. But maybe we can use another loader indeed, like css-loader can parse url() and style-loader handle the runtime part.

**Comment by thangngoc89** [comment]
Good idea. :+1: I still like the idea of user can replace the loader if he/she doesn't like the way it behaves.  Breaking it to multiple loader is a good solution to that. But in order to pass url, the markdown file has to be required somewhere. So we need to ditched babel plugin first. cc #301

**Comment by MoOx** [comment]
I consider this as a dup of #147
