### ISSUE TITLE
Boilerplate/Theme collection

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#359]
I started porting nice themes from other static site generator to Statinamic.

I'll use this issue to track all avaiable boilerplate/theme avaiable until we have a page delicated for this

If you created a nice theme for Statinamic, please comment below and I'll add it here.

# Lumen 

- Ported from [gatsby-starter-lumen](https://github.com/hb-gatsby/gatsby-starter-lumen)
- Repo: https://github.com/thangngoc89/statinamic-theme-lumen
- Demo: https://khoanguyen.me/statinamic-theme-lumen/

![image](https://cloud.githubusercontent.com/assets/3049054/14208540/3636f870-f84a-11e5-95f7-869679cfa577.png)

**Comment by gristel** [comment]
I love it.
Very soon I'll be able to help you with this!

**Comment by MoOx** [comment]
We should find a smart way to clone a boilerplate/theme during the setup.
Btw, maybe we should find a smart way to extends/override a theme without touching it. This way we can call that "theme".

**Comment by thangngoc89** [comment]
Absolutely. But it should be after 1.0

**Comment by MoOx** [comment]
We should think about that before 1.0, to avoid a huge refactor to be able to handle this, but I think a trick with webpack alias can make this very easy :)

**Comment by MoOx** [comment]
Closing this until we handle #508. We might revisit this when we will have a better official support for that.
