### ISSUE TITLE
flow interfaces

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#360]
@thangngoc89 any reason you choose flow-interfaces instead of this https://github.com/marudor/flowInterfaces ?

**Comment by thangngoc89** [comment]
I'm just too lazy to cherry pick each packages that I'll use. So I choose flow-interfaces,  install and forget about it.

There is plan to merge those two : https://github.com/TechnologyAdvice/flow-interfaces/issues/2

**Comment by thangngoc89** [comment]
FYI: https://github.com/flowtype/flow-typed

**Comment by MoOx** [comment]
Yeah, all those different way are just a huge mess. But maybe this one is the better... We should post our interfaces over there.

**Comment by thangngoc89** [comment]
> We should post our interfaces over there. 

Really ? I thought those definitions are for project that doesn't use flowtype

**Comment by MoOx** [comment]
I mean the external-modules we have

**Comment by MoOx** [comment]
This had been handled in 0.16.0 \o/
