### ISSUE TITLE
Improve React's performance in production build

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#377]
Read this article https://reactjsnews.com/how-to-make-your-react-apps-10x-faster

TL;DR: Add 2 babel plugins for production build 

```
"transform-react-constant-elements",
"transform-react-inline-elements"
```

I tested this on my blog, it reduces 200ms on painting

---

Update: Also `transform-react-remove-prop-types` because React doesn't check for propTypes in production anyway.

**Comment by thangngoc89** [comment]
Looks like some one pull all of these plugin into a single presets

**Comment by MoOx** [comment]
So should be easy to add this

**Comment by thangngoc89** [comment]
Done in #429
