### ISSUE TITLE
Inject sw-register.js into the main js bundle

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#398]
Since sw-register.js is pretty small, making another http request to get it is costly. We should inject it to the main js bundle instead.

---
Below is the plan by @MoOx 

In config we have `config.webpackConfig` and `config.webpackConfigClient`. We can inject the file we want in `config.webpackConfigClient.entry.phenomic-client` (btw, we may validate that this entry name exist, or at least that there is one).

For the injection we can do: 
- if there is a single entry, just append (entry can be a path OR a array of path)
- if there is multiple entries, and one is called phenomic-client, append to this one.
- if there is multiple entries, and no one is called phenomic-client, throw an error for now (if people ask we might allow the name to be changed, but not for now - or if you want, add a param in config like "entryToInjectScripts", default to phenomic-client, cause maybe we might add more for other features).

**Comment by MoOx** [comment]
Will automatically added to phenomic.browser entry (this entry is always present now, since it's now injected).
