### ISSUE TITLE
Custom service worker logic

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#399]
~~Current sw logic is not different than appcache.~~ (see #405)

SW logic is smarter than appcache because it can cache files on demand. But there should be an option to let user define their own service worker logic (by giving a lodash's template path).

**Comment by thangngoc89** [comment]
Actually, providing above logics is unneeded. We only need to provide a default SW logic which cache everything in the same origin on demand. User can choose which to cache initially via globby pattern.

If they do need a custom logic, provide a path.

**Comment by MoOx** [comment]
> If they do need a custom logic, provide a path.

I guess they can just add an new entry in webpack client side config?

**Comment by thangngoc89** [comment]
> I guess they can just add an new entry in webpack client side config?

Not possible at the moment. They don't have a list of all assets before compilation.

**Comment by MoOx** [comment]
That's why I was saying we should consider webpack define plugin, so people can use some constantes everywhere.

**Comment by MoOx** [comment]
Not sure if that's doable tho, depends on the plugin hook execution.

**Comment by thangngoc89** [comment]
> depends on the plugin hook execution.

Webpack plugin can get all the assets which were emitted by Webpack. (see https://github.com/NekR/offline-plugin) 

But I don't choose this at the beginning because we copy assets with fs and produce `*.html` files after webpack build. If we can inject these information to webpack, it would be great.

**Comment by MoOx** [comment]
We can probably do that by make a custom (simple) plugin.

**Comment by thangngoc89** [comment]
Haha. We'll will see. I can't understand webpack internal API. So many concept.

**Comment by MoOx** [comment]
We can just add in doc a ref to the offline-plugin which is the solution we will use soon.

**Comment by MoOx** [comment]
Closing in favor of #535
