### ISSUE TITLE
Consider replacing redux in favor of react context

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#40]
Since we don't do a lot of modifications (ie: no modification at all for now), we might consider replacing redux usage by react context (that are now documented http://facebook.github.io/react/docs/context.html).
That should be clearly enough to just "pass" some data (collection and page components references) that are declared during app initialization.

It don't really see any downside from the current usage.

Any thoughts? poke @bloodyowl

**Comment by bloodyowl** [comment]
I'd really say it depends on what you try to achieve. statinamic already seems opinionated on some parts, and I see it more like a boilerplate than a library. if you want to provide a way to manage data across components whatever the tree structure is in this boilerplate, then I'd say keep redux. If you want it to be more of a library, keep it minimal, and just use your own provider and decorator.

**Comment by MoOx** [comment]
Statinamic is a collection of lib + a boilerplate generator + docs: you start with a boilerplate that use statinamic libs to help you generate a website with react and webpack. So Statinamic is opininated because of these 2 things (react and webpack). Except that nothing is mandatory (no required structures etc).
You can use the webpack config you want, your own loader, and any npm module you want in your components.

There is a minimal boilerplate that is required to allow some flexibility (choose your styles flavor (inline, css modules, sass...) and I am currently writing a helper to generate the minimal required boilerplate.

The idea is to allow to create a website very easily with one command `$ statinamic setup`: this will generate the boilerplate that use Statinamic libs. The only things that Statinamic uses are:
- a registry to access page data
- a registry to get available pages layouts (component references) that can be used from md header

Not a lot of things, no user interaction. That's what I was thinking about using react context instead of redux. Currently there is already a context provider to share some metadata about your project (eg: package.json to get homepage url, stuff like that) and I was thinking about using it for all the shared (read only - or sort of) data. The only interaction is: you click on a link, if page data are not in the store, we fetch a json to get those.

**Comment by thangngoc89** [comment]
I use redux in almost every project so using redux is one the reasons why I use statinamic.

Also with redux, I can just add reducers that listen for default action of statinamic. Some example use cases: show a loading indicator when getting new page's info. show a error message when getting new page's info failed, ...

In the other hand, keeping redux would make statinamic too opinionated.

**Comment by MoOx** [comment]
> show a loading indicator when getting new page's info. show a error message when getting new page's info failed, ...

I think thoses things should be possible without redux (and more easy to implement without using redux).

I will try to avoid redux and maybe will consider removing it.

**Comment by thangngoc89** [comment]
I think we should consider this again. I don't see the benefit of using redux anymore. We aren't modify anything in the state (just add more page).

This should be a good alternative solution
https://github.com/heroku/react-refetch

**Comment by MoOx** [comment]
I think we should not need anything if we remove redux. All the logic for downloading is in PageContainer, maybe we can make a simple fetch/registry directly in here for now. And that might help for hot loading md.

**Comment by thangngoc89** [comment]
It is your call. Removing redux would help us reduce the bundle size

**Comment by MoOx** [comment]
Totally. That's why I opened this issue in the first place :)

**Comment by thangngoc89** [comment]
So. Shall we change status of this issue ?

**Comment by MoOx** [comment]
Done :)

**Comment by thangngoc89** [comment]
I think that implement this would be easy, just mutate a window object. :dancer:

**Comment by MoOx** [comment]
An alternative http://madx.me/articles/a-simpler-alternative-to-flux-and-redux.html poke @madx

**Comment by arlair** [comment]
I was investigating this tool to use with a MobX store app, so removing Redux is 👍  from me.

**Comment by MoOx** [comment]
Will be handled soon (hopefully)

**Comment by dab** [comment]
Any updates on this issue? It's really nice to have easy way to add your preferred state store. I'm also using mobx currently, and would like to add it to my static site app as well. It's not *such* simple to replace redux right now.
Thanks.

**Comment by MoOx** [comment]
I will try to work on that for the next release. Should not take that long.

**Comment by dab** [comment]
👍 thanks for the update

**Comment by bloodyowl** [comment]
Going to be fixed with #925
