### ISSUE TITLE
Improve hot markdown reloading performances

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#400]
Currently, `content-loader` is not cachable because it need to update the in-memory collection.
By breaking it into 2 parts, we can make it partially cacheable.

- `content-loader`: Loader, parse content and return an object. This loader is cachable.
- `collection-loader`: Emit files, update collection, generate feeds. (also resolve #260 when doing this)

We must the old `content-loader` a little while for backward compat.

**Comment by MoOx** [comment]
Maybe we can have 2 loaders internally and expose one that merge both or something like that? For example ExtractTextPlugin does something similar.

**Comment by thangngoc89** [comment]
I doesn't know it's possible. I'm all for it.

**Comment by MoOx** [comment]
> I doesn't know it's possible. I'm all for it.

It is, extract text plugin does that.

**Comment by MoOx** [comment]
Will be improved by #532 and maybe #646
