### ISSUE TITLE
PageContainer component doesn't work on IE10

### ISSUE THREAD

**Issue by kuzvac** [MoOx/phenomic#407]
We need to add `import "babel-polyfill";` to src/PageContainer/components.js because [collection.find](https://github.com/MoOx/phenomic/blob/next/src/PageContainer/component.js#L49) not works in IE10. With polyfill it works :)

**Comment by thangngoc89** [comment]
Thanks for reporting this. But I don't think we will inlude this to the boilerplate by default. It slows down the app. I usually cherry pick these polyfill.(babel-polyfill is big)
Also,  this is interesting 

https://cdn.polyfill.io/v2/docs/

**Comment by thangngoc89** [comment]
By the way, you can add it to `index-client.js` or any file that will be loaded on the first load. It's a polyfill,  it  mutate the global object

**Comment by kuzvac** [comment]
> https://cdn.polyfill.io/v2/docs/ 

It's really interesting, thank you.

**Comment by MoOx** [comment]
We should remove the call of this method, it should work at least for IE10. Or find a small polyfill. Not sure what is the best.

**Comment by thangngoc89** [comment]
Speaking of browser compat, safari 8 doesn't support string.prototype. endsWith ,  this break react-router.

**Comment by thangngoc89** [comment]
Closed by https://github.com/MoOx/phenomic/commit/390d25098d2ed63d7d29c5d816fce6154f52894f
