### ISSUE TITLE
Split to 2 bundles for boilerplate and docs  (user code + deps)

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#411]
Ref https://github.com/MoOx/phenomic/pull/404#issuecomment-211947320

**Comment by thangngoc89** [comment]
Actually, we should do this for dev server as well. It helps reducing rebuild time.

By the way, js order in the dev server is not the same as production bundle. So fix it too.

**Comment by MoOx** [comment]
> By the way, js order in the dev server is not the same as production bundle. So fix it too.

Can you give more details about this?

**Comment by thangngoc89** [comment]
The order of js script tags. On production bundle,  it is ordered a-z. But on dev server, there is not code to order it yet. We just use webpack's order.

**Comment by MoOx** [comment]
Will revisit this later, not a priority atm.
