### ISSUE TITLE
Styles on Safari iOS are broken on some pages

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#413]
Eg: https://phenomic.io/docs/setup/ from my iPhone: styles broken.
If I go to homepage, refresh, styles are ok. I navigate to this page, styles are still ok since client side browsing is enabled. Need to investigate.

I have homepage on 0.11 and setup page with 0.10.2. That's the weird part. Not sure how to make a full refresh on Safari iOS.

**Comment by MoOx** [comment]
Maybe related to appcache or sw.

**Comment by thangngoc89** [comment]
It's ok on my android phone with chrome. Maybe you can wait a little longer to leave time for appcache to be updated and than refresh the page

**Comment by magsout** [comment]
It's ok on my iPhone

**Comment by magsout** [comment]
![image](https://cloud.githubusercontent.com/assets/1997108/14650669/fd173286-066c-11e6-860b-e445533c9fa1.png)

**Comment by MoOx** [comment]
I checked with Safari debugger

> Did not parse stylesheet at 'https://phenomic.io/phenomic-client.fddce1fe23979242a9c5.css' because non CSS MIME types are not allowed in strict mode.

Continuing my investigation.

**Comment by MoOx** [comment]
Ok, https://phenomic.io/phenomic-client.fddce1fe23979242a9c5.css is now a 404, and the html page has been cached (probably because of appcache). Refreshing and waiting (and refreshing) does not help.

**Comment by thangngoc89** [comment]
> Ok, https://phenomic.io/phenomic-client.fddce1fe23979242a9c5.css is now a 404

It is a 404. new url is https://phenomic.io/phenomic-client.6d29c921b25166eeede0.css 

FYI, I turned off appcache, it's so annoying.

**Comment by MoOx** [comment]
That's what I said.

Appcache is just broken. I can't find a fucking way to update the page. I guess I will have to have a js update or something.

**Comment by thangngoc89** [comment]
Try to deploy a new version with appcache disabled. Appcache will goes away on second reload.

**Comment by MoOx** [comment]
If I do that, I assume that appcache is so broken and will disable it by default with "offline": true.

**Comment by thangngoc89** [comment]
It's fine to me. Disable it.

**Comment by MoOx** [comment]
Appcache is shit. We need to handle #277, there is probably a similar thing to do for SW?
