### ISSUE TITLE
Meta description should remove new lines.

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#414]
It's useless.

**Comment by thangngoc89** [comment]
It's simple delete all Break node in MDAST https://github.com/wooorm/mdast#break

**Comment by MoOx** [comment]
Or just remove "\n" in the string, even simpler imo.

**Comment by MoOx** [comment]
Replace "\n" by a space.

**Comment by thangngoc89** [comment]
LOL. It's much better.
