### ISSUE TITLE
Add one line setup in docs

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#416]
Should work this way

```console
DIR=your-website-folder && mkdir $DIR && cd $DIR && mkdir node_modules && \
npm i phenomic && ./node_modules/.bin/phenomic setup && npm i && npm start
```

**Comment by slybridges** [comment]
hey there :smile: 

New user here, looking forward to playing around with phenomic. Awesome job btw !

Doesn't `npm i ` only work if you either have a `package.json` file or a `node_module`subdirectory inside of `$DIR`?  

In my config at least the commands above didn't install phenomic in `node_modules` and I had to manually create `node_modules` to make it work:

```bash
DIR=your-website-folder && mkdir $DIR && mkdir $DIR/node_modules && cd $DIR && \
npm i phenomic && ./node_modules/.bin/phenomic setup && npm i && npm start
```

**Comment by thangngoc89** [comment]
Poke @MoOx .  could you confirm this?

**Comment by slybridges** [comment]
Tested using: 
- npm 3.8.8 
- node 5.10.1
- Ubuntu 15.10

**Comment by MoOx** [comment]
Oh I guess that why `npm init -f` was used for. Maybe we can add `mkdir node_modules` too?

**Comment by slybridges** [comment]
yep, creating `node_modules` too like in the command line above make it work like a charm.

**Comment by MoOx** [comment]
The nice thing to do is to offer this line with an input for the project name, so people can copy the line from the website homepage :)

**Comment by thangngoc89** [comment]
This is even shorter: 

```console
DIR=your-website-folder && mkdir -p $DIR/node_modules && cd $DIR && \
npm i phenomic && ./node_modules/.bin/phenomic setup && npm i && npm start
```

**Comment by MoOx** [comment]
A windows equivalent will be nice, with an adjustment depending on the navigator user agent :)

**Comment by thangngoc89** [comment]
Windows (not tested yet): 

```
mkdir your-website-folder/node_modules && cd your-website-folder && npm install phenomic && node ./node_modules/.bin/phenomic setup && npm i && npm start
```
