### ISSUE TITLE
Question: How to specify text render engine?

### ISSUE THREAD

**Issue by arve0** [MoOx/phenomic#417]
The docs state that one can use [whatever text rendering one likes](https://github.com/MoOx/phenomic/blame/next/docs/content/docs/usage/write.md#L13), and refer to [configuration](https://github.com/MoOx/phenomic/blob/next/docs/content/docs/usage/configuration.md). But I'm unable to find how to configure the text rendering. Am I blind, or isn't it documented yet?

**Comment by MoOx** [comment]
It's not documented yet but it's simple.

In `scripts/webpack.config.babel.js` in the `query` section of the `phenomic/lib/content-loader` (for example [right after `context`](https://github.com/MoOx/phenomic/blob/505501f0891e76f8d714584b59efc8ae4ad861d9/boilerplate/scripts/webpack.config.babel.js#L17)), you can add a [`renderer` option](https://github.com/MoOx/phenomic/blob/505501f0891e76f8d714584b59efc8ae4ad861d9/src/content-loader/index.js#L29) that accept text (md?) as first parameter and must return html ([here is the default renderer](https://github.com/MoOx/phenomic/blob/505501f0891e76f8d714584b59efc8ae4ad861d9/src/content-loader/default-renderer.js#L7), note that the es6 arrow means function syntax is returning something).

Will add that into the doc for next release. Thanks for raising this :)

Tell me if that enough or not clear.

**Comment by ben-eb** [comment]
@MoOx The `renderer` doesn't get passed to `content-loader`. I tried adding a `foo` property which went through, but `renderer` doesn't. Config is the same as in the boilerplate, I just defined a `renderer` function outside and added it in...

```js
const renderer = text => text;
// ...
      { // phenomic requirement
        test: /\.md$/,
        loader: "phenomic/lib/content-loader",
        query: {
          context: path.join(config.cwd, config.source),
          renderer,
          feedsOptions: {
            title: pkg.name,
            site_url: pkg.homepage,
          },
// ...
```

Seems strange but this property is `undefined` when I log `query.renderer` (before it is overridden by the default renderer).

**Comment by thangngoc89** [comment]
@ben-eb you should blame webpack for that. It filtered all functions from loader's query. You can move all the loader's query to webpack config object (just like postcss-loader)

https://github.com/thangngoc89/blog/blob/59a60ac4b828826dbcab94bf4f6eb8f901236f21/scripts/webpack.config.babel.js#L75-L118

**Comment by MoOx** [comment]
We should warn about that.

**Comment by thangngoc89** [comment]
@MoOx How about move the loader query to webpack config object by default ?

**Comment by MoOx** [comment]
The problem with that is that it make it hard to handle 2 formats (eg: md and .txt)
But I guess it's simpler by default...

**Comment by ben-eb** [comment]
@thangngoc89 Thanks, that worked. Was definitely thrown off by the boilerplate config as it includes a commented out `renderer` function in the same place that I had it. 😄
