### ISSUE TITLE
Upgrade to webpack@2

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#421]
I am currently trying it on a project and there is not a lot of breaking changes, so should not be a big deal.
Still flagged as beta, but for a while so I think it's pretty mature now.

**Comment by thangngoc89** [comment]
I think webpack 2 is stable enough to be used in phenomic. I use it in several project right now. 

I read somewhere that webpack's team is focused on making the documentation better atm. And working on the next version.

**Comment by MoOx** [comment]
Same here, using v2 for a while now.

Indeed they works on the doc to remove "beta" flag :)

**Comment by thangngoc89** [comment]
I gave this a try and find out that, because of the mix between node and webpack environment, we can't disable commonjs module transformation in babel :/ . Any suggestions?

**Comment by MoOx** [comment]
We might disable it for client build, not node build. Not possible?

**Comment by thangngoc89** [comment]
AFAIK, It's not possible (or I'm overthinking).

**Comment by MoOx** [comment]
We are talking about disabling/enabling a specific babel plugin depending on the env right?

**Comment by thangngoc89** [comment]
I give this another try tonight.

**Comment by MoOx** [comment]
Will try too. I won't cut a new release until this is done anyway, since #714 sucks!

**Comment by MoOx** [comment]
On it.

**Comment by MoOx** [comment]
OK it was alsmost easy until you want to disable es2015 modules for webpack only :)

**Comment by MoOx** [comment]
Now the tricky part is react-hot-loader update :)

**Comment by thangngoc89** [comment]
:+1:

**Comment by thangngoc89** [comment]
Tracking this https://github.com/mzgoddard/hard-source-webpack-plugin/issues/27

**Comment by MoOx** [comment]
Closing in favor of #737
