### ISSUE TITLE
Docs: new homepage

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#423]
Here is the plan [WIP]. Feel free to bring ideas.

---
# Phenomic
## Simple and powerful

Write with Markdown, HTML or anything else you want. Boost with JavaScript and React.
Customize anything. No template language to learn. Just JavaScript (and JSX if you like it).
### Static and Dynamic

No database or dynamic server to configure.
Just files and one command to generate your website/webapp that you can host anywhere for free.

Offer a top-notch UX to your users.
Enjoy the best DX as a writer and developer.
## Easy setup with a highly capable boilerplate

1 command to setup a website or webapp in a minute.
1 command to write and develop.
1 command to build and optimise.
1 command to publish (and you just have static files to serve).

Infinite possibilities, with a lot already built-in in the default skeleton (search, blog etc).
## Optimized UX

No reload between pages, enjoy a smooth & fast navigation, with built-in offline capability.
Page transition are optimised with a enhanced discret loading animation (that you can customize).
## React and NPM ecosystem

You can just grab some packages on the NPM ecosystem to help you build your website, blog or even a small app.
Phenomic will help you generate and deploy a website in a heartbeat.
### ~~Isomorphic~~ Universal by default

Works as HTML and as a web app.
## Optimized DX

Live-edit for content, layouts and any UI element thanks to React Hot loading
## Flexibility

Full control (on almost anything)
## @todo Migrations

See https://import.jekyllrb.com/

**Comment by thangngoc89** [comment]
So this will be a normal markdown rendered page ? How about a delicate page with React components ?  A bootstrap like landing page should do the job

**Comment by MoOx** [comment]
That's just the plan. Not the technical implementation. This will definitely be a dynamic page with React components.

**Comment by MoOx** [comment]
I just saw this http://jekyll.tips/ which is nice and clear.
