### ISSUE TITLE
Online demo boilerplate

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#424]
It would be nice to have the default boilerplate online.

**Comment by thangngoc89** [comment]
fyi: https://phenomic.surge.sh

I think it's a good idea to use another hosting service to deploy boilerplate.

**Comment by MoOx** [comment]
We can just put it under /demo/
What's wrong with that?

**Comment by thangngoc89** [comment]
Nothing. But it make build step more complicated. Maybe a subdomain ?

**Comment by MoOx** [comment]
No, it won't be complicated at all, don't worry ;)

**Comment by MoOx** [comment]
demo.phenomic.io or phenomic.io/demo?
Wait stop. What about this:

themes.phenomic.io/base or phenomic.io/themes/base?

I think phenomic.io/themes make more sense as we might offers an official "catalog" one day or another?

**Comment by thangngoc89** [comment]
See http://themes.gohugo.io/ if you need inspirations. I think we should go with Hugo's way

**Comment by DavidWells** [comment]
`phenomic.io/themes/base` looks prettier to me but might be harder to maintain.

The subdomain approach might be easier in the long run.

You could have all the themes live on the subdomain and still have a phenomic.io/themes/ page that acts like http://demo.mythemeshop.com/s/?theme=myPortfolio (Not endorsing the design here). It's just a simple iframe that loads in a different URL when you choose a different theme.

**Comment by MoOx** [comment]
We now have the base theme here https://phenomic.io/themes/base/demo/
The way it's deployed is probably temporary until we make a gallery or something like that.
