### ISSUE TITLE
Boilerplate: add Disqus and Google Analytics

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#428]
setup should ask user for their id, and if present, boilerplate should contains required components.

**Comment by thangngoc89** [comment]
The components part is easy. But how to add/remove them according to user's answer ?

**Comment by MoOx** [comment]
Meanwhile for GA:
- https://github.com/MoOx/phenomic/blob/b641f0f6eea2979604cb5e785b581bfeb54bfcf5/docs/src/AppContainer.js#L15
- https://github.com/MoOx/phenomic/blob/b641f0f6eea2979604cb5e785b581bfeb54bfcf5/docs/src/components/GoogleAnalyticsTracker/index.js

**Comment by thangngoc89** [comment]
There is a tutorial https://theduke.at/blog/develop/how-to-use-google-analytics-with-phenomic/

**Comment by DavidWells** [comment]
This is tricky. I think we should provide an easy way for folks to do this, but GA can be implemented via this component OR via something like segment.io

Perhaps giving users a way to inject custom html/js into the footer of the page would solve this.

Probably one of the hardest things to do with a dynamic site like this is adding custom scripts to given pages b/c you have to learn and use `<Helmet>`

Netlify has a pretty nifty feature that lets you inject any custom stuff you want into your site after it's build process is done:

![image](https://cloud.githubusercontent.com/assets/532272/19228967/ea55d82e-8e7e-11e6-9057-89716474a64d.png)

Just thinking it might be cool to start potentially thinking about this for phenomic as perhaps some `customBuildHooks` or something.

**ORRRR even better,** giving the user access to the `index.html` template and they could add/configure these global scripts/third party deps in there.

Sorry for rant =)

**Comment by MoOx** [comment]
I really don't want to allow an index.html template: this does not make sense. When you are on the client side, the code won't be executed on each pages, just once!

Helmet is pretty easy to "learn" and I think we can add example in the docs.

**Comment by xuopled** [comment]
@thangngoc89 I saw you use [autotrack](https://github.com/googleanalytics/autotrack) for your `phenomic` project. Can I check somewhere how you did ? Thank you

**Comment by MoOx** [comment]
See #384 ;)

**Comment by xuopled** [comment]
Thank you

**Comment by kchens** [comment]
@MoOx and @xuopled should the autotrack set-up in  [@MoOx/react-toulouse@c42045d](https://github.com/MoOx/react-toulouse/commit/c42045d1001ab813c5d7eae5ab2f4f8c08c0025e)  still the best way to set-up GA? Not sure if it matters but autotrack got bumped up to 

I prefer to have auto-tracking, but I ended up having to set-up react-ga for the time being.

**Comment by xuopled** [comment]
I finally used `react-ga` and it works well

**Comment by MoOx** [comment]
I just checked my current setup for react-toulouse website and it's working like a charm (checked using real-time tracking). I didn't update tho.
Just be sure to check with a browser without adblocks and in a private tab ;)

**Comment by DavidWells** [comment]
Interesting. @moox do you no longer need react-ga with the auto track setup? https://github.com/MoOx/react-toulouse/commit/c42045d1001ab813c5d7eae5ab2f4f8c08c0025e

**Comment by kchens** [comment]
I followed the steps in several times.  @MoOx/react-toulouse@c42045d

I get this error though
`Uncaught SyntaxError: Unexpected token import
    at Object.<anonymous> (phenomic.browser.07e4847….js:3722)
    at __webpack_require__ (phenomic.browser.07e4847….js:556)
    at fn (phenomic.browser.07e4847….js:87)
    at eval (eval at <anonymous> (phenomic.browser.07e4847….js:1788), <anonymous>:58:3)
    at Object.<anonymous> (phenomic.browser.07e4847….js:1788)
    at __webpack_require__ (phenomic.browser.07e4847….js:556)
    at fn (phenomic.browser.07e4847….js:87)
    at eval (eval at <anonymous> (phenomic.browser.07e4847….js:990), <anonymous>:19:21)
    at Object.<anonymous> (phenomic.browser.07e4847….js:990)
    at __webpack_require__ (phenomic.browser.07e4847….js:556)`

**Comment by MoOx** [comment]
@kchens this looks like a webpack configuration issue (saying this because of `Unexpected token import`).
@DavidWells no I don't, but I have still very few visit on this site, so be careful and try on a small period and double check :)

**Comment by yatsyk** [comment]
@kchens The reason of this error is that imported files (for example node_modules/autotrack/lib/plugins/url-change-tracker.js) are not processed by babel. According to webpack config only scripts and src folders are processed. Only node_modules/autotrack/autotrack.js is ready for importing.

**Comment by codepreneur** [comment]
@yatsyk do you have any solutions for this? Cause I am experiencing the exact same problem.

**Comment by yatsyk** [comment]
@codepreneur you can use autotrack by importing autotrack.js with all plugins enabled or use features you need by importing particular files from lib/plugins folder. I think that importing 'autotrack' with all plugins should work without additional settings.

**Comment by MoOx** [comment]
@kchens @yatsyk what version of webpack are you using? Can you share your webpack config?

**Comment by jedau** [comment]
@MoOx I'm encountering the same error as @codepreneur and @kchens I'm on webpack v1.11.0 and I'm using Phenomic's default webpack config. I'm running on phenomic v0.20.3

**Comment by Quinn-H** [comment]
@jedau @codepreneur @kchens I'm also on webpack v1.11.0. I have same error when set-up GA. Did you guys still have this error ?  Any workaround available ? @MoOx

**Comment by MoOx** [comment]
Might add a thing in an example but not a priority for v1.
