### ISSUE TITLE
Config "offline": {  "serviceWorker": true } seems to create appcache too

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#438]
I tried this config and I end up with a `manifest.appcache`. If we provide only one key, should not assume other key is true.

**Comment by thangngoc89** [comment]
> Contains 3 keys. Please be aware that you don't need to define all of 3 keys. They will be defined with their default values.

This is what I wrote from the docs. And this is by design, not a bug.

**Comment by MoOx** [comment]
Technically it's not a bug indeed, but since it's not intuitive, we need to change that.

**Comment by MoOx** [comment]
We can just "throw" a warning, if all 3 keys are not provided.

**Comment by thangngoc89** [comment]
It's a solution but I don't like it. :/

**Comment by MoOx** [comment]
It's better than nothing right?

**Comment by thangngoc89** [comment]
Nah. I don't think so. The reason I implemented this kind of behavior in the first place because I don't want to force user to remember (or check the docs) for all the keys needed.

**Comment by MoOx** [comment]
Yeah but UX is bad because if you don't read the doc (or too quickly) you get an unexpected result and you will end up asking for help.

**Comment by thangngoc89** [comment]
Okie. Let's go with throwing error. #415 will resolve all the UX issues

**Comment by MoOx** [comment]
There is no silver bullet. Not sure a command will solve all problems like that.

**Comment by thangngoc89** [comment]
Right. But first thing first, resolve this issue first

**Comment by MoOx** [comment]
For now no more offline feature in v1. We will review this later.
