### ISSUE TITLE
phenomic.node build might create some files in scripts/_

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#439]
This can happen if you have some files loaded using file-loader.
A cleanup is made for the extracted css (to only keep phenomic.node.bundle.js), so we should add this to the cleanup.

**Comment by thangngoc89** [comment]
This depends on the webpack setup. And it's really annoying. In my case, I can't have a pattern to ignore unneded files in my scripts folder 

![image](https://cloud.githubusercontent.com/assets/3049054/15066159/2018f1c6-1391-11e6-88e5-263a980a9db9.png)

We can have a temp working folder and delete that folder after build

**Comment by MoOx** [comment]
No we can't use a temp working dir since during the commonjs build, path are relative.
Well maybe we can but we need the exact same depth in the tree so link to node_modules (that are transformed by webpack to relative links) need to be working).
