### ISSUE TITLE
Better Logo

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#441]
Current logo does not looks great. We need a better one.

**Please use GitHub reactions when you like the idea behind a shot.**

**Comment by DavidWells** [comment]
Maybe something like this? http://codepen.io/DavidWells/pen/XdOVOj =)

**Comment by MoOx** [comment]
Haha. Nice effect.
I am more thinking about a logo with an icon that can be used as an avatar.

**Comment by MoOx** [comment]
Some ideas for inspiration:

- https://thenounproject.com/search/?q=atom
- https://thenounproject.com/search/?q=molecule

**Comment by MoOx** [comment]
Dirty shot with ADN in mind

![screen shot 2016-05-18 at 23 55 06](https://cloud.githubusercontent.com/assets/157534/15376237/fc904d18-1d53-11e6-8952-f804a2fc9e6a.png)

**Comment by MoOx** [comment]
![screen shot 2016-05-19 at 00 05 28](https://cloud.githubusercontent.com/assets/157534/15376465/6a8a824c-1d55-11e6-85f9-5f3f53b6be14.png)

**Comment by MoOx** [comment]
As you can see I am not a designer :D

**Comment by DavidWells** [comment]
What about something like:
https://camo.githubusercontent.com/243622d9da5c5e342224f1f30c50846625eed571/68747470733a2f2f75696b69742d72656163742e66697265626173656170702e636f6d2f696d616765732f6c6f676f2e737667

With the icon inside the react atom.

Then that icon could be the O in phenomic maybe?

**Comment by MoOx** [comment]
I would like to avoid a react like icon. There is already (imo) too many atomic icon (atom, react, redux, etc) and I think a unique identity can be nice.

Will try something with the O in mind. It's a good idea. The letter P is not really cool to work on :)

**Comment by MoOx** [comment]
![screen shot 2016-05-19 at 00 12 25](https://cloud.githubusercontent.com/assets/157534/15376617/6452fc0a-1d56-11e6-9105-bc0089adec90.png)

Going to bed, will try something tomorrow.

**Comment by MoOx** [comment]
![screen shot 2016-05-19 at 00 19 00](https://cloud.githubusercontent.com/assets/157534/15376751/5469cd72-1d57-11e6-96d3-33143eda530d.png)

**Comment by MoOx** [comment]
![screen shot 2016-05-19 at 00 24 00](https://cloud.githubusercontent.com/assets/157534/15376858/02814c3c-1d58-11e6-91d1-34f5fda8f378.png)

**Comment by MoOx** [comment]
![screen shot 2016-05-19 at 06 43 46](https://cloud.githubusercontent.com/assets/157534/15382723/22127d52-1d8d-11e6-9e43-4e99ac070386.png)

**Comment by MoOx** [comment]
![screen shot 2016-05-19 at 06 43 51](https://cloud.githubusercontent.com/assets/157534/15382740/4479677a-1d8d-11e6-8d38-ba632cecc8f1.png)

**Comment by MoOx** [comment]
![screen shot 2016-05-19 at 06 43 54](https://cloud.githubusercontent.com/assets/157534/15382749/5571e354-1d8d-11e6-9979-4a43d40abec0.png)

**Comment by MoOx** [comment]
![screen shot 2016-05-19 at 06 44 01](https://cloud.githubusercontent.com/assets/157534/15382753/60562cc6-1d8d-11e6-8574-b812f231b6bd.png)

**Comment by MoOx** [comment]
![screen shot 2016-05-19 at 06 44 11](https://cloud.githubusercontent.com/assets/157534/15382759/6a110100-1d8d-11e6-97cf-5780e7f66754.png)

**Comment by MoOx** [comment]
![screen shot 2016-05-19 at 06 45 31](https://cloud.githubusercontent.com/assets/157534/15382763/722949f6-1d8d-11e6-9c53-b3f233960ef8.png)

**Comment by MoOx** [comment]
![screen shot 2016-05-19 at 06 45 35](https://cloud.githubusercontent.com/assets/157534/15382767/77e31a0c-1d8d-11e6-9f9c-1f2cddbdc605.png)

**Comment by charlespeters** [comment]
i think your concept here is strong
needs a little bit to make it stronger

what is the main point you're trying to convey with the mark? is it that phenomic is static or that it's simple to setup? 

![](https://cloud.githubusercontent.com/assets/157534/15382767/77e31a0c-1d8d-11e6-9f9c-1f2cddbdc605.png)

**Comment by MoOx** [comment]
I think the key here is the idea of **components**.

IMO the best strength of React is the ease to reuse encapsulated components.

**Comment by cedricdelpoux** [comment]
I like hexagons but I'm not sure it's really representative of Phenomic

**Comment by MoOx** [comment]
Maybe that can help

> Phenomics is an area of biology concerned with the measurement of phenomes—the physical and biochemical traits of organisms—as they change in response to genetic mutation and environmental influences

https://en.wikipedia.org/wiki/Phenomics

> A phenome is the set of all phenotypes expressed by a cell, tissue, organ, organism, or species.

https://en.wikipedia.org/wiki/Phenome

**Comment by MoOx** [comment]
![phenomic-typo](https://cloud.githubusercontent.com/assets/157534/15396468/93025c40-1ddc-11e6-8a21-789973c9617a.png)

**Comment by MoOx** [comment]
Typo hand made by my brother

**Comment by cedricdelpoux** [comment]
Beautiful. I like it !

**Comment by magsout** [comment]
Good job 👍

**Comment by MoOx** [comment]
FYI https://dribbble.com/shots/2728189-Phenomic-Logo
And take a look to the website http://phenomic.io/ (if you have old version, please let me know, I think current service worker implementation sucks a lot).
