### ISSUE TITLE
How to mix CSS modules with legacy CSS? .global.css

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#443]
tl;dr: https://github.com/putaindecode/putaindecode.io/blob/6c830193a4f873790df3d10df9ef3e2e89bbd36b/webpack.config.babel.js#L45-L75

here “styles.css” files are css modules, and files in the “legacy” folder are normal css

**Comment by MoOx** [comment]
More here https://gitter.im/MoOx/phenomic?at=572baa59df1a01ff18fce02f

**Comment by MoOx** [comment]
We can implement .global.css (the opposite of this https://github.com/gatsbyjs/gatsby/pull/295/files)

**Comment by DavidWells** [comment]
👍 this will fix me having to wrap a global css library with `:global { }`

**Comment by sscotth** [comment]
Can the `test: /\.css$/` be changed to avoid the exclude? Something like `/!(global)\.css$/`. I'm not very good with regex...

**Comment by MoOx** [comment]
I don't think it's possible to do that :/
