### ISSUE TITLE
Boilerplate: Rename LayoutContainer to AppContainer

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#444]
Following https://twitter.com/MoOx/status/728210032093990912

**Comment by DavidWells** [comment]
👍 I agree

**Comment by MoOx** [comment]
@revolunet @thangngoc89 any thoughts on this?

**Comment by thangngoc89** [comment]
This mightbe duplicated with react hot loader 3 if we go for that name.

**Comment by MoOx** [comment]
we will use rhl3 appcontainer so people don't have to ;)

**Comment by thangngoc89** [comment]
Ok. If so, that name is fine to me
