### ISSUE TITLE
Recommended approach for integrating Phenomic site with search URL params and results from an external API?

### ISSUE THREAD

**Issue by janicak** [MoOx/phenomic#446]
Greetings from another user of this awesome project!

I'm trying to integrate a Phenomic-generated site with an external API for a "search results" page, and was wondering if you have have any recommendations about including query params in the URL (possibly related to issue #15).

I've so far tried:

Search input onSubmit: `this.context.router.push("search/?"+query)`
+
In routes.js: `<Route path="search/?:query" component={ SearchResults } />` 

--> yields the 404 page to matching URLs

Adding a search.md page (like 404.md with `route: search/?` in the front matter) 

--> responds to "search/?hello" with the 404 page
--> responds to "search/?" with a JSON download of:

`'{"head":{"layout":"SearchResults","route":"search/?","description":"Content here not used, see web_modules/SearchResults\n"},"body":"<p>Content here not used, see <code>web_modules/SearchResults</code></p>\n","rawBody":"Content here not used, see ``web_modules/SearchResults``\n","raw":"---\nlayout: SearchResults\nroute: search/?\n---\nContent here not used, see ``web_modules/SearchResults``\n","__filename":"search.md","__url":"/search/?/","__resourceUrl":"/search/?/index.html","__dataUrl":"/search/?/index.html.81a6916b2722b7ff0e5a4f334a7fe4a9.json"}'`

Any advice would be much appreciated!

**Comment by MoOx** [comment]
I think search query string can't be matched
So try to:

- don't specify the query in the Route path (maybe double check in [react-router docs](https://github.com/reactjs/react-router/blob/master/docs/Glossary.md#routepattern)
- just use context.location.search?

Otherwise you could use `search/:query` but page won't be generated anyway (only .md are generated for now - this sucks but will be improved when handling #15 - it's the next thing on my todo).

**Comment by janicak** [comment]
Thanks @MoOx! To clarify, are you suggesting ...

1. In routes.js:
`<Route path="search" component={ SearchResults } />`

2. curl ".../search?hey"

3. Access "?hey" from context.location.search from within the SearchResults component? I tried to search for docs about context.location, but didn't find anything helpful, and wasn't able to work that out.

If an example comes to mind, that would be awesome, and otherwise, I'll wait to see how #15 is resolved.

**Comment by thangngoc89** [comment]
@janicak did you take a look at react-router's query-params example app ? https://github.com/reactjs/react-router/blob/master/examples/query-params/app.js

**Comment by thangngoc89** [comment]
Btw, I put some code together as an example for you. See it here 

https://github.com/MoOx/phenomic/compare/issue/446?expand=1

`search.md` was added as an placeholder to tell phenomic to generate an search/index.html on static build

**Comment by janicak** [comment]
@thangngoc89 Many thanks for getting back and for the examples!

I have them both working, but am noticing that if you type a query in the URL bar and submit, rather than clicking on the button, the 404 page will flash briefly before returning to the search page. Is there a way to use the loading page instead?

**Comment by janicak** [comment]
Never mind, that only appears to be the case for the dev server - the build version is good

**Comment by thangngoc89** [comment]
@janicak No problems. I'll close this issue for now. Feel free to re-open it.
