### ISSUE TITLE
Consider using babel-node instead of babel to avoid the *.babel.js need in node context

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#450]
File consumed via webpack build don't need this, but since we removed babel-plugin-webpack-loaders, I also removed babel-node.
We should try using it back and check perfs. If same result (or almost, since require hook is already on, to handle those *.babel.js via https://github.com/tkellen/node-interpret) we can add it back.

**Comment by thangngoc89** [comment]
Hum. I confused. The require hook no the same as `babel-node`. Maybe remove the pattern `/\.babel\.js/`  in the require hook ? It should work.

**Comment by MoOx** [comment]
We just got an issue about that with @montogeek. importing a file from webpack config that is written in es6 but don't have .babel.js breaks everything. And it sucks. So module.exports or .babel.js... until we fix this.

**Comment by thangngoc89** [comment]
Again: 

> Hum. I confused. The require hook is the same as babel-node. Maybe remove the pattern /\.babel\.js/ in the require hook ? It should work.

I can handle this if this is the way you want to do it. We don't need `babel-node`

**Comment by MoOx** [comment]
We do need babel-node to allow webpack.config being written in es6+.

**Comment by MoOx** [comment]
Try without an we will see...

**Comment by thangngoc89** [comment]
OK. I'll work on it.
