### ISSUE TITLE
Random 404, even on production, when using client side navigation

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#451]
I just opened https://phenomic.io/ and looked for Usage / Deploy to github and got a 404. This is bad. Maybe related to SW.

**Comment by thangngoc89** [comment]
I saw that too. But only 1 time, I can't reproduce it anymore to find out what causing this problem.

**Comment by MoOx** [comment]
I think the following scenario create this issue:

- I have offline mode with SW
- I open the homepage
- later (after an update of the website), I reopen the homepage: cache is used since our SW say "cache first"
- in this homepage, collection reference to json files are out of date, and if file is not cached already, when I will open a page, I will get a 404 (client side 404).

According to this, we must change our SW policy as we provide json with content hash. Or if people want offline first, we need to remove hashes so url to json (like html url) never changes.

But using by default network first will also "fix" #277

**Comment by thangngoc89** [comment]
Yeah. That might be the scenario here. We clean cached content but doesn't change json files link.

**Comment by MoOx** [comment]
I am thinking about even removing content hash on json. Here is why.

- I load a page "a" (hash "123")
- Another day I load another page "b". The collection in this page indicates that page "a" has changed (hash "456"). Here current cache for "a" is deleted since out of date.
- Another day, I am offline, and goes to page "b" (works, offline cache via sw), then try to access page "a". Hash is "456" and I don't have this page in cache. But I previously had the "123" version. 

It would be nice to have the previous (even if not up to date) page, right?

Like normal url, url for json should not change. Cool uris don't change. Don't you think? Anyway, browser handle cache and when we add an hash, we are trying to do this and cache is a hard problem, we all know that.

You might say that the same can apply for css and js.

**Comment by thangngoc89** [comment]
Adding hashes is mandatory for some cdn to work properly. Removing them is not a good idea. I think that we should find a way to update the current collection in memory so it will reflect the new content changes.

**Comment by MoOx** [comment]
The collection is always up to date, the problem is more that you don't have out of date cached pages as fallback.

**Comment by MoOx** [comment]
Not sure if hashes are mandatory. It's not for html files isn't it?

**Comment by thangngoc89** [comment]
Some cdn caches files forever. So it's mandatory to invalidate those files

**Comment by MoOx** [comment]
So the problem applies for html files as well? More resources about that?

**Comment by thangngoc89** [comment]
I don't know about html files.

More info (I use Amazon Cloudfront as an example): 

> Although you can update existing objects in a CloudFront distribution and use the same object names, we don't recommend it. CloudFront distributes objects to edge locations only when the objects are requested, not when you put new or updated objects in your origin. If you update an existing object in your origin with a newer version that has the same name, an edge location won't get that new version from your origin 

http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ReplacingObjectsSameName.html

**Comment by MoOx** [comment]
> If you update an existing object in your origin with a newer version that has the same name, an edge location won't get that new version from your origin until both of the following occur:
> ...
> **There's an end user request for the object at that edge location.**

So when a user request the item, item will be update on the CDN. Am I not understanding this correctly?

**Comment by thangngoc89** [comment]
Until **both** ...

**Comment by MoOx** [comment]
Fuck. Ok but this solutions leads to problem. I will think about this more.

**Comment by MoOx** [comment]
Ok, here is a simple solution: when deploying, calling the CDN cache cleanup (for example you can do that with a url on most serious hosting services. This should do the trick. Phenomic should not have to handle caching problem.

**Comment by MoOx** [comment]
At least it should not introduce bugs while trying to handle a problem it should not handle :/

**Comment by MoOx** [comment]
Also: cloudflare default cache lifetime is 4 hours. So is it better to have a default behavior that allow 404 or outdated content?

**Comment by MoOx** [comment]
I think github pages default cache lifetime is 10min.

**Comment by thangngoc89** [comment]
@MoOx 

> when deploying, calling the CDN cache cleanup (for example you can do that with a url on most serious hosting services

I don't see this as a good solution for the situation. I hardly do this since all of my web apps use hashing for assets' filenames. As far as I know, hashing is the best solution for long term caching problems and webpack makes this a lot easier. 

> I think github pages default cache lifetime is 10min.


Yes. And you can't change it. 

In conslusion, I would prefer editing the service worker/ appcache rather than removing such a great built-in feature like this.

**Comment by MoOx** [comment]
> In conslusion, I would prefer editing the service worker/ appcache rather than removing such a great built-in feature like this.

The problem is I don't see we can fix that. Or maybe just impose this constraint: network first (to be sure collection is always up to date - and if fallback to cache, then cached page will be with the correct thing).

So closing in favor of #485
