### ISSUE TITLE
Ability to inline CSS in HTML

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#459]
Since only one HTML per user session is used, no big deal.
And it's good for perf (and [gatsby is now supporting this](https://github.com/gatsbyjs/gatsby/issues/145#issuecomment-217691369)).
A flag in config should be easy (enabled by default), and/or support for CSS chunk names (default to all CSS, support for array to filter chunk names with string/regex support).

**Comment by kuzvac** [comment]
Just interested: with css modules, how it can help?

**Comment by thangngoc89** [comment]
@kuzvac I don't think it would help us with anything here.

**Comment by MoOx** [comment]
The idea is just to inline the CSS to avoid an HTTP query. So no relation with how the CSS is handled (sass, css modules...).

**Comment by kuzvac** [comment]
Oh, ok, thank you.

**Comment by DavidWells** [comment]
Checkout https://github.com/addyosmani/critical-path-css-tools might be useful for this issue. 

The idea with critical is that is will inline above the fold CSS for that 'instant' load feel without needing to inline all of the sites CSS in the head tag

**Comment by bloodyowl** [comment]
Going to be fixed with #925 (moving to user land)

**Comment by DominikGuzei** [comment]
@bloodyowl @MoOx how exactly was this solved in latest releases? Would be nice to have some guidance as #925 does not say anything about how to inline css.

**Comment by MoOx** [comment]
Currently all CSS-in-JS examples are extracting inline CSS. Didn't make an example yet for css(?modules)

**Comment by DominikGuzei** [comment]
Nope, no examples for css (+ modules) yet 😉 i just looked over the css-in-js examples, so should i be able to pull the css the same way?

```
<head>
  <style dangerouslySetInnerHTML={{ __html: css }} />
</head>
```

**Comment by MoOx** [comment]
I will push an example ;)
