### ISSUE TITLE
CMS Admin

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#461]
- file tree to browser content/modules
- text editor
- split view: editor on one side, live view on the other

dev start will open this view. An idea is to start dev view in an iframe, and add just a "phenomic toolbar" which allow you to show/hide the split view with the editor. Should not be a lot of work for v0.1 of this admin :)

This will be handy for "writers".

**Comment by kuzvac** [comment]
Recently i found Contentful, looks interesting https://www.contentful.com/blog/2016/06/07/contentful-ruby-static-sites/

**Comment by dab** [comment]
I like the idea. Did you tried [prose.io](http://prose.io/)? It's simple markdown editing tool fot github.

**Comment by thangngoc89** [comment]
Netlify CMS is being re-written in React. This is definitely my choice for a CMS Admin based on Github once it was merged to master branch. 

Check it out https://github.com/netlify/netlify-cms/tree/react-pr

Also there is one thing you have to consider: There is no way to login to Github using Oauth 1 without a server. So you might need a server running somewhere or use Netlify hosting service for login to Github

**Comment by muhajirframe** [comment]
I found prismic.io is pretty cool too. Will you guys write how to use prismic with phenomic too  like this one https://phenomic.io/docs/usage/cms/netlify/ ?

**Comment by MoOx** [comment]
Good idea. I don't have time for this but any help to document existing solutions is appreciated.

**Comment by thangngoc89** [comment]
@muhajirframe Prismic.io and Netlify CMS are different, Netlify CMS hooks up to Github Pages and provide the UI for interacting with content. Prismic.io, on the other hand, manages all content and provide them via the API so you need to pull it before building your static site

**Comment by farfeduc** [comment]
@MoOx I thought of developping a small admin software based on a wysiwyg editor like this : https://github.com/timurtu/markup . The idea is to browse and create new pages/blog posts locally and then push everything on some repository and use the git hooks to automatically deploy the changes :)

This way everyone could use phenomic everyday once it is setup ! What are your thoughts on this ? Would it be a good thing ?

I had this idea because I dislike administration interfaces in CMS, they are security problems and are not easy to use. Another perk with using an external software would be to be able to do "offline editing".

**Comment by thangngoc89** [comment]
@farfeduc hi there, so it's markdown editor right? There are many open source editor avaiable (based on Electron). Why reinventing the wheel?

**Comment by farfeduc** [comment]
@thangngoc89 I agree with you but I don't plan to reinvent the wheel. My goal would be to build upon an existing markdown editor, add some features and make some adjustments : 

The new features would be like : 
1.  simple deployement (automatic git push at the press of a button to publish a new version)
2.  wysiwyg editor only as an option (not everyone is familiar with markdown)
3.  file tree in the sidebar to edit/create pages, blog posts, custom elements...

In the future we could still add more things to optimise the user experience.

The idea behind the number 2 is to make phenomic a more popular solution. If anyone can use it to publish content, only the setup would need some developper skills and such.

**Comment by MoOx** [comment]
User land thing.
