### ISSUE TITLE
Add more visible and accessible ROADMAP

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#462]
A ROADMAP.md?
Any other (better) idea?
A page on the website?

**Comment by thangngoc89** [comment]
We have issues for all of the features. Using milestones will be easier and more accessible

**Comment by MoOx** [comment]
I tried Milestones in the past, and I find that those are not easy to find or easy to maintain.

**Comment by revolunet** [comment]
a bird eye view of the roadmap and future plans would be interesting

**Comment by MoOx** [comment]
Will try to put this quickly.
My priorities atm:

- "plugins" for content-loader (very simple way to adjust content of the consumed files by this loader) #260 
- all routes generated with ability to provides routes like /tag/:tag or /author/:author (data gathered from collection)
- built-in (sort of) search #142 
- more modularity, extensibility, theme? #508 

Anyway, this is "my" roadmap, if contributors want to bring more important stuff for them, I am not against anything :)

**Comment by revolunet** [comment]
thanks  👍

**Comment by MoOx** [comment]
My personal current ROADMAP (this does not means nobody can work on something they want to have)

- better website homepage, round 2 https://github.com/MoOx/phenomic/issues/423
- more visible/up to date roadmap (this issue, how meta?)
- update eslint/stylelint and handle all the current PRs
- normalize public API (deprecate all phenomic/lib/* and prepare monorepo) https://github.com/MoOx/phenomic/issues/433
- Pagination https://github.com/MoOx/phenomic/issues/657
- search input https://github.com/MoOx/phenomic/issues/142
- rename LayoutContainer https://github.com/MoOx/phenomic/issues/444 and rearrange default boilerplate to prepare theme #508

**Comment by MoOx** [comment]
What do you think of this https://github.com/MoOx/phenomic/projects/2 ?

**Comment by montogeek** [comment]
@MoOx I like the use of projects

**Comment by MoOx** [comment]
Projects are hard to maintain, we will review this after v1
