### ISSUE TITLE
onClick not fired for Link elements

### ISSUE THREAD

**Issue by kuzvac** [MoOx/phenomic#469]
I try to use onClick for Link elements, but it will work only inside Header and Footer components.
In other components, and layouts it's doesn't work. :(

**Comment by thangngoc89** [comment]
Maybe it's because phenomic intercepts click event on links :D . See PageContainer component for more information

**Comment by MoOx** [comment]
We should only intercept click in the "dangerousHtml" part. Looks like a bug.

@kuzvac can you provide a bit more code? What `Link` component are you using?

**Comment by kuzvac** [comment]
I use `import { Link } from "phenomic/lib/Link"`
For example, try to use onClick on Link element inside Layouts, or any components except header and footer (inside header and footer onClick works :))

**Comment by MoOx** [comment]
It's a bit weird since props should be sent to the original react-router Link component https://github.com/MoOx/phenomic/blob/2313c7c59a49fc11afcf2c6b2b16f48a3be2fe28/src/Link/index.js#L18

Will take a deeper look later.

**Comment by MoOx** [comment]
Maybe we should not return true or false here https://github.com/MoOx/phenomic/blob/2313c7c59a49fc11afcf2c6b2b16f48a3be2fe28/src/PageContainer/component.js#L141 and just preventDefault() when we use push in browserHistory? @thangngoc89 any thoughts?

**Comment by thangngoc89** [comment]
Yeah. That should work.

**Comment by MoOx** [comment]
After digging, this won't be solved the "easy" way. I am preparing a clean fix, that will involves a very tiny change in the layouts (replace the dangerouslySetInnerHTML by a Phenomic BodyContainer call).

**Comment by MoOx** [comment]
@kuzvac the current way to fix this need a small change in your code. See https://github.com/MoOx/phenomic/blob/master/CHANGELOG.md#0122---2016-05-20
