### ISSUE TITLE
Add preview to showcase links

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#483]
It would be nice to have different sizes of the website like desktop, tablet, mobile. 
https://github.com/sindresorhus/pageres might help. We need to generate those only if not available if the process takes time. And not add those in git to avoid heavy .

**Comment by MoOx** [comment]
Pageres give really shitty screenshots like if there where taken with 5 yo browsers. Flexbox is not correctly supported. Will try something else.

**Comment by DavidWells** [comment]
Nightmare.js uses electron (WebKit) now under the hood for screenshots

It might be a solid option

**Comment by MoOx** [comment]
This is done!
