### ISSUE TITLE
Less verbose output for gh deploy

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#484]
Currently, the recommended method (used for docs) can be verbose if you have a lot of pages, assets etc. We need to tweak this a little bit to avoid the noize. Or maybe wrap the current script in a node module and only show something like "X files published to {branch}".

**Comment by bloodyowl** [comment]
Going to be fixed with #925

**Comment by MoOx** [comment]
What is your plan for this?

**Comment by bloodyowl** [comment]
just use the `gh-pages` module, why bother?

**Comment by thangngoc89** [comment]
@bloodyowl because gh-pages doesn't allow force push to gh-pages branch.

**Comment by bloodyowl** [comment]
hum ok, I'll find something 😊

**Comment by MoOx** [comment]
Yeah gh-pages sucks. The solution I added in the doc is temporary but simple enough.
