### ISSUE TITLE
Change default service worker behavior

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#485]
Currently it's cache first. But it's not relevant for our docs.
A better behavior is network first, cache if offline.
https://github.com/GoogleChrome/sw-toolbox and https://github.com/GoogleChrome/sw-precache can help.

**Comment by thangngoc89** [comment]
:+1: now I understand why you always want network first.

**Comment by MoOx** [comment]
Taggin as bug as this will fix #451

**Comment by MoOx** [comment]
Ok it seems that sw-precache is the easiest solution available and can create a sw with this kind of config

https://github.com/GoogleChrome/sw-precache/blob/963368236e261a4f3ba0c1cd66351b293b8192b3/app-shell-demo/gulpfile.babel.js#L123-L143

Sounds good to you @thangngoc89 ? (Good thing: there is a lot of option https://github.com/GoogleChrome/sw-precache/tree/963368236e261a4f3ba0c1cd66351b293b8192b3#options-parameter)

**Comment by thangngoc89** [comment]
I plan to use sw-precache in the first place but I don't quite remember why did I choose to write it from scratch, maybe some complication in the implementations. If you can implement it, go for it.

**Comment by MoOx** [comment]
I took some times and almost finish the thing with sw-precache that have a "sort" of debug mode (cool for debug: handleFetch option). So I were looking how to enable this in dev, and was thinking only a webpack plugin can help us (since postbuild is run after the static build only). So I looked webpack offline-plugin https://www.npmjs.com/package/offline-plugin and I am seeing everything we need now (this plugin has evolved).
To make things simple, I am considering adding this to the code with simpler flag, because currently the plugin have lot's of option, and I think a simple pattern for resource cached on "install" event + strategy (eg: network first) for non cached during "install" event should be enough for most people. Since we now have already something to inject stuff in people webpack config, we can probably do that and remove code from our core.

What do you think?

**Comment by thangngoc89** [comment]
Awesome, please go ahead and do it
