### ISSUE TITLE
join-uri problem?

### ISSUE THREAD

**Issue by ezralalonde** [MoOx/phenomic#489]
First I'd like to thank you for all the work that has been put into Phenomic. It's a fine piece of software that I'm really enjoying using, and I appreciate all the effort that has been put into making it.

Today I noticed that my "og:url" meta was incorrect, and discovered that the cause a possible fault in `join-uri`: it's removing all instances of "//", including those in schemes, which I believe is an issue.

In my case, I expected `https://some.site`, I get `https:/some.site`. Is this expected? If so, what is the scheme-safe alternative?

    joinUri("https://some.site/", "page")
    >>> https:/some.site/page  // I thought I'd get https://some.site/page

In my local version (only where I set "og:url"), I've replaced this call to `join-uri` with one to `https://www.npmjs.com/package/url-join`, which works as expected.

I originally experienced this issue on 0.12.0, and have since upgraded to 0.12.1, and still see it.

I apologize if this issue is already known, or if this is the expected behaviour of `join-uri`.

I'm happy to submit a pull request swapping calls to the homegrown `join-uri` with the `url-join` package referenced above, if it makes sense, and there's any interest in it.

Thanks again for all your great work!

Cheers,
Ezra.

**Comment by MoOx** [comment]
This is definitely a bug.
Feel free to make a PR to replace internal utility by the one you mentioned, otherwise I will end up doing it.
Just be sure to continue to expose it in phenomic index like  it was before so we can release this change as a patch. Another is planned for #469.

**Comment by ezralalonde** [comment]
Cool. I'll submit a pull request this afternoon.

Thanks in advance for your patience in dealing with me…

Cheers,
Ezra.

**Comment by MoOx** [comment]
No problem. At the stage of this project, every feedback and discussions are welcome :)

**Comment by ezralalonde** [comment]
Turns out the issue, internally, is a little hairy, since there's not curretly a clear distinction between when it is appropriate to treat things as filesystem paths, and when they are URIs. `join-uri` is, as far as I can tell, is being used for both.

I just ended up writing some tests, since I don't want to break any internals.
