### ISSUE TITLE
Regression with 0.12.3: path.posix does not exist in the browser

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#502]
This breaks everything on the client side.

@ezralalonde any idea how to handle this without path.posix? (I don't have much time atm).

Meanwhile, I tagged 0.12.2 as the latest version.

**Comment by thangngoc89** [comment]
Why can't we catch this before in unit tests ? This should be an easy fix. I'm on it

**Comment by MoOx** [comment]
We don't run test in the browser (yet), and I guess webpack provides a "path" polyfill, but the polyfill must be broken.
Thanks for handling this @thangngoc89.

**Comment by ezralalonde** [comment]
Murphy's Law. Oops!

Thanks @thangngoc89 and @MoOx
