### ISSUE TITLE
Add client side integration tests with phantomjs or nightmarejs

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#505]
That would help to prevent major issue like we just got (eg: #502).

**Comment by thangngoc89** [comment]
Do you have any library in mind to do the abstraction ? 

Usually I use karma + mocha for this job. But AVA can't be run in the browser

**Comment by MoOx** [comment]
phantomjs/casperjs but I am not experienced with this kind of testing, so if you have better idea that would be nice.

**Comment by thangngoc89** [comment]
No idea either. With the current setup, it's complicated to use another testing framework like karma. Will do some researches about how to test React component wit Phantomjs and AVA

**Comment by MoOx** [comment]
The idea is not to test react components. The idea is to test the client side navigation. So the final client side runtime. We don't need to care about react in this tests. I think we can just use a phantomjs script to check that this works. We can also use slimerjs to test in both webkit and gecko engine.

**Comment by pytkin** [comment]
How about Enzyme (https://github.com/airbnb/enzyme)?

**Comment by MoOx** [comment]
I think you are not understanding the purpose of the tests I want to add. Currently we already have low level tests on react components (mainly PageContainer) but the error that we go cannot be caught because we are running tests using AVA, so no browser involved). So we can probably add test using enzyme and something like karma/testem with mocha/tape/whatever but I would prefer to add real integration tests: we will test that a click on a certain item on a "page" will actually change the state of the page, with the expected result).
This tests won't care what is used under the hood (zero focus on react) and should even work if we disable js in the headless browser.
