### ISSUE TITLE
Evalutate the possibility to make webpack optional

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#517]
Eg: React + inlines styles (+ inline svg as jsx) can works with just babel.
Babel can works without webpack (require hook). So in theory, this can works without webpack. So will make things WAY FASTER. Like A LOT.
You will say "what about .md?". I will say: the loader is pretty simple and stupid, and we can probably extract the logic outside it, and make a simple watcher that update a single JS. The thing is: what about hot loading? We can take a look to "cold loading" https://github.com/chromakode/isolated-core and see if this can works, since we have a store (even if it will become private).

We can allow both method: with webpack, and without.

Thoughts?

**Comment by DavidWells** [comment]
Interesting idea.

What about webpack 2. Are there any performance gains to be had there?

The power behind webpack is the large ecosystem of plugins.

If phenomic moves to its own "build" will all custom loaders will need to be rewritten?

Both might be good (or confusing to people) :)

**Comment by MoOx** [comment]
No big change with webpack 2.

The api can be: if there is a webpack config file, then build with webpack. If there is none, build without :)
Should not be that confusing.
Like I said, Phenomic custom loader is pretty simple, so no big deal to extract the logic (and keep it as it is) + create a watcher + websocket to send update to files (like webpack dev server does).

**Comment by MoOx** [comment]
The thing I didn't mention is that something like browserify will be at least required.

**Comment by thangngoc89** [comment]
As you talked about browserify, what about roll up?

**Comment by MoOx** [comment]
why not :)

**Comment by bloodyowl** [comment]
Going to be fixed with #925

**Comment by MoOx** [comment]
Fixed in master. v1 might have a browserify example (mostly for fun)
