### ISSUE TITLE
JS file is auto formatted after edit

### ISSUE THREAD

**Issue by demoneaux** [MoOx/phenomic#518]
The JavaScript code is automatically formatted after I edit it, which I did not expect at first. I removed the `eslint --fix` option in package.json for linting, but it still automatically formats my code when I run phenomic. Is there a way to disable that?

**Comment by MoOx** [comment]
Take a look to the eslint-loader configuration in webpack.config file, You will see it over there. `"eslint-loader?fix",`. Just remove `?fix` and it should be good.
Just curious, what is the problem with this autofix behavior?

**Comment by demoneaux** [comment]
Oh, because I don't think it's a good idea for something like this to be
done automatically as people might be confused over why their code suddenly
changes, especially if they're not sure how to disable that. My editor
(VSCode) also doesn't reload files from disk that often so there were
conflicts when saving which I did not expect.

**Comment by kennu** [comment]
I also found this very annoying since I don't agree with most of the formatting defaults, like double-quotes and spaces inside {  }. So I spent lots of time adding exceptions to the default rules.

Also, the auto-formatting completely breaks with this tag:

    <ReactBootstrapSlider
      value={ this.state.width }
      handleChange={ this.changeValue }
      step={ this.state.step }
      max={ this.state.max }
      min={ this.state.min }
      orientation="horizontal"
      disabled={ this.props.logoVariation ? "" : "disabled" } />

(It generates 3 kilobytes of spaces before the closing tag />)

Anyway, I was able to turn it off, thanks for the instructions @MoOx.

**Comment by MoOx** [comment]
I will remove the too strict config by default in a near future. Please track #631.

**Comment by MoOx** [comment]
> (It generates 3 kilobytes of spaces before the closing tag />)

This is probably an eslint issue that should be reported :)

**Comment by MoOx** [comment]
Easy fix: just remove "?fix" in webpack config of the defautl theme.
