### ISSUE TITLE
Service Worker: consider remove the restriction of the origin

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#522]
@thangngoc89 currently you implemented the sw with restriction on the origin `requestURL.origin == location.origin`. What is the reason for that? For example if we have assets loaded from another domain (eg: an image) we won't have it cached.
What can be the issue about caching things not from our domain?!

Looks like a bug or not really useful restriction for me, but maybe you can enlighten me about the reason.

**Comment by thangngoc89** [comment]
My website has stuff like video embed, music that come from others host. I think that should not be cache. Does it sound like a good reason to you ?

**Comment by MoOx** [comment]
Why that should not be in cache, if that can be?

**Comment by thangngoc89** [comment]
Well. You can remove the origin restriction but you must provide a way to customize the service worker template. We can't provide a template that fit for all. About the video, I think it's too large to cache a video.

**Comment by MoOx** [comment]
There is currently no more restriction since we started to use webpack offline-plugin.
