### ISSUE TITLE
Support webpack notification on Windows

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#527]
We are using [webpack-error-notification](https://github.com/vsolovyov/webpack-error-notification) but it doesn't support Windows. I suggest we can use [webpack-notifier](https://www.npmjs.com/package/webpack-notifier) instead for Windows support. (I'm using Windows on daily basic now)

**Comment by MoOx** [comment]
Sure thing. I am using this one too this days.

**Comment by thangngoc89** [comment]
Alright. I'll send a PR for this
