### ISSUE TITLE
Change the default structure of the project

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#529]
`web_modules` might be confusing.
Something like

```
/
  /app?
  /layouts
  /modules? /components?
  [/themes?](#508)
```

Need to think more tho.

**Comment by stevenkroon** [comment]
I like "components" over "modules"

**Comment by revolunet** [comment]
I like "components" over "web_modules" too

**Comment by thangngoc89** [comment]
:+1:  for componens.

**Comment by MoOx** [comment]
Do you think a folder like "layouts" is necessary? Since they are just components after all. Not sure if this will help or confuse people.

**Comment by MoOx** [comment]
FYI you can already change this structure, since everything is explicit from the `scripts/phenomic.*.js`. Nothing is implicit (for now) so you have access to all references and so you can change all paths.

**Comment by revolunet** [comment]
indeed, putting layouts in components makes sense imho.

**Comment by thangngoc89** [comment]
I think keeping layouts as a seperated folder makes more sense. It's like containers vs components.  But you can put it where you like it. (Phenomic is pretty flexible, and unopinionated)

**Comment by MoOx** [comment]
I will probably introduce this

```
content/
src/
  /layouts (should we parse this automatically? need to think about this...)
  /components
  routes.js (optional? should this one have defaults too?)
  app.js (optional, should have a default)
scripts/ (optional, should have a default)
  phenomic.*.js 
webpack.config.js
package.json
```

Ref https://github.com/MoOx/phenomic/issues/508#issuecomment-238462889

**Comment by DavidWells** [comment]
@MoOx looks good to me. Its pretty much exactly what I did 2 days ago =)

![image](https://cloud.githubusercontent.com/assets/532272/17570952/4c7b7f32-5f03-11e6-8773-8ea57f6f0c16.png)

**Comment by revolunet** [comment]
yes, having dedicated layouts folder is better if you want to support auto-discovery so we wont have to declare them in route.js

**Comment by MoOx** [comment]
You can check the new tree here https://github.com/MoOx/phenomic/tree/master/themes/phenomic-theme-base
Feedbacks welcome :)
