### ISSUE TITLE
Disable browser reporter in production

### ISSUE THREAD

**Issue by stevenkroon** [MoOx/phenomic#530]
It would be great if the production builds don't show the browser reporter messages

**Comment by MoOx** [comment]
You can already replace the default boilerplate postcss section by this

```js
  postcss: () => [
      require("stylelint")(),
      require("postcss-cssnext")({ browsers: "last 2 versions" }),
      ...config.production ? [
        require("postcss-browser-reporter")(),
      ] : [],
      require("postcss-reporter")(),
    ],
```

This won't push error in the CSS, just in the console during the build step.
We might thing for a cleaner code block, but I will definitely push this in the default boilerplate!

**Comment by MoOx** [comment]
This has been done in the current default boilerplate.
