### ISSUE TITLE
Does Google Analytics in docs capture hits correctly?

### ISSUE THREAD

**Issue by ezralalonde** [MoOx/phenomic#531]
Hi again,

Thanks again for all of your work.

In recently trying to configure Google Analytics to work with Phenomic for myself, and using the doc site as an example. In the "Realtime Overview" (leftmost circle) I noticed GA's "Active Page" (middle circle in screenshot) always appeared to be the last page that was "hard-loaded" (e.g. by hitting enter on the URL bar), even though ajax-y "soft-loads" ("virtual pageviews", e.g. by clicking a <Link>) were still showing up in the "per-second totals" (right circle).

![screenshot](https://cloud.githubusercontent.com/assets/87369/16100560/7342ea64-331c-11e6-86bb-c3d2483c0045.png)

Is anyone else observing this behaviour? Is it what is expected?

Lines 41–43 of phenomic/docs/web_modules/GoogleAnalyticsTracker/index.js 

      if (isProduction) {
        ga("send", "pageview")
      }

Based on [Google's Advice for using Analytics with SPAs](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications#tracking_virtual_pageviews), setting the page before sending seems to show the correct "Active Page", even after soft-loading.

      if (isProduction) {
        ga('set', 'page', window.location.pathname);
        ga("send", "pageview")
      }

Does this seem reasonable? It appears to work for me.

It's not a big deal (or hard to fix), I just thought I'd let you know. Thanks again for everything.

Cheers,
Ezra.

**Comment by MoOx** [comment]
This is probably a huge bug. Thanks for letting me know. I will try your recommendation and see if stats are changing.

**Comment by MoOx** [comment]
FYI I think it's best to go to Behavior > Site Content > All pages.

![screen shot 2016-06-16 at 06 27 09](https://cloud.githubusercontent.com/assets/157534/16105515/6aa230c6-338b-11e6-938a-e8adad02e476.png)

So not sure if the line you added will change something. A better option might be to rely on #384 .

**Comment by thangngoc89** [comment]
@MoOx Behavior > Site Content > All pages doesn't provide accurate information for this bug. As @ezralalonde said, if this is true, Google Analytics only record the last full page reload.

**Comment by thangngoc89** [comment]
@ezralalonde I did some test on my website and I can't reproduce this. (probably because I'm using a different GA wrapper) 

My component https://github.com/thangngoc89/blog/blob/2108b8d514ce8655c8c1ef11180311c77ce39ab5/web_modules/components/GATracker/GATracker.js

**Comment by MoOx** [comment]
I think I made some tests in the past but I am not sure.
We can probably create an hidden page and access it via another one to see using real time tracking. That might be a way to ensure there is a bug. Did you do that @ezralalonde ?

**Comment by ezralalonde** [comment]
I did the tracking on the main page, since the site I was testing has ~0 traffic. In this sense it is "hidden".

My test method was manual variations on the following:

1) Find a page XYZ with 0 active users, 
2) Visit XYZ using a hard-loading method, such as typing it in the browser bar,
3) Observe XYZ show up in "Active Pages"  with 1 active user, and the per-second visit registered,
4) Navigate away to ABC using a soft-loading method, such as clicking a <Link>,
5) Observe that XYZ still has 1 active user, and the per-second visit registered. ABC's value is unchanged

I agree this is easier on a site with 0–1 users than hundreds. I wasn't able to "fake" this by manipulating the URI by appending `#` or `?` strings.

[Checking real-time reports](https://support.google.com/analytics/answer/1008083?hl=en) is the suggested way to verify a GA installation. I believe these reports are the simplest and most reliable way to track the behaviour, especially if you're dealing with an extremely low-traffic site, as I am.

Like I said, I observed the following behaviour originally:

1) All page views would register (ie. all views would show up in per-second views),
2) "Virtual" Page views would never update the "Active Pages" metric.
3) Reloading the page would always update the "Active Pages" metric.

After adding the one "pathname" line, I noticed that "Virtual" Page views would accurately update the "Active Pages" metric.

For @thangngoc89, your site uses a different GA library (`react-ga` instead of `react-google-analytics`) and it does appear to supply the URI to the library for logging.

I think that my test site is substantially similar enough to the Phenomic docs site, though they obviously differ, that it may have existed in both. Still, the bug may be particular to my implementation, or some other factor, since they are not identical.

It's not a critical, show-stopping, life-changing, stop-the-presses issue; I just thought I'd share what I noticed. I only noticed the potential issue because I learn by browsing source of the sites in the showcase, which you have both graciously shared with me.

Thanks again!

**Comment by thangngoc89** [comment]
@ezralalonde thanks for the detail information. It's great to read your comment. @MoOx patched this as you suggested https://github.com/MoOx/phenomic/commit/5e4d4dd15e510bb77e05d67090612804b271e326

**Comment by MoOx** [comment]
FYI, I am not sure this change really changed something.
See below the number of pageview for last mont (I integrated the change the 16 june).

![screen shot 2016-07-02 at 05 53 15](https://cloud.githubusercontent.com/assets/157534/16538098/4bd5f0d4-4019-11e6-9806-416444edc997.png)

**Comment by ezralalonde** [comment]
The total number of pageviews was always being recorded correctly. Certain pages were being counted twice, while others were not being counted at all.

As you know, with isomorphic/universal rendering in React, there are two types of pageviews:

1) Pages viewed by directly loading an HTML file
2) Pages viewed by loading and rendering a JSON file

The second type is what was not being recorded correctly in my experience. I was able to test it easily because it was on a low-traffic site, so I could easily correlate the Active Pages/Active Users with actual pageviews. I agree that it would be very hard to tease this data or gauge the effect from actual usage statistics on a website with multiple concurrent users, but that it's very easy when you have perfect knowledge of all visits.

Imagine the following actions:

1) User uses address bar to navigate to example.org/
2) User clicks link to `/able`.
3) User refreshes current page, `/able`.
4) User clicks link to `/bravo`.

With the bug present, this would register two pageviews for `/` (steps 1 & 2) and two for `/able` (3 & 4). With the bug fixed, it would register one for `/` (1), two for `/able` (2 & 3), and one for `/bravo` (4). You can verify this by inspecting "Active Pages" under Google Analytics with and without the bug, and comparing it to the page that is actually open in the browser.

If you are really not sure, I'd recommend putting together a private site with a new tracking ID, and testing the effect in isolation. It's going to be *very* hard to make sense of a general effect using measurement of real traffic patterns.

I hope that makes sense.

**Comment by MoOx** [comment]
Thanks again for the explanation. I will trust you on this.
