### ISSUE TITLE
filter wildcards

### ISSUE THREAD

**Issue by caranicas** [MoOx/phenomic#542]
is there any way to add a wildcard `*` to the filters in `enhanceCollection`? , I gave it a go, but it didn't work the way I thought it would. I want to keep my markdown files and layouts a bit more modular and have separate files for  `Employee-Bio`, and `Employee-JobDescription` . 

I'd like to be able to do something like this.

```
const allEmployeeData = enhanceCollection(this.context.collection, {
      filter: { layout: 'Employee-*' }
})
```

**Comment by MoOx** [comment]
Better than wildcard, I think regex are supported.

You can try this.

```js
const allEmployeeData = enhanceCollection(this.context.collection, {
      filter: { layout: /^Employee-/ }
})
```

**Comment by MoOx** [comment]
v1 have a new API.
