### ISSUE TITLE
Render JSX in Post markdown Files

### ISSUE THREAD

**Issue by KraigWalker** [MoOx/phenomic#543]
I was wondering if anyone had luck rendering Markdown to JSX?

My current setup attempts to use [remark-react](https://github.com/mapbox/remark-react) instead of remark-html but I've hit a wall. I'm not quite sure I've understood it's use to be honest.

having a way of doing this would be ideal, as it would allow for phenomic to render components (such as react-d3 charts, etc.) out in a post without having to create a whole new layout. It'd also make the task of supporting specs like [Google AMP](https://www.ampproject.org/) and [Facebook Instant Articles](https://developers.facebook.com/docs/instant-articles) a bit easier by using alternative React Components instead of default elements to make `<img>` tags valid `<amp-img>` components, for example.

     renderer: (text) => {
					remark
					.use(remarkSlug.default)
					.use(remarkAutolinkHeadings.default, {
						attributes: {
							class: "phenomic-HeadingAnchor",
						},
						template: "#",
					})
					.use(remarkReact, { entities: "escape" })
					.use(remarkHighlight.default)

					// render
					.process(text, {
						commonmark: true,
					})
				},

**Comment by MoOx** [comment]
For now only HTML is supported since we support text to html only (maybe due to the legacy json restriction). But we plan to allow transformation as object (results of jsx) too. Please track #434.
Any kind of help is welcome.

**Comment by thangngoc89** [comment]
You can define your renderer as plain text like this

```js
(render) => render
```

and import remark and remark-react within your client code to use remark-react's features

**Comment by iamvlado** [comment]
@KraigWalker Try [this](http://cmichel.io/how-to-use-react-in-markdown/). It's really simple working example.
