### ISSUE TITLE
While running as root .gz files gets created on working directory

### ISSUE THREAD

**Issue by drFabio** [MoOx/phenomic#545]
When running phenomic as root a bunch of .gz files intended for cache get's created on the working directory.

This is caused by  the os.tmpdir() and process.env.TMPDIR pointing to the working dir and not /tmp/ as expected. This is similar to [this webpack issue](https://github.com/webpack/webpack/issues/2223) and caused by the same reasons

On this [issue](https://github.com/npm/npm/issues/4531) from npm it says it is related to [this line on npm](https://github.com/npm/npm/blob/master/lib/utils/lifecycle.js#L79) and relates the switch to [this npm configuration](https://docs.npmjs.com/misc/config#unsafe-perm).

So running trhough npm as root changes the tmp dir.

So for example this script:

``` javascritpt
console.log('Env: '+process.env.TMPDIR);
console.log('By os:'+require('os').tmpdir());
```

As root (either locally or on container):

> Env: CURRENT DIR
> By os: CURRENT DIR

On container directly as root (node script.js):

> Env: undefined
>  By os:/tmp

running locally directly (non root):

> Env: undefined
>  By os:/tmp

 locally trhough npm gives (non root):

> Env: /tmp
> By os:/tmp

I realize this is the expected behaviour by NPM folks but is a pretty specific caveat  and one that will always happen on docker.

I suggest either asking for the tmp directory on the setup script and configuring unsafe-perm or the env var  , or put a warning on the script before start if tmp dir is equal to working dir  , or even a simple warning somewhere on the site to people be aware of the caveat.

**Comment by MoOx** [comment]
The thing is: we don't use tmpdir() or TMPDIR in our codebase. So not sure if we should handle this.

Asking for something during the setup might seems overkill (for most use case).
Anyway, if nobody is open to handle that (pretty sure npm won't be open for a change, nor webpack) we might do something like a warning (at least).

Can you check if disabling babel cacheDirectory fix this problem? It seems it might be the culprit (in this case we can specify a specific folder  - so fix this issue ourself).

**Comment by drFabio** [comment]
Setting cache_directory on webpack,config.babel.js  did solve the problem.
Probably changing the cache directory for webpack to /tmp would solve it as well.

**Comment by thangngoc89** [comment]
I sent a PR to create-react-app to fix this issue here https://github.com/facebookincubator/create-react-app/pull/620

Poke @MoOx should I do the same here?

**Comment by thangngoc89** [comment]
I have a local wip but it uses Jest. 

Waiting on #744

**Comment by MoOx** [comment]
babel-loader now handle this.
