### ISSUE TITLE
error on web page 'number-zero-length-no-unit' deprecated

### ISSUE THREAD

**Issue by wilsonmar** [MoOx/phenomic#557]
After downloading and setup as described in https://wilsonmar.github.io/static-websites/
I get this message at the top of the screen:

'number-zero-length-no-unit' has been deprecated, and will be removed in '7.0'. Use 'length-zero-no-unit' instead.

<img width="1132" alt="screen shot 2016-07-07 at 8 18 06 am" src="https://cloud.githubusercontent.com/assets/300046/16664984/cc7ee37e-443f-11e6-9416-68e3ce60b7b0.png">

**Comment by MoOx** [comment]
Sorry for this. You can safely update stylelint-config-standard to "^10.0.0", this will fix this issue. Btw, fix stylelint version to "^6.8.0"

```console
$ npm install --save-dev stylelint@^6.8.0 stylelint-config-standard@^10.0.0
```

This should fix your issue. The fix will be pushed (already in master, will be release in the next few days)  but will only affect new projects.

**Comment by wilsonmar** [comment]
Would changing version numbers in the package.json file do the same as the parameters?

**Comment by wilsonmar** [comment]
This fixed the problem. Thanks.
