### ISSUE TITLE
More UI templates and features

### ISSUE THREAD

**Issue by wilsonmar** [MoOx/phenomic#558]
I think it would help the popularity of this endeavor a lot if more nice templates are available with additional features such as search, social media, email forms, etc. such as shown on http://jekyll.tips/plugins/

Or did I miss them for this framework somewhere?

**Comment by DavidWells** [comment]
👍 for plugins!

I'm interested in a standardize templating setup too. Perhaps modelled vaguely after how WordPress templates (at least file structure wise) does it

**Comment by wilsonmar** [comment]
Is there a converter that takes a Jekyll site (such as http://jekyll.tips/templates) and converts the files to phonemic? (with pre-arrangement and attribution etc.).

Even better if it does that and adds them to a website of themes (such as http://jekyll.tips/ provides)

**Comment by thangngoc89** [comment]
@wilsonmar I'm not an Jekyll expert but Phenomic's markdown file structure was inspired by Jekyll, so it work out of the box with Jekyll's markdown files.

**Comment by thangngoc89** [comment]
There is an open discussion about template here: https://github.com/MoOx/phenomic/issues/508

**Comment by MoOx** [comment]
I am getting a 404 on http://jekyll.tips/plugins/.
What you idea in mind? Cause with the component approach, note sure lot's of stuff like you can find for wordpress or jekyll make sense.

Ok for the "standardized" template idea. We can discuss about that in #508.

For the "jekyll to phenomic" thing, most simple md files should work out of the box, but it can be more complexe to handle. Nothing has been made from what I am aware of.

**Comment by bloodyowl** [comment]
Going to be fixed with #925

**Comment by MoOx** [comment]
Might review this later.
