### ISSUE TITLE
Boilerplate: Make date structure obvious

### ISSUE THREAD

**Issue by bnb** [MoOx/phenomic#559]
Not sure if it's yyyy/mm/dd or yyyy/dd/mm structure. In "Hello World!" would it be possible to change whichever one is `dd` to `28` (since there are only 28 days, typically, in Feb)? Or, more ideally, March 31st?

**Comment by MoOx** [comment]
It's yyyy-dd-mm. Will update according to your comment.

**Comment by bnb** [comment]
@MoOx thanks!
