### ISSUE TITLE
Error on Fresh Install

### ISSUE THREAD

**Issue by bnb** [MoOx/phenomic#560]
Here's the error I got from stylelint when I first opened Phenomic:

![Phenomic Stylelint error on first run](https://cloud.githubusercontent.com/assets/502396/16699591/0d548046-4523-11e6-91c6-894335bbd4fb.png)

**Comment by MoOx** [comment]
It has been fixed on master, will cut a release in the next few days (this will only affect new setup tho)..
Please take a look at this comment https://github.com/MoOx/phenomic/issues/557#issuecomment-231179966 where you will find instructions to fix this issue.
Sorry for this.

**Comment by MoOx** [comment]
Should be ok now.
