### ISSUE TITLE
Pages transitions

### ISSUE THREAD

**Issue by xuopled** [MoOx/phenomic#587]
It could be great to handle pages transitions using css transitions to reproduce this kind of transitions : http://tympanus.net/Development/PageTransitions/

I used react-router to handle the routing transitions but there is maybe a better way : https://gist.github.com/cedricdelpoux/4286de789e7b0138708a3be4581963f2

What do you think ?

**Comment by MoOx** [comment]
Will take a look when I got some times :)

**Comment by cedricdelpoux** [comment]
Thank you for your help :)

**Comment by DavidWells** [comment]
👍 looks cool!

**Comment by MoOx** [comment]
I got an awesome idea:

- stop unmounting current Layout, instead keep it and just send new props (people will be able push an optimistic update with title, meta, with just the body to update, when data are received)
- handle render of the Loading differently (have to think about this a bit more)

This should allow people to do whatever they want (eg: use ReactCSSTransitionGroup) in they layout when props change.

**Comment by cedricdelpoux** [comment]
Awesome solution. thank you for your help

**Comment by MoOx** [comment]
I guess what we have in 0.18.0 is enough for now. We can improve and revisit later.
