### ISSUE TITLE
"eject" command, like create-react-app

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#596]
My idea: better (and simpler) defaults with no boilerplate (just components) + an "eject" command to get all the boilerplate in your project so you have full control.
Thoughts?

**Comment by thangngoc89** [comment]
I'm all in. It's a pretty nice feature.

**Comment by thangngoc89** [comment]
On a second thought, this is what I want to build a phenomic webiste

- Install it `npm install -D phenomic`
- Init `phenomic init`

This will create a content folder with some md files and nothing else

- Everything will be keep inside phenomic repo 
- We will provide a default theme and (and community themes)
- To build a site : 

  - Default theme: `phenomic build` 
  - Community theme : `phenomic build --theme=<theme-name>`
  - Use a custom theme: `phenomic build --theme=<path-to-theme>` or we can enforce that if a theme folder was found, use that folder.

This is what I'm imaging about Phenomic, super simple and easy for even non-technical user.

**Comment by MoOx** [comment]
theme could be a key in the config too. But yeah that's how I see the thing too ;)

**Comment by thangngoc89** [comment]
I thunk I dont need to talk about that since every cli args has a config counterpart

**Comment by MoOx** [comment]
Haha true. I like this project so much.

**Comment by MoOx** [comment]
Closing in favor of #783
