### ISSUE TITLE
Explode as a monorepo

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#598]
This might require a lot of work but maybe splitting into something like this

phenomic-core
phenomic-content-loader
phenomic-content-loader-plugin-*
phenomic-content-loader-preset-\* (bundle of plugins, for example phenomic-content-loader-preset-markdown)
phenomic-static-rendering

Just an idea :)

**Comment by thangngoc89** [comment]
What is `core` and `static-rendering` ? Still, this is a pretty good ideas and a good chance to clean up and organize the codebase. I hate it when the `src` folder has too many subfolders

**Comment by MoOx** [comment]
core will be, well the core part (not sure what this will be yet) and static-rendering will be code for the static html generation part. But maybe this should be in the core as well.

spoiler: with monorepo, we might have even more (sub)folders ;)

**Comment by MoOx** [comment]
To check: 
- http://lernajs.io/ (I saw so bad feedback: slow https://github.com/pouchdb/pouchdb/issues/5545)
- https://formidable.com/open-source/builder/ (maybe a bit weird)
- https://github.com/northbrookjs/northbrook (inspired by cyclejs monorepo)
- some infos
  - https://github.com/pouchdb/pouchdb/pull/5178
  - https://github.com/boennemann/alle#readme

**Comment by thangngoc89** [comment]
Biggest trade: no greenkeeper (We are suffering this already with docs and boilerplate)

About the structure, I think we should keep the core of Phenomic in one piece at first. only break plugins section.

**Comment by MoOx** [comment]
There is solution for greekeeper + greenkeeper plans to handle monorepo as well.

**Comment by MoOx** [comment]
Might be interesting for consuming git repo https://github.com/facebook/jest/blob/2fcae4df8256ed00e3b995cf7ea2957b8766e7a5/scripts/postinstall.js

**Comment by MoOx** [comment]
@thangngoc89 shared this https://github.com/knitjs/knit looks promising

**Comment by bloodyowl** [comment]
Going to be fixed with #925
