### ISSUE TITLE
Add a loader plugin to handle a library of picture

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#610]
I made seaade2016.vn a while ago with phenomic (statinamic actually). It's a website for a conferrence. At the time, the client request is pretty clear to me, it's definitely a static site with a few markdown files. But now, the client is willing to pay extra for adding new functions to the site. 1 particular request is adding a photo library which is kinda hard to fullfill. Here is the client's request:
- a space on the site to display photos
- photos can be display by event (for ex: opening ceremony, presetation, ...) or by timeline.
- should have a user-friendly interface so that photographer can upload photos directly. Github isn't a option here.

So you guys have any suggestions to fullfill these requirements? do you think that using a static site generator is suitable to fullfilling this?

**Comment by MoOx** [comment]
Make a GUI that commit photo to github?
This reminds me this project https://github.com/eduardoboucas/staticman

**Comment by MoOx** [comment]
Upload photo create empty md with just a front-matter with path to the asset. Then you can do anything you want using the collection.

**Comment by thangngoc89** [comment]
Thanks. I almost forgot about this. I think your solution 1 file - 1 photo is great. Will try it

**Comment by MoOx** [comment]
I just got a fucking great idea: with the new plugin system, you should be able to use phenomic-loader on .jpg file, and use custom plugins to generate head/body fields according to jpg name and metadata (eg: exif). That can be sick!

**Comment by thangngoc89** [comment]
You are briliant!!! :100: 

I might need to put jpg files somewhere else and pull them on build, storing them in git is not ideal

**Comment by MoOx** [comment]
You can use a specific phenomic-loader “context" option for this specific loader section to catch files from anywhere, in theory. But need to be tested because I am not sure how we could handle the result. Maybe you will need another plugin to do an effective copy, cause current default loader consume the md and serve data in json, but for jpg you can't just do that haha.

**Comment by thangngoc89** [comment]
Yeah. Valid point. We'll see what I will ended up with.

**Comment by thangngoc89** [comment]
I didn't use Phenomic for this job. I wrote a simple server and embed the result to the website.

**Comment by MoOx** [comment]
I think with the current state of the project, this will be very easy. I might handle this later via a loader plugin since my wife website use a lot of photos.

**Comment by thangngoc89** [comment]
@MoOx nice!

**Comment by MoOx** [comment]
Will be more easy with v1 with plugins.
