### ISSUE TITLE
Use webpack-dashboard for a beautiful webpack output

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#615]
![](https://camo.githubusercontent.com/cbbf3964c3bb6369f27a888e5987e5a88e115b89/687474703a2f2f692e696d6775722e636f6d2f354257613168422e706e67)

https://github.com/FormidableLabs/webpack-dashboard

Implementing this to phenomic is just 1 line, super easy since we have everything in place.

We can implement this behind a flag for experiment first and then make it the default after that. What do you think @MoOx ?

**Comment by MoOx** [comment]
Yeah I already thought about that. Can be nice.

**Comment by thangngoc89** [comment]
Closing this. Webpack-dashboard expect it's the only thing that write to the stout. If we console.log somewhere, whether the message will be omitted or webpack dashboard's layout is broken. Oh, I forgot, this doesn't work on Windows
