### ISSUE TITLE
Add some CSS variables in the default theme

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#617]
As an example, via http://cssnext.io/usage/#features (simplest way) or via CSS modules `@value` (but I don't like this totally non standard syntax).

Following @revolunet's request on the chat.

**Comment by revolunet** [comment]
How should this be implemented  ? a separate `cssVariables.js` file required by webpack/postcss-cssnext ? 
Also, where should we store shared "mixins" for composes ?

**Comment by MoOx** [comment]
Currently yeah you could pass options here https://github.com/MoOx/phenomic/blob/2b44e19bfa095d2a4bb512c122dbb24380a83ef1/boilerplate/webpack.config.babel.js#L150, imported from another file works.

For mixins, I think if you need more than a simple value, you should probably write a UI component ;)
