### ISSUE TITLE
Generating a sitemap

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#621]
How would you suggest handling XML sitemap generation?

There seem to be a lot of NPM packages for this https://www.npmjs.com/search?q=sitemap+generator 

Does anyone have a recommended way of doing this?

**Comment by thangngoc89** [comment]
You have all the information you need in collection to create a sitemap. Just need to print it out properly. Or you can just use the RSS feed generating feature. With Google Webmaster tool, you can submit a RSS feed for sitemap.

**Comment by MoOx** [comment]
I guess we can add this like for the rss feed, and later extract this as a package when handling #598.
This would have to be added here https://github.com/MoOx/phenomic/blob/2b44e19bfa095d2a4bb512c122dbb24380a83ef1/src/phenomic-loader/index.js#L86

**Comment by MoOx** [comment]
@thangngoc89 having informations is one thing, being able to do it without pain is another, we need to provide options to make this super easy. It's very a basic requirement.

**Comment by thangngoc89** [comment]
I suggest extracting the rss and sitemap logic from the loader and put it into the plugin.

**Comment by MoOx** [comment]
baby steps ;) For now it's easy to add this here.

**Comment by theduke** [comment]
So, how do I go about adding a sitemap?

The problem I see is:

```javascript
<Route component={ LayoutContainer }>
    <Route path="/sitemap.xml" component={SiteMap} />
    <Route path="*" component={ PageContainer } />
</Route>
```

So how do I define an additional "/sitemap.xml" route that does not use LayoutContainer?

**Comment by MoOx** [comment]
In theory, this should work (for any html url), but the problem is that pages generated are wrapped into an Html component.
My suggestion is to use something else and not rely on phenomic (eg: https://www.npmjs.com/package/simple-sitemap)

**Comment by theduke** [comment]
But I need the sitemap to be available at /sitemap.xml, not just submit it to google.

I guess I could write a script to generate it and copy it to the build folder on deploy though.

**Comment by MoOx** [comment]
The package I mentionned allow to write to disk, so yeah you should call it after the build (eg: npm "postbuild" hook) and this should do the trick.

**Comment by thangngoc89** [comment]
This should be easy now, but still require some works.

You can take a look at [Loader Feed Webpack Plugin](https://github.com/MoOx/phenomic/blob/master/src/loader-feed-webpack-plugin/index.js) and make a similiar Plugin (Loader Sitemap Webpack Plugin)

Use [sitemap](https://www.npmjs.com/package/sitemap) to generate `sitemap.xml` from list of urls.

**Comment by DavidWells** [comment]
Wrote this custom script to handle this for me in the meantime:

Note: The `node-dir` npm package is super handy for dealing with markdown manipulation as well. Just an FYI (see: https://github.com/serverless/site/blob/master/scripts/blog/update-blog-yaml.js )

```js
// generate script
var dir = require('node-dir')
var sm = require('sitemap')
var path = require('path')
var distPath = path.join(__dirname, '..', 'dist') // path to built dist

function getAllUrls (filePath, callBack) {
  dir.readFiles(filePath, {
    match: /.html$/,
    //exclude: /^\./
  }, function (err, content, filename, next) {
    if (err) throw err
    next()
  },
    function (err, files, test) {
      if (err) {
        callBack(err)
      }
      var urls = files.map(function(file, i) {
          return {
            url: file.split('dist')[1].replace('index.html', ''),
          }
      })
      console.log(urls)
      callBack && callBack(null, urls)
    }
  )
}

getAllUrls(distPath, function(err, urls) {
  if (err) {
    console.log(err)
    return false
  }
  var options = {
    hostname: 'http://serverless.com',
    cacheTime: 600000,  // 600 sec cache period
    urls: urls
  }
  // Creates a sitemap object given the input configuration with URLs
  var sitemap = sm.createSitemap(options);
  // Generates XML with a callback function
  sitemap.toXML( function(err, xml){ if (!err){ console.log(xml) } });
  // Gives you a string containing the XML data
  var xml = sitemap.toString();
  // write sitemap to file
  console.log('sitemap', xml)
})
```

**Comment by xuopled** [comment]
@DavidWells when do you launch your script ? I did not see any `npm` postbuild hook related to sitemap for your site

**Comment by xuopled** [comment]
I just open a PR about this #907

**Comment by DavidWells** [comment]
The script is here https://github.com/serverless/site/blob/master/scripts/sitemap.js

I actually disabled it because right when I generated it in postbuild we started seeing a huge google analytics drop off.

I can't confirm it was the site map but I'm scared to toggle it back on =P

After about 2-3 weeks of the sote page being toggled off, the site traffic was back to normal.

Very very strange and I still can't explain why this happen (or if it was directly related to adding the site map.xml)

**Comment by xuopled** [comment]
Ok, thank you for your feedback. I saw the script but I did not see how the script is automatically run. But I understand now

**Comment by DavidWells** [comment]
@xuopled no problem.

I'd be curious if you see a similar thing when you toggle on a sitemap.
