### ISSUE TITLE
Incremental Cache via Service Worker

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#629]
Just wanted to leave this here as an idea/discussion.

This looks pretty interesting: "...an incremental cache for the web. It only downloads the delta between the old file in cache and the new file." – https://github.com/gmetais/sw-delta

https://github.com/gmetais/sw-delta#how-does-it-work 

> Asked url:          http://domain.com/js/main-1.2.0.js
> Version in cache:   1.1.1
> Updated url:        http://domain.com/js/main-1.2.0.js?cached=1.1.1

So the idea might be that `phenomic build` doesn't remove the previous `/phenomic.browser.v1234.js` from the build directory and the service worker can do its thing? 

**Why?**: return visitors would (potentially) only need to download the smaller diffed `http://domain.com/js/main-1.2.0.js?cached=1.1.1` file if the site has been updated since there last visit and not the entire new bundle

**Comment by thangngoc89** [comment]
Build should be stateless. IMHO, a stateful build will increase the complexity. Will think more about this

**Comment by MoOx** [comment]
Also, this require a server. Which kind of broke the "easy static" idea (deploy a folder anywhere).
Anyway, current default worker use a network first approach. And SW run in the background. So not sure we should add this into Phenomic now. Might be a good candidate for a plugin tho.

**Comment by DavidWells** [comment]
It does add complexity :)

I don't think it needs a server. The script versions + diffs can be built statically and deployed up to CDN

**Comment by MoOx** [comment]
The "how it works" explains this needs a server side part https://github.com/gmetais/sw-delta#how-does-it-work
If you want to handle this statically, this means your static build will need to compute diff for all previous versions of all files, which can quickly become a fucking lot very quickly.

**Comment by DavidWells** [comment]
Hahaha, a fucking lot indeed!

**Comment by MoOx** [comment]
Closing due the complexity. Might revisit later if relevant :)
