### ISSUE TITLE
Plugins, round 2

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#630]
In current master (will be released soon) we have ability to use plugins for phenomic-loader. Let's call that "phenomic loader plugins".
We will end up having theme (#508), so having a global plugin system seems like a good next step.

Here is my idea about what a plugin should be able to do:
- adjust config
- adjust webpack config (add loaders, plugins etc)
- register phenomic loader plugins

Please share your ideas!

**Comment by thangngoc89** [comment]
The plugin API needs more love. It should not be a 1-1 mapper. A file can produce multiple file after runnig through the plugin system. Or it can be removed as well.

**Comment by thangngoc89** [comment]
Did you know about  spike? 

https://github.com/static-dev/spike-core/blob/master/readme.md

It's another SSG that uses Webpack as its compiler. And it has a very flexible plugin API. I'm investigating it

**Comment by bloodyowl** [comment]
Going to be fixed with #925
