### ISSUE TITLE
Add option to choose your linting eslint shareable config on setup

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#631]
eslint-config-i-am-meticulous is nice, but too probably opininated (according to user feedback). We should ask what user want, and offer another by default (standard? airbnb?...)
We should ensure that eslint autofix can cover some common config so when we switch the config and run autofix the theme does not give any error (that might be a non problem when default boilerplate... theme! will be in its own package - or maybe not, according to the "eject" feature #596).

**Comment by thangngoc89** [comment]
I dont think eslint autofix is capable of doing such a thing. A test should confirm tht

**Comment by MoOx** [comment]
eslint autofix can adjust indentation, change quote from double to single, add or remove semicolons, add or remove trailing comma, etc. It can handle a lot, more and more each days!

**Comment by revolunet** [comment]
Personally i disabled autofix because i prefer to have my warnings in my IDE and handle linting progressively. looks like im doing a lot of `⌘+S` while coding and this can be annoying.

Linting is too restrictive here for me but everyone as it tastes so i suggest to just make linting non-blocking :)

**Comment by MoOx** [comment]
autofix can be used "once" when user have choose his config, right after config. I will probably remove autofix, or ask in setup. We should find a way to make setup more flexible (but I have no idea atm on how to make this flexible... codemods?)

**Comment by revolunet** [comment]
CLI flag ?

**Comment by MoOx** [comment]
not sure if cli/options should adjust webpack config loader options (will make more boilerplate). But when we will provide default theme as a package, why not!
