### ISSUE TITLE
Phenomic loads css files in node_modules differently in dev and static mode

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#639]
Reproduce: 

```
git clone https://github.com/thangngoc89/dnh-cpp && cd dnh-cpp
git checkout upgrade-phenomic
# Normal dev mode, nothing happen
npm run start

# Failed on build
npm run build
```

This is the error: 

```
> dnh-cpp@ build /home/khoa/web/dnh-cpp
> phenomic build

  phenomic:builder ✓ Static build: assets copy completed +0ms
  phenomic:builder ✓ Static build: client build completed +13s
  phenomic:builder ✓ Static build: static build completed +2s
/home/khoa/web/dnh-cpp/node_modules/normalize.css/normalize.css:9
html {
     ^
SyntaxError: Unexpected token {
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/khoa/web/dnh-cpp/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at eval (eval at <anonymous> (/home/khoa/web/dnh-cpp/node_modules/.cache/phenomic/phenomic.node.bundle.js:3:18018), <anonymous>:1:18)

```

According to the error stack trace, `normalize.css` was loaded as a js file, not as a css file. 
I can reproduce this bug on master of phenomic too

See https://github.com/MoOx/phenomic/compare/issue-639?expand=1

Steps to reproduce: 

```
# Clone and checkout
cd boilerplate && npm install normalize.css
npm run build
```

**Comment by revolunet** [comment]
Had the same issue last week with react-flexbox-grid

Workaround : add this to the webpack config (hint from https://github.com/roylee0704/react-flexbox-grid/issues/28#issuecomment-198758253)

```js
require.extensions['.css'] = () => {
  return;
};

// and 
{
  test: /\.css$/,
  include: [/node_modules\/flexboxgrid/],
  loader: 'style!css?modules'
}
```

**Comment by thangngoc89** [comment]
@revolunet where should I add the `require.exensions` ?

**Comment by thangngoc89** [comment]
> @revolunet where should I add the require.exensions ?

Answer my own question: Put it in webpack.config.babel.js

There is no **real** fix for this right ?

**Comment by MoOx** [comment]
OMG. I think I have the answer. https://github.com/MoOx/phenomic/blob/5d93d4f4297e1541fe90650b48732aa89da0965f/src/builder/webpack/config.node.js#L33-L38
I guess the [a-z] regex should be tweaked to match .js files only...

**Comment by MoOx** [comment]
Should be easy to fix. Sorry @revolunet for missing that the other day!

**Comment by thangngoc89** [comment]
OMG. That code was there since forever

**Comment by MoOx** [comment]
The goal is to avoid ALL DEPS being compiled into the phenomic.node build (otherwise it's longer to compile static build). Meanwhile, you can provide your own "externals" in you webpack config. Try something like

```
    externals: /^[A-Za-z0-9-_].*[^\.][^c][^s][^s]$/
```

Source: http://refiddle.com/im81

**Comment by revolunet** [comment]
Cool we have a solution thanks 👍

**Comment by MoOx** [comment]
If you confirm this works for you 2, I can add this in master before cutting the new release :)

**Comment by thangngoc89** [comment]
This works for me

**Comment by revolunet** [comment]
works for me too thanks \o/

**Comment by MoOx** [comment]
You will be able to remove the "externals" option completely i 0.16.1. See release notes.

**Comment by kennu** [comment]
I got some errors in dev mode with the suggested workaround:

    externals: /^[A-Za-z0-9-_].*[^\.][^c][^s][^s]$/

    phenomic.browser.b6957d1….js:1212 Uncaught ReferenceError: ansi is not defined

But I got it working in both dev and static mode with this regex that doesn't match any files:

    externals: /.^/

**Comment by MoOx** [comment]
I am working on another trick to avoid all those issues.

**Comment by thangngoc89** [comment]
@kennu this became more annoying than ever. Please track this 

https://github.com/MoOx/phenomic/issues/656

**Comment by nhjk** [comment]
How do I use bootstrap in phenomic? I'm doing `import "bootstrap/dist/css/bootstrap.css"` in `src/AppContainer.js`, but I keep getting unexpected token errors. I've been looking at these issues for hours and trying the workarounds, but I can't get them to work. I'm using phenomic 0.20.1.
