### ISSUE TITLE
Mention html-to-react-components to start fresh boilerplate

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#64]
https://github.com/roman01la/html-to-react-components

**Comment by MoOx** [comment]
Also interesting to mention http://jxnblk.com/rebass/

**Comment by thangngoc89** [comment]
I think this should be renamed to tips for React starter :)

**Comment by thangngoc89** [comment]
Also mention flexbox polyfill. 

https://github.com/10up/flexibility (There is no reason for me to not learning flexbox anymore)

**Comment by MoOx** [comment]
Also http://jxnblk.com/reflexbox/
