### ISSUE TITLE
Build context

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#641]
I am running into a problem with a third party module (from auth0), where one of their dependancies is referencing `window` and `navigator` and is causing the phenomic node build to fail. (`npm start` dev works fine, but node static build chokes)

I'm unable to differentiate the node vs browser build from my webpack config in my site. 

It looks like that would have to happen deeper at https://github.com/MoOx/phenomic/blob/master/src/builder/webpack/config.common.js#L25 

I'm proposing adding a `PHENOMIC_BUILD_CONTEXT` variable here so we can use conditionals in our code to include none isomorphic friendly libs.

In my code, I'd like to do this: 
```js
// dynamic require in the phenomic site
if (process.env.PHENOMIC_BUILD_CONTEXT === 'browser') {
  const ModuleReferencingWindow = require('non-isomorphic-compatible-lib')
} else {
  // node context, don't require the code for isomorphic build
  const ModuleReferencingWindow = {}
}
```

What do you guys think?

I'm working on adding Auth to our new site and this is a core piece of it =). Going to discuss this in the phenomic demo I'm doing at the react meetup later this month

**Comment by thangngoc89** [comment]
my way of checking for browser/node: 

if (typeof window !== 'undefined')

Could you try that first? Afaik, that's only way for isomorphic app. I don't want to introduce a different way of doing this in phenomic

**Comment by DavidWells** [comment]
I tried that. It didn't work. Node kept choking on the node dependancy (out of my control)

I will try again.

But the webpack provide in browser.webpack fixed the issue for me

**Comment by DavidWells** [comment]
Lolz. Nevermind. @thangngoc89 you are right =P

I was wrapping my module incorrectly
