### ISSUE TITLE
Code splitting via routes

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#643]
Another future perf question ;)

Is it possible to override the default single script phenomic.js into a chunked build based on routes (and/or layout components)?

https://webpack.github.io/docs/code-splitting.html

**Comment by MoOx** [comment]
I didn't try that yet, but I guess there is nothing to do from Phenomic side, as webpack will handle require.ensure/System.import automatically and create more chunks (in theory).
You may want to check react-router docs as well https://github.com/reactjs/react-router/blob/master/docs/guides/DynamicRouting.md#dynamic-routing

**Comment by bloodyowl** [comment]
Going to be fixed with #925 (moving to user-land)

**Comment by MoOx** [comment]
User land thing with v1.
