### ISSUE TITLE
Add source map for phenomic.node.bundle.js

### ISSUE THREAD

**Issue by revolunet** [MoOx/phenomic#644]
When running `npm run build` i get a cryptic error with no detail on the origin of the problem.

In that case i guess its some non server-compatible module but hard to find the exact source

<img width="1221" alt="capture d ecran 2016-08-22 a 13 46 28" src="https://cloud.githubusercontent.com/assets/124937/17853886/7e36a202-686f-11e6-9430-34ec2f89579d.png">

I have no idea how to debug this

**Comment by MoOx** [comment]
I am not familiar how node can handle sourcemaps, I guess if we add correct sourcemap config in webpack, we will get proper source of the error.

Can you try this package? https://github.com/evanw/node-source-map-support#installation-and-usage
Including the line in `scripts/phenomic.node.js` should do the trick for testing.

Here is a "simple" way to add it automatically for us in the future, is it's working correctly http://jlongster.com/Backend-Apps-with-Webpack--Part-I#Sourcemaps,-CSS,-and

**Comment by revolunet** [comment]
tried the line in `scripts/phenomic.node.js` and the webpack banner plugin and same message :/

**Comment by MoOx** [comment]
@revolunet I forgot an crucial part: Add sourcemap in your webpack config! (The default boilerplate only add for dev env!) 
Try adding `devtool: 'sourcemap'` in  your config for all env please :)

**Comment by revolunet** [comment]
For some reason i had some minimal info in the console (i dont know how) :

<img width="627" alt="capture d ecran 2016-08-23 a 02 00 50" src="https://cloud.githubusercontent.com/assets/124937/17875987/e55d1f3a-68d6-11e6-9f48-64a13b2eabf4.png">

and it appears this line comes from `style-loader` : https://github.com/webpack/style-loader/issues/114

**Comment by MoOx** [comment]
> For some reason i had some minimal info in the console

That would be really nice to know what you did to get something more relevant ^^
