### ISSUE TITLE
Discussion: Pull instead of Push

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#645]
Just wanted to leave this here for discussion.

This post by kyle was pretty interesting: https://bricolage.io/gatsby-open-source-work/

> Pull instead of Push: This last idea is a bit abstract but super powerful. Currently data in Gatsby (like pretty much every static site generator) is pushed into templates to be rendered into HTML. This is a simple pattern and works great for many use cases. But when you start working on more complex sites, you really start to miss the flexibility of building a database-driven site. With a database, all your data is available to query against in any fashion that you’d like. Whatever bits of data you need to assemble a page, you can pull in. You want to create author pages showing their bio & last 5 posts? It’s just a query away. I want this same flexibility for Gatsby. I want to be able to query my markdown files and treat them as a database of sorts. I’ve hit on what I think is an excellent way to do this and am prototyping the code. Expect to hear more on this soon. Ping me if you’d like an early demo. It’s using GraphQL under the hood and the collocated queries pattern developed by Relay. I couldn’t be more excited about this feature. It’ll open up so many useful and powerful options.

This is the idea behind collections yes?

Perhaps there is a way to have static everything + a query-able database through a managed search provider like [algolia](https://www.algolia.com/doc/guides/getting-started/how-it-works#introduction) or AWS elasticsearch.

**Concept**: When phenomic builds it pushes the window.collection up to algolia index and then you can have instant search on the site. (the free algolia account should cover most sites)

This would obviously not be in core phenomic but a potential 'search' plugin

**Comment by thangngoc89** [comment]
I implemented it a while ago. See it here 

http://blog.daynhauhoc.com/

Source: https://github.com/daynhauhoc/blog

After implemented it, I think Phenomic should make it easier and prettier to implement these function. If you have any ideas of how to implement this please let's us know

**Comment by MoOx** [comment]
> > You want to create author pages showing their bio & last 5 posts? It’s just a query away

Haha, we can already do that with Phenomic ;)
So yeah it's "collections". The thing is collections does not offer the entire content of each posts.
Grapql might offers more flexibility, I found this is overengineered (and some might say using React for a static website is already overengineered...).
We can offers (like Phenomic currently does) a more simple API. I plan to remove "collection" from the context and just offer a `getCollection({ options })` function `from "phenomic"`. Do you think it's a good idea?

I like simple things and thing for 95% of use cases, a simple filtering/sorting on the collection is more than enough...

I even have an idea in my mind to handle pagination using this API, which will allow with a very small change to generate all possible pages (*/1, */2 etc)!

**Comment by bloodyowl** [comment]
Going to be fixed with #925

**Comment by MoOx** [comment]
v1 works with an (sort of) rest API.
