### ISSUE TITLE
Ignore file-ignored warnings from stylelint

### ISSUE THREAD

**Issue by kennu** [MoOx/phenomic#647]
I'm trying to ignore Bootstrap CSS (in node_modules) by adding

    "stylelint": {
      "ignoreFiles": "**/bootstrap/**"
    }

It works, but it causes the Phenomic build process to bark out a 500 line warning message every time I edit something:

    WARNING in ./~/css-loader!./~/postcss-loader!./~/bootstrap/dist/css/bootstrap.css
    stylelint: This file is ignored

Couldn't figure out a way to ignore CSS files without the warning.

**Comment by MoOx** [comment]
Ouch. I have to admit this sucks. Need to check who is the culprit.
That can be stylelint itself or webpack... poke @davidtheclark @jeddy3

**Comment by MoOx** [comment]
@kennu Maybe you can remove stylelint for this loader section? Should be straight forward.
Not sure if stylelint maintainers want to remove this warning :/

**Comment by kennu** [comment]
@MoOx Removed it, thanks for the advice. I'm still learning the framework so it was difficult to know where everything is enabled/disabled. But it's a really nice framework. :-)

**Comment by davidtheclark** [comment]
As of v7 stylelint reporter only tells you about ignored files if you use the verbose option. https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#700 So this is either due to an outdated version or the webpack loader doing its own thing, I think.

**Comment by MoOx** [comment]
Thanks a lot for the explanation. We currently use an outdated version (6.8.x). Sorry!
I will close this when we will udpate to 7.x.

**Comment by MoOx** [comment]
Closed by #741
