### ISSUE TITLE
Build fails when Bootstrap CSS is imported

### ISSUE THREAD

**Issue by kennu** [MoOx/phenomic#649]
I was able to get Bootstrap working in development mode (`npm start`):

    import "bootstrap/dist/css/bootstrap.css"

By uncommenting this in webpack.config.babel.js:

        {
          test: /\.css$/,
          // depending on your need, you might need to scope node_modules
          // for global CSS if you want to keep CSS Modules by default
          // for your own CSS. If so, uncomment the line below
          include: path.resolve(__dirname, "node_modules"),
          loader: ExtractTextPlugin.extract(
            "style-loader",
            [ "css-loader", "postcss-loader" ].join("!"),
          ),
        },

But when I try to build the production distribution, I get an error:

    phenomic:builder ✓ Static build: assets copy completed +0ms
    phenomic:builder ✓ Static build: client build completed +0ms
    phenomic:builder ✓ Static build: static build completed +986ms
    /...myproject/node_modules/bootstrap/dist/css/bootstrap.css:7
    html {
         ^
    SyntaxError: Unexpected token {

I'm a bit confused what's going on. At the time of error, there is already a CSS bundle generated in dist, and it seems to include the Bootstrap CSS:

    $ ll dist
    total 3920
    -rw-r--r--  1 kennu  staff      535 Aug 23 03:07 404.html.f3d82a4d938b593823c37ead979b3b86.json
    drwxr-xr-x  3 kennu  staff      102 Aug 23 03:06 assets
    -rw-r--r--  1 kennu  staff      519 Aug 23 03:07 feed.xml
    -rw-r--r--  1 kennu  staff   108738 Aug 23 03:07 glyphicons-halflings-regular-89889688147bd7575d6327160d64e760.svg
    -rw-r--r--  1 kennu  staff    45404 Aug 23 03:07 glyphicons-halflings-regular-e18bbf611f2a2e43afc071aa2f4e1512.ttf
    -rw-r--r--  1 kennu  staff      310 Aug 23 03:07 index.html.22b662838edf9f0530e093a990a6461a.json
    drwxr-xr-x  3 kennu  staff      102 Aug 23 03:07 loading
    -rw-r--r--  1 kennu  staff   248932 Aug 23 03:07 phenomic.browser.bceef2dbf1838f8497d5.css
    -rw-r--r--  1 kennu  staff  1583710 Aug 23 03:07 phenomic.browser.bceef2dbf1838f8497d5.js

It seems like only the final index.html fails to build?

**Comment by MoOx** [comment]
This is a dup of #639.
Will push a quick fix asap.

**Comment by MoOx** [comment]
FYI, a workaround is explained here https://github.com/MoOx/phenomic/issues/639#issuecomment-241283144
