### ISSUE TITLE
Upgrade 15 to 16 react-router-scroll issue

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#652]
Following the upgrade commit: https://github.com/putaindecode/putaindecode.io/commit/aa1b037

I get an `Uncaught TypeError: (0 , _reactRouterScroll2.default) is not a function`

![image](https://cloud.githubusercontent.com/assets/532272/17879524/85da10ce-68a7-11e6-9dee-1d8336e60eab.png)

I installed phenomic 0.16 via npm `npm i phenomic@0.16.0 --save` 

Any ideas what is going on here? 

`react-router-scroll@0.3.2` is installed in the node_modules folder

related perhaps https://github.com/TrueCar/gluestick/issues/231

**Comment by DavidWells** [comment]
Perhaps this? https://github.com/MoOx/phenomic/commit/7e275b7a65a23c60b97c82aadb1d2dc7572c0bb8

**Comment by DavidWells** [comment]
Confirmed 

`rm -rf node_modules/react-router-scroll && npm i react-router-scroll@0.2.0` fixed this bug

Looks like v 0.3.0 has breaking change how it's called/imported

**Comment by MoOx** [comment]
This is a bug. Will fix it.

**Comment by MoOx** [comment]
@DavidWells can you tell me what is your version of react-router?

**Comment by DavidWells** [comment]
Did a `rm -rf node_modules` after installing phenomic 0.16 from npm.

The react-router version in there right now is react-router@2.7.0

**Comment by MoOx** [comment]
Found the issue https://github.com/taion/react-router-scroll/commit/29b3e0b0ff73d375997ab8b16aca358606948b92#diff-1fdf421c05c1140f6d71444ea2b27638L6
It was exporting a function in 0.3.1, not anymore. Will push a fix.

**Comment by DavidWells** [comment]
@MoOx Thanks for the quick fix. Can you bump the NPM version too =)

**Comment by MoOx** [comment]
Wait a minute, I am trying to push another fix as well ;)
