### ISSUE TITLE
Error: phenomic (static) doesn't handle redirection yet

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#653]
After upgrading from 0.15 to 0.16

![image](https://cloud.githubusercontent.com/assets/532272/17881407/fe084252-68b9-11e6-9e2f-7375b8dd3c9f.png)

This is after fixing this bug https://github.com/MoOx/phenomic/issues/652 the `npm run build` fails

**Comment by MoOx** [comment]
Phenomic does not handle redirections indeed. This need some work and an issue is already open. See #628.

**Comment by DavidWells** [comment]
@moox I haven't setup any redirects is the problem =)

**Comment by MoOx** [comment]
Hum... Can you show me your `routes.js` ?

**Comment by DavidWells** [comment]
I do have an odd route config:

```
export default (
  <Route component={Index} auth={auth}>
    <Route path='/resource/:id' component={Resource} />
    <Route path='login' component={Login} auth={auth} />
    <Route path='access_token=:token' component={Login} />
    <Route path='/protected' component={Login} onEnter={requireAuth} auth={auth} />
    <Route path='*' component={Layouts} />
  </Route>
)
```

**Comment by MoOx** [comment]
Hummm... Does `onEnter` handle a redirection? My guess is "yes", since it seems to be a protected page.

**Comment by DavidWells** [comment]
@MoOx yep that was the issue.

Will try to check for window and give onEnter `null` on static build

**Comment by MoOx** [comment]
Yeah you will probably need to do something like that.
We should add a note in the FAQ cause we can't really fix that :/

**Comment by DavidWells** [comment]
This is the full code that works with static build now =)

```js
import React from 'react'
import { Route } from 'react-router'
import Index from './Index' /* Main entry of all requests */
import Layouts from './layouts' // Page Layouts
import Login from './components/Login/Login'
import Resource from './layouts/Resource' // layout for dynamic route
import AuthService from './utils/AuthService'
const isClient = typeof window !== 'undefined'
const auth = new AuthService(__AUTH0_CLIENT_ID__, __AUTH0_DOMAIN__) // eslint-disable-line
let requireAuth = null
// onEnter callback to validate authentication in private routes
if (isClient) {
  requireAuth = (nextState, replace) => {
    console.log(auth)
    if (!auth.loggedIn()) {
      replace({ pathname: '/login' })
    }
  }
}

export default (
  <Route component={Index} auth={auth}>
    <Route path='/resource/:id' component={Resource} />
    <Route path='login' component={Login} auth={auth} />
    <Route path='access_token=:token' component={Login} />
    <Route path='/protected' component={Login} onEnter={requireAuth} auth={auth} />
    <Route path='*' component={Layouts} />
  </Route>
)
```

One oddity I have with this route config though is hard refreshes on site.com/login for example flash a 404 then the router kicks in and displays the correct page. 

Does every route need a matching .md file to avoid this?

**Comment by MoOx** [comment]
> Does every route need a matching .md file to avoid this?

No, if you have a weird behavior, it's probably a bug.

**Comment by DavidWells** [comment]
ok scratch that. Must have been my fault or something in 0.15 only

Thanks for the quick fix. =)

**Comment by MoOx** [comment]
@DavidWells do you have a trailing slash for you login route? Can you try to access `.../login/` from your static build?

**Comment by DavidWells** [comment]
The /login index.html file is now in my dist folder. For some reason on 0.15 it didn't seem like that was the case for my custom routes

**Comment by MoOx** [comment]
@DavidWells indeed, previously only .md (files consumed by phenomic loader) were converted to html. Now all pages are supposed to be handled, with some restrictions https://phenomic.io/docs/usage/routing/

For your 404, a nasty thing can be this site.com/login !== site.com/login/

**Comment by MoOx** [comment]
Thanks for the PR on the doc ❤️
I will close this when a entry in the FAQ explain the error message :)

**Comment by MoOx** [comment]
Should be automatically handled when we do #628, so closing in favor of this one.
