### ISSUE TITLE
Module parse failed autoit.js

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#658]
Getting a build error with 0.16.2

phenomic:builder ModuleParseError: Module parse failed: /opt/build/repo/node_modules/highlight.js/lib/languages/autoit.js Maximum call stack size exceeded
You may need an appropriate loader to handle this file type.
RangeError: Maximum call stack size exceeded

I've fixed it via webpack noParse. Adding autoit.js to noParse fixed this https://github.com/isagalaev/highlight.js/issues/895#issuecomment-149223858

For anyone else seeing this issue, my webpack looks like:
```
  module: {
      noParse: [/\.min\.js/, /autoit.js/],
  }
```

**Comment by DavidWells** [comment]
Note that this was happening on local build, then I `rm -rf node_modules` and then local build oddly worked without this noParse change.

However our CI/CD build was always failing until the noParse /autoit.js/ was added and its fixed now =)

**Comment by thangngoc89** [comment]
I reported this before. You'll need to upgrade remark-highlight@4.0.1

**Comment by thangngoc89** [comment]
Btw: https://github.com/MoOx/phenomic/issues/616 

Should I mark this as a dup ?

**Comment by MoOx** [comment]
@DavidWells you have an outdated version of highlight.js, probably in your package.json. Just remove it.
remark-highlight.js should handle the correct dep for you (and latest version does not ship the buggy version).

Dup of #616
