### ISSUE TITLE
Add custom data to redux store

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#659]
I'm not able to add custom keys to the redux store. Is there something special I need to do?

```
import { combineReducers } from 'redux'
import createStore from 'phenomic/lib/redux/createStore'
import * as phenomicReducers from 'phenomic/lib/redux/modules'

window.__INITIAL_STATE__ = {
  test: 'please add to redux store'
}
const store = createStore(
  combineReducers(phenomicReducers),
  { ...(typeof window !== 'undefined') && window.__INITIAL_STATE__ }
)

export default store
````

I'm getting this error when trying to add my own custom keys
"warning.js?07c3:14Unexpected key "test" found in initialState argument passed to createStore. Expected to find one of the known reducer keys instead: "pages". Unexpected keys will be ignored."

![image](https://cloud.githubusercontent.com/assets/532272/17913542/c0371bd8-694f-11e6-91da-f1f7f264eec2.png)

Any ideas?

**Comment by thangngoc89** [comment]
window.__INITIAL_STATE__ doesn't expect to be alter by hand. 

Please read this section about how to add custom redux reducer (along with your own initialState) here 
https://phenomic.io/docs/advanced/redux/

**Comment by DavidWells** [comment]
Thanks for the quick response! I saw those docs. Do you have any live examples I can checkout?

I was just trying to combine the initial state, with some custom stuff to start. I was going to hook up the reducers for them later.

```
import { combineReducers } from 'redux'
import createStore from 'phenomic/lib/redux/createStore'
import * as phenomicReducers from 'phenomic/lib/redux/modules'

const additionalState = {test: 'hi'}
const combinedInitialStateObject = { ...(typeof window !== 'undefined') && window.__INITIAL_STATE__, ...additionalState }
const store = createStore(
  combineReducers(phenomicReducers),
  combinedInitialStateObject
)
console.log('combinedStateObject', combinedInitialStateObject)
export default store
```

The store when it gets combined with the `pages` key drops my custom `test` key

**Comment by thangngoc89** [comment]
This is how redux work. You're adding a state tree that no reducer can handle, so it throws error. 
I don't have any live example for you but this is mostly redux stuff. What are you trying to achieve here ?

**Comment by DavidWells** [comment]
It's possible (or it was) to set whatever initial state you wanted in `createStore` 

Does redux strip it out now if there is no reducer to act on that key?

I will setup a new reducer and test this out. I still need to set the intial state somewhere and I don't see where you would do this other than `createStore` here. Going to follow the ducks pattern https://github.com/erikras/ducks-modular-redux#example

**Comment by MoOx** [comment]
Like it has been explained, you probably just miss a reducer, that's how redux works.

Anyway, do not count too much on Phenomic store as it is going to be removed (you will have to handle it yourself). Please track #40.
I will try to provide instructions when it will be remove so people can keep their custom reducers using a custom store.

**Comment by DavidWells** [comment]
@moox @thangngoc89 yep this was my fault. Importing stuff all wrong =/

Fixed it though and now have userAuth setup in redux! =)

**Comment by DavidWells** [comment]
For anyone else interested. Redux will throw errors if you don't setup the corresponding reducer to handle the state key passed in.

I hadn't seen this before
