### ISSUE TITLE
Docs: How do I add a featured image in the markdown file?

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#663]

**Comment by drFabio** [comment]
What is this about ?
I am already adding an image by adding on the metadata and extending PagePreview for example to display it on the list. Is something like this or something else?

**Comment by MoOx** [comment]
Something like that yes. Use a field in the metadata and then just use this field in a component :)

**Comment by MoOx** [comment]
Closing in favor of #736. Thanks @drFabio!
