### ISSUE TITLE
Bug with anchors

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#665]
Ref https://github.com/taion/react-router-scroll/issues/37

**Comment by mistadikay** [comment]
Hi, so I'm in the middle of investigation on how to handle this bug. So far I came to this solution: https://github.com/mistadikay/phenomic/commit/1537aa9a1a6568bb219b65b70aeada680670e862 It solves anchors problem when they're on the same page, but it doesn't work on the first load and when I'm navigating to another page with an anchor (for example to `/team#profile` from `/contacts`). I guess there might be a way to solve it with `shouldUpdateScroll` hook in `ScrollContainer` element, but so far I couldn't make it work.

Where are you guys standing on this at the moment? I think @thangngoc89 investigated this bug as well?

**Comment by MoOx** [comment]
Hi @mistadikay. I didn't dig yet and @thangngoc89 don't have much time for a few weeks so, feel free to keep investigating.
Your draft looks good so far! I appreciate the contribution <3

**Comment by MoOx** [comment]
@mistadikay did you find how to fix the entire problem?

**Comment by mistadikay** [comment]
nope, requirements have changed for my project and it's not a priority right now, so I didn't contribute more thought into this

**Comment by MoOx** [comment]
Will cut a release with the fix tomorrow morning.

**Comment by mistadikay** [comment]
@MoOx you're just awesome, thanks a lot for your work!

**Comment by MoOx** [comment]
There are still bugs left https://github.com/stylelint/stylelint.io/issues/25#issuecomment-262742885

**Comment by MoOx** [comment]
Should be better know and will work with async(slow) loading.
