### ISSUE TITLE
FAQ: why did I get a page with "..." when running "npm start"?

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#679]

**Comment by kevin940726** [comment]
Is this a bug or a todo documentation?

**Comment by thangngoc89** [comment]
@kevin940726 this is a TODO documentaition. 

This happens because ReactDOM.render haven't mount to root container yet.

```
<body>
   <div id="root">...</div>
</body>
```

Maybe we can replace ... with something useful

**Comment by kevin940726** [comment]
I see. `...` looks like a bug a lot though, I agree we should change it or just simply left it blank?

**Comment by thangngoc89** [comment]
@kevin940726 this is a normal behaviour React app in dev mode. I think the message should be `Loading... Be patience`

Could you send a PR ? 

Pretty much edit this line : https://github.com/MoOx/phenomic/blob/161dbc63410e56451af8568377ff4aab38971ac1/src/builder/server.js#L135

**Comment by kevin940726** [comment]
Sure. But just to be clear, it doesn't show on production at all right?

**Comment by thangngoc89** [comment]
@kevin940726 yes. In production, it's full HTML page.

**Comment by DavidWells** [comment]
I was thinking about this the other day. 

Would it be possible to provide your own default loading content here: https://github.com/MoOx/phenomic/blob/161dbc63410e56451af8568377ff4aab38971ac1/src/builder/server.js#L135 else leave it blank?

I'd like to do something like: http://tympanus.net/Tutorials/PagePreloadingEffect/ which requires some default content living in that `div` and some hardcoded css/js in the DOM.

I think blank is better than seeing the `...` flash in the left part of screen before the react app bootstraps

**Comment by kevin940726** [comment]
Since it only shows in development mode, which means usually only developers(us) can see that pre-loading effect. I don't see why we should implement that in the core?

But I agree that maybe blank is better than even `Loading... Be patience`, which may need extra documentation to let the users know that this message will not be seen in production. Or simply add a note like `this will only show in development` in the loading message.

**Comment by thangngoc89** [comment]
@DavidWells I think putting some coll effects their is over-engineering.

**Comment by DavidWells** [comment]
@thangngoc89 I agree. How about we just remove the `...` =)

**Comment by thangngoc89** [comment]
@DavidWells Agreed. @kevin940726 could you update your PR to completely remove `...`.

**Comment by MoOx** [comment]
What can be nice is:

- remove ...
- add a simple inline script wrapper by a setTimeout that will show "if loading is too long, your page might contains error(s), please check the console" or something like that and kill the timeout when app is mounted.

This would avoid people saying "I have a blannnnk  paaaageeee, phenomicccc is nooot workinnnnng".

Thoughts?

**Comment by kevin940726** [comment]
Never thought about that! I actually think that this is a good idea.

**Comment by MoOx** [comment]
I am using this pattern on all apps I make: splash screen + timeout for potential error/slow loading + kill timeout when app is successfully mounted and people are happy with it :)

**Comment by DavidWells** [comment]
Lol I want to make your life easier and avoid having to answer "I have a blannnnk paaaageeee, phenomicccc is nooot workinnnnng" support questions

Removing the content + the timeout message sounds solid to me.

**Comment by thangngoc89** [comment]
Lol. This sounds awesome to me. @kevin940726 could you implemented this?

**Comment by MoOx** [comment]
I am on it ;)

**Comment by kevin940726** [comment]
Question: Is there any known way to produce such a bug so we can let the user figure out where possibly went wrong?

**Comment by MoOx** [comment]
Yeah, you will see ;)

**Comment by DavidWells** [comment]
@moox even better than a 'please check the console' would be printing the console error in the page when the setTimeout runs.

http://stackoverflow.com/questions/16616722/sending-all-javascript-console-output-into-a-dom-element

```
   window.onerror = function(message, url, linenumber) {
        console.log("JavaScript error: " + message + " on line " +
            linenumber + " for " + url);
    }
```

**Comment by MoOx** [comment]
@DavidWells YOU RUINED THE SURPRISE 👿

**Comment by MoOx** [comment]
I ended up doing a simple & stupid window.onerror only, as the app start really quickly, too quickly to have time to display anything useful. 

Check out #725
