### ISSUE TITLE
Idea: key in yaml to ignore specific markdown files on build

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#688]
Sometimes I have markdown files that aren't ready to be published but are in the repo in the `/content` folder.

```md
page-xyz.md
---
title: Whatever!
layout: Page
---

Content coming!
```

What would be cool is if I could add a `status:draft` (or `draft:true`) key to the frontmatter yaml and ignore the file in the site build. 

Then people in the repo can contribute to the non-published doc and the file wouldn't need to get moved around a bunch.

**Example:**

```md
page-xyz.md
---
title: Whatever!
layout: Page
status: draft
---

Content coming! This markdown file is now ignored by phenomic build!
```

**Comment by thangngoc89** [comment]
Duplicated of https://github.com/MoOx/phenomic/issues/111. Close ?

**Comment by MoOx** [comment]
Yeah it's a dup. We should definitely allow phenomic loader to produce multiples files or NO files at all via one entry.
