### ISSUE TITLE
Disable ServiceWorker in dev

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#689]
Most of the time, it's causing too much trouble.
We should allow to enable in dev via a cli flag only. Or via an option offline: { dev: true }

**Comment by thangngoc89** [comment]
What ? It's enabled in dev

**Comment by MoOx** [comment]
Nice part: This allows you to not have a blank page when you start the dev server.

**Comment by MoOx** [comment]
Bad part: when you have more than 1 phenomic project using offline, you might get the appshell of another website... Which sucks too much.

**Comment by thangngoc89** [comment]
That explains sometimes I saw phenomic docs instead of my webiste. We should disable SW in dev. It's annoying.

**Comment by MoOx** [comment]
That's why I opened this issue :)
