### ISSUE TITLE
Default theme: stop using pkg.name as site name

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#692]
Currently we are doing this

```
{ property: "og:site_name", content: pkg.name },
```

Which sucks because the pkg name is restricted to dashed-case.

We should think of a place to store the website name. Relying on pkg.name (and homepage etc) is not a good idea in all case.
We should provide upgrade instructions for this.

**Comment by thangngoc89** [comment]
I suggest using a seperate phenomic.yml (or toml/json) or something like that. It also serves as an identifier for phenomic projects.

**Comment by MoOx** [comment]
The easy way is to use https://github.com/davidtheclark/cosmiconfig which allow to use anything you want.

I guess we should add this fields in phenomic config:
- name
- url

**Comment by MoOx** [comment]
For other stuff like twitter/github/disqus etc we should allow a specific field to accept anything. We might call this "metadata".

**Comment by thangngoc89** [comment]
I think for configs, we should enforce a single location. The is better for themes. And `metadata` sounds right to me

**Comment by MoOx** [comment]
I don't like enforcing things. We will definitely _recommend_ a way, but I don't want people to not be happy. Anyway, people won't read doc, so they might miss this "feature": they will probably stick with recommended (default) way :)

**Comment by thangngoc89** [comment]
lol. It's your call. But sometime, flexibility comes with burden since people (like me) likes to customize everything and it's a burden to keep track of the upstream and bugs. 

If you're going with https://github.com/davidtheclark/cosmiconfig , I suggest that you add a function for theme author to get user's config like 

```
import { getConfig } from "phenomic"
```

**Comment by MoOx** [comment]
Yeah definitely!

**Comment by thangngoc89** [comment]
My suggestion: 

```
phenomic: {
   framework: {
       ...currentConfig,
   },
   site: {
      ...userCustomConfig,
   },
}
```

This should make a good convention for users who want to explore many different Phenomic projects

**Comment by MoOx** [comment]
What is currentConfig & userCustomConfig?
Why not just a flat config?

**Comment by thangngoc89** [comment]
No thing wrong with a flat config. But IMHO, breaking the configs to framework and site section would make it more organized. 

- currentConfig is configurations for Phenomic itself (offline, CNAME, assets, devPort). 
- userCustomConfig is for theme/component configs like googleAnalystic, cssnext's variable.

**Comment by MoOx** [comment]
We could allow this

```js
phenomic: {
  ...currentConfig,
  userConfig: { /* random values (not validated) */ }
}
```

**Comment by thangngoc89** [comment]
```
phenomic: {
  ...currentConfig,
  userConfig: { /* random values (not validated) */ }
}
```

This is better :D

**Comment by MoOx** [comment]
v1 will have a minimalistic config file
