### ISSUE TITLE
Discussion: Support for YYYY-MM-DD-post-name.md markdown files

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#700]
Would it be possible to support the standard jekyll post name format `YYYY-MM-DD-post-name.md`?
1. People could port from jekyll to phenomic with relative ease =)
2. Files in /blog would be easier to navigate through (example: https://github.com/auth0/blog/tree/master/_posts everything is in date order to quickly jump to a given post)

We are doing the serverless blog in phenomic as well and I'm trying to plan for the future when we have like 100+ markdown posts in a folder, It would be nice to have them in date order.

**Idea:** When phenomic builds routes, any markdown file name matching the pattern `YYYY-MM-DD` would automatically strip out the date and just be the name of file.

**Example:**  `2012-01-27-hello-world.md` become `hello-world` without needing to specify the custom `route` in the yaml frontmatter

Currently, you would need to provide the `route` param to frontmatter to the file with the `YYYY-MM-DD` prefix to remove that on the site url. I think we can streamline/remove this =)

**Comment by thangngoc89** [comment]
Hi @DavidWells, 

Personally, I don't like this kind of magic from Jekyll. This makes sense in Jekyll because it's a blog-aware static site generator (SSG) . On the other hand, Phenomic is a general SSG so this makes no sense to Phenomic. But supporting people migrating from Jekyll (or other SSG) should be a top priority for us. 

I migrated my blog from Jekyll to Phenomic once and I can feel the pain of this. 

So my suggesting is: make this configurable. Either exposing a hook to allow user edit the route mapping themselves or add a flag : `jekyll: true`

What do you think?

**Comment by DavidWells** [comment]
@thangngoc89 Yeah that sounds good.

I think we are still going to use the jekyll style convention though with the `YYYY-MM-DD` prefix but our blog content is going to live in a separate repo and will be included before `phenomic build` runs.

During this "before phenomic build" process, I'm going to remove all the date-prefixes from the file names. 

It would be night if phenomic did this though, not sure how it would be hooked up/configured because:

Some people might like the automatic removal BUT some people might want the `YYYY-MM-DD` in their URLs. Hard to say heh

**Comment by thangngoc89** [comment]
@DavidWells I marked this as a feature request. Will look in to this later .

**Comment by MoOx** [comment]
We could make an option *enabled by default* that convert date in filename to date in the front-matter. 
Oh and I guess we should handle that in phenomicLoader, maybe as a plugin if that's possible.

We should support that, it's very easy to implement.
Super handy for blog/news etc (everything related to time).
I will need that to convert my personal website anyway :)

**Comment by DavidWells** [comment]
I wrote this script to handle the automatic filename rewrites for us for right now if you find it useful

```js
var dir = require('node-dir')
var fs = require('fs-extra')
var path = require('path')
var destPath = path.join(__dirname, '..', 'content/blog/')
var blogSrcPath = path.join(__dirname, '..', 'node_modules/serverless-blog/posts/')

// Clear blog contents
fs.emptyDir(destPath, function (err) {
  if (err) {
    console.log('emptyDir fail!')
  }
  console.log('Blog folder emptied!')
  fs.copy(blogSrcPath, destPath, function (err) {
    if (err) return console.error(err)
    console.log("Blog content successfully moved!")
    renameAllFiles(destPath)
  });
})
// Copy and rename files
function renameAllFiles (filePath) {
  dir.files(filePath, function (err, files) {
    if (err) {
      throw err
    }
    files.forEach(function (name) {
      var newName = name.replace(/[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])-/g, '')
      fs.copy(name, newName, function (err) {
        if (err) {
          return console.error(err)
        }
        // remove old post
        fs.removeSync(name)
        // Do stuff to new post
      })
    })
  })
}

```

**Comment by thangngoc89** [comment]
@DavidWells I have some follow up for you. This is the part that needs to be modified in order to support this.

https://github.com/MoOx/phenomic/blob/bab74b8647ccfc20491f381303fdc340ae27ee24/src/loader/index.js#L40-L52

You can get fileName from `relativePath`, test if it match this format and append a date field to frontmatter.

But I think we should put this behind a flag/config because I don't like this to be the default behaviour.

**Comment by MoOx** [comment]
No need for a flag for a simple parsing. We can even skip a regex and do: take "XXXX-XX-XX".length first chars, split by - and check [0].length === 4 && [1].length ===2 && [2].length ===2. No need for an option for a simple thing that should be what most people except since jekyll is the most used SSG.

**Comment by thangngoc89** [comment]
OK. No flag the. But checking for length isn't enough, You'll need to validate Date too. Or you'll get an `Invalid Date` error when using it. I marked this as contribution welcome.

**Comment by MoOx** [comment]
Throwing "Invalid Date" does not look like a big deal as I think nobody will start a post with "1234-56-78" :D

**Comment by thangngoc89** [comment]
Haha. OK. The date someone complains about it, we'll add the check.

**Comment by bloodyowl** [comment]
With #925, this will automatically sort the collection with dates, you then just have to parse the date from the title in your UI code

**Comment by DavidWells** [comment]
I proposed this naming convention because it's a better way to keep posts in chronological order when trying to find + edit the file in the filesystem (finder or IDE).

It's also the 'standard' for naming posts in most (all?) other markdown driven static site generators. Which would make it super easy for people to port over their sites to another static site tool if they wanted to in the future.

![image](https://cloud.githubusercontent.com/assets/532272/21437875/4b8573de-c854-11e6-8ba8-ad25d4e01436.png)

I can still achieve [what I am doing in userland](https://github.com/serverless/site/blob/master/scripts/blog/remove-date-from-filename.js#L11-L23) but blog posts are typically chronological in nature and having posts ordered out of the box with the naming convention makes finding posts much easier.

**Comment by bloodyowl** [comment]
you *can* do it, but it shouldn't be the way we force users to make posts IMO

**Comment by DavidWells** [comment]
Yeah. Some people like it and some people hate it =)

Okay, I'll keep my build step =)

Great work on this BTW. Super stoked 🎉

**Comment by MoOx** [comment]
@bloodyowl I guess we could make a plugin? ;)

**Comment by bloodyowl** [comment]
yeah, I guess so 😉
