### ISSUE TITLE
Question: Possible to disable remark-highlightjs?

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#701]
Random question about Google indexing developer posts about code. 

I'm curious if the HTML generated from  `remark-highlightjs` is indexed correctly as the original source code or if it's jumbled up because of all of the additional `<span>` tags in the html.

We are going to publish a TON of src code and want to have it as google friendly as possible =). Just wondering if anyone has insight on this. 

Is it possible to disable or change how `remark-highlightjs` rendered src code?

```html
<!-- from remark-highlightjs in index.html file. SPAN CITY! -->
<pre><code class="hljs language-yml"><span class="hljs-attr">service:</span> first-service
<span class="hljs-attr">provider:</span> aws
<span class="hljs-attr">functions:</span>
<span class="hljs-attr">  hello:</span>
<span class="hljs-attr">    handler:</span> handler.hello
<span class="hljs-attr">    events:</span>
<span class="hljs-attr">      - schedule:</span> rate(<span class="hljs-number">10</span> minutes)
<span class="hljs-attr">resources:</span>
<span class="hljs-attr">  Resources:</span>
<span class="hljs-attr">    MyBucket:</span>
<span class="hljs-attr">      Type:</span> AWS::S3::Bucket
<span class="hljs-attr">      Properties:</span>
        BucketName : <span class="hljs-string">"myserverlessbucket"</span></code></pre>
```

I'm wondering if it's better to render the code as is in the `index.html` file and then have the client apply the syntax highlighting when the page loads.

This would be the "clean" example of code in index.html without span tags
```html
<!-- clean src code in index.html file 
and then highlight.js etc would bootstrap on client and highlight syntax -->
<pre><code class="js">
'use strict'

const User = use('App/Model/User')
class AuthController {
    index(request, response) {
        yield response.sendView('login')
    }
}

module.exports = AuthController
</code></pre>
```

**Comment by thangngoc89** [comment]
1) How google index highlighted code?  I don't know
2) Remove remark-highlight.js ? Yeah. Possible but It's a pain right now. You have to write yourself a custom plugin to do that. See https://phenomic.io/docs/usage/plugins/

We have an issue https://github.com/MoOx/phenomic/issues/668 to help with this pain. But no time yet. 

3) Putting the highlighted code in a seperated html file load it via http doesn't sound like a good choice to me. It looks complicated. My suggest is you use highlight.js directly in the client.

**Comment by DavidWells** [comment]
Thats what I am saying. Disabling the `remark-highlight` on build and only using it on the client =)

This might also be a request for people that want to use other syntax highlighters like prism.js

**Comment by thangngoc89** [comment]
@DavidWells could you make a PR for #668 ?

**Comment by DavidWells** [comment]
@thangngoc89 I see it being used here: https://github.com/MoOx/phenomic/blob/bd5a898aee22dea91c7cba936c34ec1d9f36c02f/src/phenomic-loader-plugin-markdown-transform-body-property-to-html/index.js#L29 I'm not sure how one would pass options there though.

I'm using the `phenomicLoader`. If I understand that correctly. The `phenomicLoader` is a preset of all the plugins combined already for me?
```
      {
          // phenomic requirement
          test: /\.md$/,
          loader: phenomicLoader,
          // config is in phenomic.contentLoader section below
          // so you can use functions (and not just JSON) due to a restriction
          // of webpack that serialize/deserialize loader `query` option.
        },
```

**Comment by thangngoc89** [comment]
@DavidWells I updated #668 ưwith more information. Could we continue the discussion overthere? You can pass the option via phenomic field in webpack config

**Comment by MoOx** [comment]
@DavidWells not sure what is the difference between code with and without span for Google. Any resources on that?
Anyway, closing in favor of #668 which might allow any default option to be adjusted.

**Comment by MoOx** [comment]
Closing as it's possible, even if not easy. Will be better with #668
