### ISSUE TITLE
Add more pages/layout in boilerplate

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#71]
At least 2/3 pages with on that handle collections.

**Comment by MoOx** [comment]
Eg: disqus example https://github.com/putaindecode/putaindecode.io/blob/797c87bad4491a7bf2277cabd55eeb23745b6315/web_modules/Layout/Post/index.js#L55-L59
and/or https://github.com/thangngoc89/blog/commit/d774f1553079599f007329e765a406e620e49933#diff-390581ab82ee594a7e11637f986763b6

**Comment by thangngoc89** [comment]
Some content with lorem ipsum right ?

**Comment by thangngoc89** [comment]
[React Waypoint](https://github.com/brigade/react-waypoint) is a better solution for React than the vanila Waypoint (I have to use it for other reason)

**Comment by MoOx** [comment]
Closing in favor of #428
