### ISSUE TITLE
Phenomic is bundling default render in client bundle

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#714]
The title pretty much explains itself. This should be consider at high priority and should be fix immediately. 

We have 2 options here: 

- Use webpack 2 tree-shaking 
- Remove phenomic-plugin-* export from `/src/index.js`

**Comment by MoOx** [comment]
webpack 2 #421, since more are moving to index.js. Should not be that hard anyway.

That's not really bug, but yeah that sucks :D

**Comment by thangngoc89** [comment]
It makes my bundle 1MB . So yeah, it really sucks

**Comment by thangngoc89** [comment]
After a careful measurement since it adds 500KB to the bundle size. This should be consider as a bug (well technically it doesn't)

**Comment by MoOx** [comment]
I planned to handle webpack 2 before previous release, I forgot :D

**Comment by thangngoc89** [comment]
This was resolved in master branch
