### ISSUE TITLE
Docs: gh-pages push from master branch

### ISSUE THREAD

**Issue by kevin940726** [MoOx/phenomic#729]
Following the docs [here](https://phenomic.io/docs/usage/gh-pages/) and the example deploy script below. The script will init git every time we deploy, so the default branch should be `master` and there will be no `gh-pages` branch. The script will fail because there is no matching ref.
```
error: src refspec master does not match any.  
error: failed to push some refs to 'ssh://xxxxx.com/project.git'
```

I've noticed that @MoOx actually changed it from `master:gh-pages` to only `gh-pages`. I wonder why?

BTW, is there any reason why we don't make this script (and the npm script also) part of the default boilerplate when the user choose to include deployment script in the setup script?

**Comment by MoOx** [comment]
The current "src refspec" issue has been fixed (but not published yet) in https://github.com/MoOx/phenomic/commit/b55f19e871cc40a2a915574eab9b0465858b74f3

Maybe I did a mistake by remove `master:` in https://github.com/MoOx/phenomic/commit/b55f19e871cc40a2a915574eab9b0465858b74f3?
If so can you fix this?

> BTW, is there any reason why we don't make this script (and the npm script also) part of the default boilerplate when the user choose to include deployment script in the setup script?

Maybe we should do this and ask people if they plan to use gh-pages. That can be subject to an improvement.

**Comment by kevin940726** [comment]
Sure, I'm on it! 🎉

**Comment by thangngoc89** [comment]
Be sure to ask if you don't understand any part of the code. I'm here for the next couple hours
