### ISSUE TITLE
phenomic-cli: make setup fast & more easy, (one install, one command?)

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#734]
We need to improve that, current setup page is not appealing.

Maybe create a phenomic-cli or something when handling #598.

Something fast, so not a electron app yet :D

**Comment by thangngoc89** [comment]
Which kind of work flow do you expect? 

npm install -g phenomic-cli
phenomic-cli new my-site

**Comment by DanielFGray** [comment]
a yeoman generator could be a good choice

**Comment by thangngoc89** [comment]
@DanielFGray did you try settting up a new phenomic project? We have everything in place, just need a better flow for new user

**Comment by DanielFGray** [comment]
Yeah I've just started with phenomic. I really dig it, but the whole `DIR=your-website-folder && mkdir $DIR && cd $DIR && mkdir node_modules && npm i phenomic && ./node_modules/.bin/phenomic setup && npm i` is a bit much. yeoman should be able to handle all of that. it uses inquirer as well, which seemed to be in use for the setup script.

I have yet to make a yeoman generator myself, but I'll have a look into what it takes and see if I can't create one

**Comment by thangngoc89** [comment]
@DanielFGray Thanks for your feedback. As you said the whole command sucks. 

My idea so far is creating a global phenomic cli that should never changed. If user want to create a new phenomic project, this is what they have to do: 

```
$ npm i -g phenomic-cli
$ phenomic new folder-name
```

This will run `DIR=your-website-folder && mkdir $DIR && cd $DIR && mkdir node_modules && npm i phenomic && ./node_modules/.bin/phenomic setup && npm i` 


Sounds good?

**Comment by DanielFGray** [comment]
It doesn't sound bad in the slightest, I just can't help thinking there's a certain amount of re-inventing the wheel there, and that off-loading it to yeoman could be a lot less work than writing a `phenomic-cli` project from scratch.

Just my two cents, I would be happy to use either.

**Comment by MoOx** [comment]
First keep in mind that the first part of the command (`DIR=your-website-folder && mkdir $DIR && cd $DIR && mkdir node_modules`) is the kind of instructions that no project includes.
Most of the time, when you start a project, you create a folder by yourself, and sometimes, already have a package.json.
So here the necessary evil is really `npm i phenomic && ./node_modules/.bin/phenomic setup && npm i`. We tried to include the "npm i(nstall)" in the setup itself, but it was not really great at this time. Since I discovered [ora](https://github.com/sindresorhus/ora), I am pretty sure we can include the install in the setup command.
We should be able to split this setup part in a specific package when we will handle #598.

**Comment by thangngoc89** [comment]
@MoOx how about putting the whole code in a bash file (or cmd for Windows). The cli just need to download and execute it. We can have a `stable` branch serves as a source of truth to download those scripts. It should be super easy (IMHO)

**Comment by MoOx** [comment]
No need for a branch, we can probably directly reach latest stable tag ;)
But yeah the cli should be pretty dumb so we don't have to update it. Or we can use https://www.npmjs.com/package/update-notifier

**Comment by thangngoc89** [comment]
I think it should be both. cli should be pretty dumb and we should use update-notifier.

**Comment by bloodyowl** [comment]
Going to be fixed with #925

**Comment by MoOx** [comment]
We will see that later, v1 will have start/build and that's it for now.
