### ISSUE TITLE
Build doesn't show `phenomic:static` log entries after upgrading to 0.16.0

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#739]
0.15.0

![image](https://cloud.githubusercontent.com/assets/3049054/18416772/b1c40f6e-7847-11e6-8297-73c67739f2b9.png)

0.16.2

![image](https://cloud.githubusercontent.com/assets/3049054/18416935/20062c46-784d-11e6-8319-6540088f0937.png)

**Comment by MoOx** [comment]
Is this just an log issue? Or is there missing files?

**Comment by thangngoc89** [comment]
it looks like missing files for me. No `.nojekyll`

**Comment by MoOx** [comment]
From my test, only the logs are missing. It seems that something is changing process.env.DEBUG value to undefined... But I have correctly the post build step. Maybe it's time to find a better way than debug module...

**Comment by MoOx** [comment]
Can't find the culprit here... I will remove "debug" because I am lazy. Anyway we don't really use it for it's main purpose: filter.

**Comment by thangngoc89** [comment]
Maybe I missed something here. Anyway, debug is unnecessary
