### ISSUE TITLE
Highlight JS not working in CI/CD build

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#743]
Totally random but it would appear that `remark-highlight.js` will run in local dev for me, and on local `phenomic build` but not inside of my continous deployment pipeline through netlify. It's running node 6 if that matters.

Did something change with how remark works? Netlify is getting fresh copies of all npm modules each time it builds.

**Local dev and build that works:**
![image](https://cloud.githubusercontent.com/assets/532272/18493481/a9652e28-79c5-11e6-9b8b-0a650a9c0378.png)
![image](https://cloud.githubusercontent.com/assets/532272/18493504/c82592da-79c5-11e6-933f-4e96ec9d7e79.png)

**actual site after CI/CD build has no syntax highlighting:**
![image](https://cloud.githubusercontent.com/assets/532272/18493541/f6405aa6-79c5-11e6-8f83-fb9148d0eee3.png)

https://serverless.com/framework/docs/guide/deploying-services/

Has anyone seen this?

**Comment by MoOx** [comment]
This is weird. I think I got the issue but it was before last update. What version of remark and remark highlight are you using?

**Comment by MoOx** [comment]
@DavidWells You should probably update your remark deps like mentionned here https://github.com/MoOx/phenomic/blob/21ad633ad382ee3b70d662c79fc5f514a8722b34/CHANGELOG.md#details this might fix your issue. Let me know if that helps.

**Comment by DavidWells** [comment]
@MoOx yep that was the problem.

I had older versions of remark as dev deps in our site. Removed them and everything magically worked.

Thanks =)
