### ISSUE TITLE
Setup CI for macOS on Travis CI

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#756]
"Modern" projects these day usually have build for 3 major OSes. What do you think?

**Comment by MoOx** [comment]
I think macOS is a unix based system so it's not require as we are not doing anything special except having to deal with windows path.

**Comment by MoOx** [comment]
Also, this will slow down CI a lot.

**Comment by thangngoc89** [comment]
Yup. It will slow down CI a lot.

> I think macOS is a unix based system so it's not require as we are not doing anything special except having to deal with windows path.

We'll never know. Testing is the right thing to do. Some projects run macOS build and Travis and Linux build on others CI like CircleCI or Wercker.

**Comment by MoOx** [comment]
I am a macOS user and never got any issue for node projects, so not sure it's really useful. The day we will encounter issues on macOS we can think about this.

**Comment by thangngoc89** [comment]
OK. !
