### ISSUE TITLE
Use lru-memoize for enhanceCollection

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#759]
`window.__COLLECTION__` never changes so caching the result is a must if we don't want to re-calculate

We can use [lru-memoize](https://github.com/erikras/lru-memoize) with a high limit (100 ?) 

If you are working on this and having trouble with lru-memoize definition for flow, you can look at this https://github.com/MoOx/phenomic/pull/720

**Comment by MoOx** [comment]
All those stuff are going away, we should not spend energy on this.

**Comment by thangngoc89** [comment]
@MoOx ah. ok. this should be 2 LOCs. And I'm having trouble with this on a site with 200 pages. (filter and limit).I guess I can apply the patch on my side then.

**Comment by MoOx** [comment]
If it's too line, feel free to handle it then :D

**Comment by thangngoc89** [comment]
I will
