### ISSUE TITLE
webpack@2 introduced a breaking change between beta22 & beta23

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#767]
Basically all configuration for eslint-loader, postcss-loader, sass-loader need to be moved out of webpack config as it's validated AND THROW ERRORS. Well... Fuck semver.

- https://github.com/webpack/webpack/pull/2974
- https://github.com/webpack/webpack/issues/3018

"Official" solution is to move those options into a loader plugin call...

https://github.com/webpack/webpack/pull/2974#issuecomment-245964406

You can say "no big deal man". But seriously, all of this because in the first place ``query`` can't handle some real JS (in a js file, that's funny right?) 

This solution is not acceptable for me *with my current mood* as everybody will have to update more of their code. So I am not ready to cut a release with this dawn change and it's blocking us for a major release. I am pissed off, sorry for that.

Tell me what you think about the "official" solution (it's more a poor "workaround" to me)...

**Comment by DavidWells** [comment]
![O no!](https://media.giphy.com/media/yedDQGWwq0heU/giphy.gif)

**Comment by MoOx** [comment]
Ok this has not been clear but it seems that query accept any JS now. This will do the trick.
Also what will need to be done:
- remove makeConfig (webpack 2 support directly a function)
- replace "loaders" by "rules"
- replace custom key by query directly

**Comment by thangngoc89** [comment]
Oh craps. This release takes forever.

**Comment by MoOx** [comment]
> This release takes forever.

This is for the better ;)

**Comment by thangngoc89** [comment]
> replace "loaders" by "rules"

What is this?

**Comment by MoOx** [comment]
just renaming "loaders" by "rules" in webpack.module section ( so module.loaders => modules.rules)

**Comment by thangngoc89** [comment]
I like that changes. It's confused as hell when I worked on the loader configuration transformer

**Comment by MoOx** [comment]
Fixed (kind of) in 7ca3cb1
