### ISSUE TITLE
Add last page url data to browserHistory

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#771]
I need a way to know the last page visited for a serverless 404-tracker I setup (and will be releasing soon). It's just a simple ajax call to a lambda function that fires when the 404 component is loaded and sends the 404'd URL along.

Adding a state object to the browser history push would presumably give me this info. https://github.com/MoOx/phenomic/blob/master/src/components/PageContainer/component.js#L154

proposed change:
```js
 browserHistory.push(pageUrl, {url: window.location.href })
```

```js
// from https://github.com/mjackson/history docs
// Use push, replace, and go to navigate around.
history.push('/home', { some: 'state' })
```

ref: http://stackoverflow.com/questions/18478602/how-to-get-the-previous-pushstate-with-javascript#answer-18478865
ref2: https://github.com/ReactTraining/react-router/blob/master/examples/pinterest/app.js#L126

I can do this with localstorage/cookies on my end but going to be messy to setup throughout my different templates

**Comment by DavidWells** [comment]
looks like my example code doesn't work here... 

```
// This has no effect and doesn't add state to the history or location object =P
 browserHistory.push(pageUrl, {url: window.location.href })
```

**Comment by MoOx** [comment]
In theory, you should be able to manually listen to history changes using native browser api and save this in an array or something.
Then, in your 404 layout componentDidMount you can handle this registry to read from it.

**Comment by thangngoc89** [comment]
How about listen to this in PageContainer? componentWillUpdate provide you currentProps and nextProps. You can get params/spat from there

**Comment by DavidWells** [comment]
Fixed with a layout refactor https://github.com/serverless/site/blob/master/src/layouts/Default/index.js#L19 https://github.com/MoOx/phenomic/issues/772#issuecomment-250367141
