### ISSUE TITLE
Idea: Callback function for PhenomicPageContainer

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#772]
There are some cases where I'd like to check the type of page being rendered and let some global elements know what type of page is rendering

For example right [here](https://github.com/serverless/site/blob/master/src/app.js#L36) in the main entry point, the `<Header>` is unaware of what the `{this.props.children}`  `PhenomicPageContainer` Layout is actually going to render.

I might want to change the site navigation links for example if the `Doc` layout is rendering.

Currently: I can rewrite my pages and have the lower level components control their own headers. This is fine and works and maybe how I should do this... but...

What if `PhenomicPageContainer` had a callback function like `onLayoutChange`?

```
export default class Layouts extends React.Component {
  setLayoutStateForHeader = (layout) => {
    console.log('current layout', layout)
    // Do redux thing
  }
  render () {
    return (
      <PhenomicPageContainer
        {...this.props}
        onLayoutChange={this.setLayoutStateForHeader}
        layouts={{
          Page,
          PageError,
          PageLoading,
          Homepage,
        }}
      />
    )
  }
}
```

Am I crazy? 

I'm kind of trying to emulate and get to the point where I can add `if` statements to dynamically render stuff in templates. Much like wordpress `is_page()` or `is_home()` or `is_search()` https://developer.wordpress.org/reference/functions/is_page/#comment-370

```js
// props.layout coming from global redux state 
if(props.layout === 'About') {
 // render different stuff
}
```

**Comment by MoOx** [comment]
You can probably use componentDidMount/componentWillReceiveProps of YOUR PageContainer to watch for change like we do for the docs for the GA tracker?
https://github.com/MoOx/phenomic/blob/bab74b8647ccfc20491f381303fdc340ae27ee24/docs/src/components/GoogleAnalyticsTracker/index.js#L34
props.param come from react-router. You probably have access to other r-r props and even context so I guess this should be enough for you?

I understand what you need and admit a callback would be handy. I am just afraid if we start adding some, we will quickly get too many and we can already track for changes via r-r.

**Comment by DavidWells** [comment]
I definitely don't want to complicate things. =)

My specific need is matching a 404 in this case. I'm not sure how to handle that

```js
 if (isNot404Page) {
 set cookie of last page viewed for my 404 tracker
}
```

I don't think `props.params.splat` will work for this. I was actually trying to do this logic right here https://github.com/serverless/site/blob/master/src/fragments/GlobalScripts/GoogleAnalytics.js#L24 =P

**Comment by DavidWells** [comment]
The one thing I miss about wordpress theming is these hooks https://codex.wordpress.org/Conditional_Tags#A_PAGE_Page . 

I'm brainstorming on how thing might be achievable with phenomic. 😃

**Comment by MoOx** [comment]
splat is not the correct choice indeed, but did you try other r-r props or the context object?

**Comment by DavidWells** [comment]
I think react router will just give me back the generic `Layout` PhenomicPageContainer component that matches * 

I will take a look at context too but I'm not sure it would know if the page doesn't exist unless I cross reference it with the `window.collection`

I'm imagining a helper function like:

```js
// inside any component up or down the tree
render () {
  const { currentPage } = this.context
  if (is404(currentPage)) {
  // do stuff
  } else if (is_search(currentPage) {
 // do other stuff
 }

}

**Comment by DavidWells** [comment]
I've refactored my main entry point to fix this issue.

Basically, all pages that are real pages run through a shell `DefaultPage` component https://github.com/serverless/site/blob/5932b6c85313e2ebc90bc8ae978ef9a407ffbdf3/src/layouts/Page/index.js and 404 is separated out now.

It might be good to note in the docs about keeping the top most component in your router as something that only renders global items and `this.props.children` https://github.com/serverless/site/blob/5932b6c85313e2ebc90bc8ae978ef9a407ffbdf3/src/app.js#L28  #KeepYourTopLevelComponentAgnostic

Closing this
