### ISSUE TITLE
Update 404 of base theme

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#775]
Ref http://alistapart.com/article/perfect404

**Comment by DavidWells** [comment]
Related: https://github.com/serverless/site/blob/master/src/pages/404/index.js

See our 404 page here https://serverless.com/lolololololol

404 tracking done with serverless AWS APIGateway + lambda +  Dynamo: https://github.com/ServerlessInc/404-tracker

**Comment by MoOx** [comment]
User land thing.
