### ISSUE TITLE
Be able to consume data files

### ISSUE THREAD

**Issue by samjbmason** [MoOx/phenomic#780]
It would be great to create a folder of json/yml files and have them turned into a collection object so that we could arbitrarily loop through the data. 

This may be out of scope for this project but I thought as Jekyll and other static site generators it might be useful to have.

**Comment by MoOx** [comment]
You can already do that. Not straight forward but by consuming json/yml via the phenomic loader (the one used for the md files in the default boilerplate) and [custom loaders plugins](https://phenomic.io/docs/usage/plugins/).
That said, I think we can improve this pretty standard use case by making this more simple.

Maybe data will need to have some standard fields?

**Comment by samjbmason** [comment]
Yeah I think standard fields maybe denoted with `__` prefix, would be good. I can see how this would be implemented now with the current setup, it would be cool to get some official docs though.

**Comment by bloodyowl** [comment]
Going to be fixed with #925
