### ISSUE TITLE
Use more of create-react-app

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#783]
Now that CRA is using a monorepo, we should be able to easily consume (and contribute to!) it.
Looks like a good idea to "standardize" some behaviors. We should be able to remove some similars stuff like utils for formatting errors etc.

I guess @gaearon will find it's a good idea, he probably makes a monorepo for that purpose.

We should also make basically a no boilerplate, with no config by default, and offer an eject feature too.

- [ ] re-open tab thing #724 
- [ ] eject
- [ ] formatting
- [ ] server?
- [ ] babel-preset
- [ ] eslint-config

**Comment by MoOx** [comment]
We can't really reuse eslint config since it "require" a flowtype plugin and I don't want people to have deps they won't probably use (even if they should ^^).
Will need to find a less strict thing than i-am-meticulous.

**Comment by MoOx** [comment]
This issue is too wide. Closing in favor or more small issues.

**Comment by drFabio** [comment]
Sorry to raise the dead issue but does the eject feature every got around? I saw snippets of the discussion but no conclusion

**Comment by MoOx** [comment]
@drFabio per our new architecture, it's not making sense anymore (at least for eject). Configuration is for now very minimal an injected. You can provide your own webpack/babel config and it should just work.
