### ISSUE TITLE
Automatically push "title" property in the <title>

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#784]
Following [a discussion](https://gitter.im/MoOx/phenomic?at=57e9561e00961416551a742a) with @halayli, we think it can be a good idea to automatically handle that in the PageContainer. People will still be able to override it anyway.

Should be very easy to do.

**Comment by nicolas-zozol** [comment]
Be careful with generated title, because for now, if two posts have the same title, the feed collection will forget one.

**Comment by MoOx** [comment]
Not sure to follow you. Collection is not supposed to deduping anything. The purpose of this issue is to automatically push the current page viewed (via PageContainer) to push the title of the current item as the page html title.

If you think you find a bug, please open a new issue with more details.

**Comment by bloodyowl** [comment]
should be in user-land IMO

**Comment by MoOx** [comment]
Yeah we have so much thing to do already.
