### ISSUE TITLE
Feature Request: Support "posts" folders

### ISSUE THREAD

**Issue by motleydev** [MoOx/phenomic#790]
Its a common practice to have a folder per post with relevant asset, additional resources as sibling level content - like a post component if you will. I'd like to see support for that.

**Comment by DavidWells** [comment]
You should be able to do this by altering the build / dev script https://github.com/serverless/site/blob/5932b6c85313e2ebc90bc8ae978ef9a407ffbdf3/scripts/phenomic.browser.js#L15

Merge the 2 folders together before all the rest of the magic happens

I've been doing alot with 'prebuild' npm hook for automatically adding external sources into the /content folder too

**Comment by thangngoc89** [comment]
@motleydev are you talking about something like this ? 

https://github.com/thangngoc89/blog/tree/50a238122d3860454820f7cd6c86e80760a5a95e/content/tang-toc-npm

I have a folder for each posts, `index.md` will be rendered into `index.html` and all images will be copied to dist folder

**Comment by MoOx** [comment]
Closing in favor of #791.
