### ISSUE TITLE
Add support for multiple collection

### ISSUE THREAD

**Issue by motleydev** [MoOx/phenomic#791]
I'd like to be able to define additional directories that get processed into their own collection. Like a gallery folder or something of that nature instead of depending on tags to filter out post types. Like a wordpress taxonomy.

**Comment by MoOx** [comment]
Meanwhile: you can filter by path using a fuction and checking the item send as the first argument ;)

**Comment by MoOx** [comment]
Meanwhile, that can be a start https://github.com/MoOx/phenomic/issues/806

**Comment by bloodyowl** [comment]
Going to be fixed with #925
