### ISSUE TITLE
Question: Why does PageContainer strip url params?

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#792]
I'm trying to do some stuff with URL params for some custom marketing/tracking stuff but it looks like the PageContainer is automagically stripping them before I can parse them.

`PageContainer: replacing by '/framework/docs?lol=hi' to '/framework/docs/'`

https://github.com/MoOx/phenomic/blob/ef97710bc61719143de01615386527856f25f322/src/components/PageContainer/component.js#L77

What's the reason for stripping the URL params here?

Demo: https://phenomic.io/docs/usage/?lol=hi resolves to https://phenomic.io/docs/usage/

I need to grab `utm` params from the URL for some upcoming marketing stuff we are working on =)

**Comment by thangngoc89** [comment]
@DavidWells it looks like a bug to me. It used to replace the hash but I added [this line](https://github.com/MoOx/phenomic/blob/ef97710bc61719143de01615386527856f25f322/src/components/PageContainer/component.js#L69) to prevent that. 

Are you up for a PR?

**Comment by DavidWells** [comment]
@thangngoc89 the expected behavior to not change the URL right?

**Comment by thangngoc89** [comment]
That's right. It should keep url params

**Comment by MoOx** [comment]
It's because of this behavior https://github.com/MoOx/phenomic/blob/6d2c9658bc2e32a53f04dda382c548e1a828b9c6/src/components/PageContainer/component.js#L65-L80
It must be enhanced to skip query strings.

**Comment by MoOx** [comment]
Fixed in 0.17.3
