### ISSUE TITLE
Idea: use webpack.DefinePlugin instead of context for meta

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#793]
Just a thought here.

I've found that is much easier to use `webpack.DefinePlugin` to specify global variables than using react context.

Should we make this the default way people provide meta data? Or perhaps just add into the docs?

https://github.com/MoOx/phenomic/blob/master/themes/phenomic-theme-base/src/components/Header/index.js#L23

Wiring up react context for global information is (not too bad but) sometimes painful.

This was super easy: 
```
  new webpack.DefinePlugin({
        'process.env': { TWITTER: 'awesomeTweets'}
   }),
```

```
{ process.env.TWITTER &&
          <a
            href={ `https://twitter.com/${process.env.TWITTER}` }
            className={ styles.link }
          >
            <Svg svg={ twitterSvg } cleanup />
              { "Twitter" }
          </a>
}
```

Just capturing my thoughts on this. =)

**Comment by DavidWells** [comment]
Just for reference. This is my refactor: https://github.com/serverless/site/commit/5932b6c85313e2ebc90bc8ae978ef9a407ffbdf3

With all global config stuff centralized: https://github.com/serverless/site/blob/5932b6c85313e2ebc90bc8ae978ef9a407ffbdf3/src/_config.js and then added to `webpack.DefinePlugin` https://github.com/serverless/site/commit/5932b6c85313e2ebc90bc8ae978ef9a407ffbdf3#diff-3fe40ded64ba5bb89dcae9266f8dc418R15

**Comment by MoOx** [comment]
No sure if that's a good idea as it only make sense for "small" value, you can't use this for big values.
Anyway, context requirement might be replaced by a simple provider component in the future (with collection refactor)

**Comment by DavidWells** [comment]
Indeed. I actually need to use both in our site. Closing this =)
