### ISSUE TITLE
global-only sass: instructions unclear

### ISSUE THREAD

**Issue by facelesspanda** [MoOx/phenomic#803]
I'm trying to get the 0.17.4 boilerplated theme working with global-only sass-powered styles.

- I installed node-sass and the sass-loader as devDeps,
- I removed every import from style files into JS modules (or at least, those supposed to be CSS modules)
- I changed every `{ style.class }` classname to simple strings
- I commented out the two `.css` and `.global.css` sections and uncommented the "global CSS only" loader object
- I changed the files it's testing to `.scss`, and changed every `.css` file in the `src` tree to `.scss`
- I added the sass-loader to the array.

So in the end here's what my webpack config looks like for styles
```js
        // ! \\
        // If you want global CSS only, just remove the 2 sections above
        // and use the following one
        // ! \\ If you want global CSS for node_modules only, just uncomment
        // this section and the `include` part
        {
          test: /\.scss$/,
          // depending on your need, you might need to scope node_modules
          // for global CSS if you want to keep CSS Modules by default
          // for your own CSS. If so, uncomment the line below
          // include: path.resolve(__dirname, "node_modules"),
          loader: ExtractTextPlugin.extract({
            fallbackLoader: "style-loader",
            loader: [
              "css-loader",
              {
                loader: "postcss-loader",
                query: { "plugins": postcssPlugins },
              },
              "sass-loader"
            ]
          }),
        },
        // ! \\ if you want to use Sass or LESS, you can add sass-loader or
        // less-loader after postcss-loader (or replacing it).
        // ! \\ You will also need to adjust the file extension
        // and to run the following command
        //
        // Sass: `npm install --save-dev node-sass sass-loader`
        // https://github.com/jtangelder/sass-loader
        //
```

What I end up with when running `npm run build` is a built site in `/dist`, without any css file.

I figure it's simply webpack not knowing I want to pack my .scss files. So I gotta tell it.

Adding an entry property in the config object just makes phenomic mad

```
√ ModuleNotFoundError: Module not found: Error: Cannot resolve module '[object Object]' in D:\__DEV__\web\phenomium
    at D:\__DEV__\web\phenomium\node_modules\webpack\lib\Compilation.js:229:38
    at onDoneResolving (D:\__DEV__\web\phenomium\node_modules\webpack\lib\NormalModuleFactory.js:29:20)
    at D:\__DEV__\web\phenomium\node_modules\webpack\lib\NormalModuleFactory.js:114:22
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:726:13
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:52:16
    at done (D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:241:17)
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:44:16
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:723:17
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:167:37
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:52:16
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:361:13
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:52:16
    at done (D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:241:17)
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:44:16
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:358:17
    at D:\__DEV__\web\phenomium\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:24:19 +6.63s
```

so... how do I go about telling phenomic "hey, add these sass files to the build process please"?

```js
// in AppContainer.js
require("./index.global.scss")
```
throws an exception that looks like this:
```
√ ModuleNotFoundError: Module not found: Error: Cannot resolve module '[object Object]' in D:\__DEV__\web\phenomium\src
    at D:\__DEV__\web\phenomium\node_modules\webpack\lib\Compilation.js:229:38
    at onDoneResolving (D:\__DEV__\web\phenomium\node_modules\webpack\lib\NormalModuleFactory.js:29:20)
    at D:\__DEV__\web\phenomium\node_modules\webpack\lib\NormalModuleFactory.js:114:22
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:726:13
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:52:16
    at done (D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:241:17)
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:44:16
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:723:17
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:167:37
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:52:16
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:361:13
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:52:16
    at done (D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:241:17)
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:44:16
    at D:\__DEV__\web\phenomium\node_modules\async\lib\async.js:358:17
    at D:\__DEV__\web\phenomium\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:24:19 +6.96s
```
and `require("index.global")` gives the same error but gets the name right (instead of `[object Object]`)

I'm at a loss with this. Can't add entries, can't require files, I got no way to select my style chunk entry point here, unless I go fiddle with phenomic's calls to webpack?

Working on it [here](https://github.com/facelesspanda/phenomium/tree/feature/sass-support)

**Comment by thangngoc89** [comment]
The answer is simple, it's because you're telling webpack to look in node_modules only 

See these lines https://github.com/facelesspanda/phenomium/blob/53d30b9efb2196ab80a8de32534236d33f125084/webpack.config.babel.js#L202-L204

My blog uses global sass as well, you can use it as an inspiration https://github.com/thangngoc89/blog

**Comment by facelesspanda** [comment]
Gosh I thought `includePaths` was just sass partials... Should've known better.

Will look around your blog to take notes though, I can only learn, at the point I'm at.

Thanks for helping me out

**Comment by thangngoc89** [comment]
@facelesspanda After a close look to the stack trace, this maybe a webpack 2 issues or something.

**Comment by facelesspanda** [comment]
I'm not using webpack 2

That said, if you look at [the default css sections](https://github.com/MoOx/phenomic/blob/master/themes/phenomic-theme-base/webpack.config.babel.js#L129-L134), the call is `ExtractTextPlugin.extract("style-loader"...)`
The [global-only commented section](https://github.com/MoOx/phenomic/blob/master/themes/phenomic-theme-base/webpack.config.babel.js#L162), later, calls `ExtractTextPlugin.extract({"style-loader"...})`

So maybe that? can't test right now.

**Comment by MoOx** [comment]
The global commented section is for webpack 2... Oops.

**Comment by MoOx** [comment]
You need this

```
{
          test: /\.scss$/,
          // depending on your need, you might need to scope node_modules
          // for global CSS if you want to keep CSS Modules by default
          // for your own CSS. If so, uncomment the line below
          // include: path.resolve(__dirname, "node_modules"),
          loader: ExtractTextPlugin.extract(
            "style-loader",
            [
              "css-loader",
              {
                loader: "postcss-loader",
                query: { "plugins": postcssPlugins },
              },
              "sass-loader"
            ].join("!")
          ),
        },
```

**Comment by facelesspanda** [comment]
And here I was thinking I did something wrong :stuck_out_tongue: 
Thanks for the support guys. I'll get back at you when I can do more testing ^^

**Comment by facelesspanda** [comment]
@MoOx your snippet is joining strings and objects.

See this [JSfiddle](https://jsfiddle.net/co1c322g/)

**Comment by thangngoc89** [comment]
Common @MoOx, you're better than this :D 

@facelesspanda I think you can just remove postcss-loader because css-loader have cssnano and auto-prefixer

**Comment by facelesspanda** [comment]
Oh, well, if they do... I'm gonna simply lint styles from atom and rid myself of all these warning stylelint gives me while building :p

Thanks @thangngoc89 !

**Comment by thangngoc89** [comment]
@facelesspanda yeah. stylelint is pretty annoying IMHO
