### ISSUE TITLE
Support Yarn

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#818]
https://github.com/yarnpkg/yarn

Yarn is a faster alternative to the npm client. 
- We should be able to detect when yarn is installed for faster testing (since we do some clean install)
- We should provide command for yarn users (I guess)

**Comment by dflynn15** [comment]
✋ 🙇

**Comment by MoOx** [comment]
This might be super interesting https://github.com/javascriptair/site/blob/master/.travis.yml (we can thanks @kentcdodds)

**Comment by DavidWells** [comment]
Good overview of yarn for folks interested https://laracasts.com/lessons/meet-yarn-your-new-package-manager

**Comment by daaain** [comment]
FYI the current setup process right now fails when using Yarn, see #869. There's a Dockerfile template in the issue for testing if you want.
