### ISSUE TITLE
browserHistory.push("/") don't work as expected

### ISSUE THREAD

**Issue by xuopled** [MoOx/phenomic#821]
My app needed the locale feature so I included `react-intl` to my app.
When I dispatch my `setLocale` action, I need to redirect to my homepage and "refresh" the content because I build my content with `this.store.intl.locale` and it has to update.

So I did

```
import {browserHistory} from "react-router"
...
updateLocale(locale) {
    this.context.store.dispatch(setLocale(locale))
    browserHistory.push("/")
}
```

The url update but the content does not.
With the help of `react-logger` I saw this log : 
`phenomic: PageContainer: replacing by '/' to '/mypage/'`. 
It seems phenomic replace my redirection with my current page.

The workaround is to use `window.location.href = "/"` but there is the uggly "refresh" effect.

Thanks fo your help

**Comment by xuopled** [comment]
I looked into `PageContainer` component but I don't understand the `adjustCurrentUrl` function.

`currentExactPageUrl` has `/` value. It's normal because of my `browserHistory.push("/")`
`itemURL` has the `/mypage/` value. So my `Phenomic` replace my new url by my old url.

I don't really know how to fix that

**Comment by thangngoc89** [comment]
@xuopled could you try `import  { browserHistory } from "phenomic/lib/client"` ?

**Comment by xuopled** [comment]
@thangngoc89, it works :D thank you very much

**Comment by MoOx** [comment]
Reopening as it will require some docs

**Comment by xuopled** [comment]
@MoOx In wich section do you want the documentation about this ?

**Comment by MoOx** [comment]
In docs/usage/routing/ ?
