### ISSUE TITLE
UX improvement: Even FASTER Page Loading

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#824]
Right now we have the [generic loading component](https://github.com/MoOx/phenomic/blob/36b03832dde5cf3a11d1b3480f15935172697060/src/components/PageContainer/component.js#L228) which is good but I was thinking about ways to make loading appear even faster for visitors.

Facebook loads the layout with phony loading state text. Example:

![image](https://cloud.githubusercontent.com/assets/532272/19334369/46e7a1ca-90b0-11e6-9d93-e34ee50ea856.png)

The effect makes the pages feel like they are loading faster to the user

**So the idea here is:**

If you build your layout components with default loading states, we could basically show the layout instantly when a link is clicked.
1. Visitor clicks link
2. Layout XYZ with prop `phenomicLoading={true}` (or something) renders instead of default generic `<PageLoading>` component
3. After `xyz.json` data is finished fetching & loads, the real layout component just refreshes with the content
4. Visitor is flipping amazed at how fast this site is

While this doesn't technically speed up anything, the perceived site performance would be much faster.

**What do you think?**

Possible implementation: 

We could check [here](https://github.com/MoOx/phenomic/blob/36b03832dde5cf3a11d1b3480f15935172697060/src/components/PageContainer/component.js#L228) is the requested Layout has the reserved `phenomicLoading` propType defined and if so, use it as loading component. If `phenomicLoading` propType is not defined use the default generic `<PageLoading>` component

B/c this would require some work/logic in layouts, this would of course be optional and not required if people just want a generic loading state component as it works now.

Related: https://github.com/MoOx/phenomic/issues/587

**Comment by MoOx** [comment]
My idea is to simplify the API.
So we can easily remove the PageLoading concept in phenomic and let user handle this via a props like you said.
That's the idea I mentionned here https://github.com/MoOx/phenomic/issues/587#issuecomment-250118023

Maybe we should close this and rename #587 ? (or the opposite)

**Comment by MoOx** [comment]
We can call this "optimistic Layout rendering" :D

**Comment by MoOx** [comment]
The way to go https://gitter.im/MoOx/phenomic?at=580715ee5636a5602eef21e1

> We should just change those lines https://github.com/MoOx/phenomic/blob/e6eaf3fbe75a688c81ce7ec475b54c5b5ed66f16/src/components/PageContainer/component.js#L233-L251
that might involves some others change like removing page error/loading from phenomic pagecontainers props and leave it to the user (via props error/loading, so people can do whatever they want in the layout depending on those flags)

**Comment by DavidWells** [comment]
I did it!!!!

http://www.screencast.com/t/Ym1KVwFP

The code is here: https://github.com/MoOx/phenomic/blob/b10beee37b1d02e29c88284f6bfe872d98eba3b4/src/components/PageContainer/component.js

I think keeping the default loader might be nice for some people (including myself when I am lazy)

The PR isn't done yet, I will probably need help with the Flow stuff =P

Let me know what you think. I think this will make phenomic sites even faster =)

**Comment by DavidWells** [comment]
Demo here: http://holy-shit-thats-fast.surge.sh/

Going to /blog and clicking into the different posts will show you the loading states (no design effort added to them yet =P).

**Comment by mistadikay** [comment]
It could be a huge improvement since it will make possible to keep Layout mounted between page tansitions and resolve #587. I checked your branch @DavidWells and it works for me. 👍  Looking forward to see it merged.

**Comment by DavidWells** [comment]
Demo loading state:

![loading-state](https://cloud.githubusercontent.com/assets/532272/19630866/9793f07a-9947-11e6-919a-ba2d81ebcf68.gif)

This is a component I made to simulate text loading. Will be released soon in the serverless/site/src/components =)

**Comment by DavidWells** [comment]
One last tweak made to the PR to pass in the additional page meta found in the window.collection.

Now the custom loading states can display the title instantly as well.

http://www.screencast.com/t/2gD2kvktZqFr

**Comment by MoOx** [comment]
@DavidWells Is your loading animation available somewhere?
Also here is a new PR https://github.com/MoOx/phenomic/pull/855 that includes your work ;)

**Comment by DavidWells** [comment]
This is my loading component 

https://github.com/serverless/site/tree/master/src/components/ContentLoading

Feel free to use it :)

**Comment by thangngoc89** [comment]
@DavidWells This is fantastic. Thank you @DavidWells
