### ISSUE TITLE
Missing dependencies for postinstall and setup

### ISSUE THREAD

**Issue by levito** [MoOx/phenomic#833]
Since v0.17.9, running `npm install phenomic` doesn't install all required dependencies for postinstall. 

Missing modules for postinstall:
- babel-cli
- babel-plugin-flow-react-proptypes
- babel-preset-latest
- babel-preset-stage-1
- babel-preset-react

After setup, `phenomic` itself is missing from generated `package.json`.

**Comment by MoOx** [comment]
Will take a look when I get some times. Meanwhile, you can probably use 0.17.8, do the setup, then upgrade to 0.17.9. Sorry for the mess.

**Comment by MoOx** [comment]
This was a stupid error, sorry for this. Releasing 0.17.10 now :)
