### ISSUE TITLE
package.json generated by phenomic setup not populated

### ISSUE THREAD

**Issue by levito** [MoOx/phenomic#835]
This is a strange issue: After running phenomic setup, the generated `package.json` seems to be just copied, not populated with the user entries.

However, if I look into [src/bin/commands/setup/index.js#L43](https://github.com/MoOx/phenomic/blob/master/src/bin/commands/setup/index.js#L43), `pkg` looks fine. And renaming `package.json` to sth. else writes the file like expected. Any idea what's going on? I'm using node v6.9.1.

Btw. phenomic itself is still missing from the package.json template.

**Comment by MoOx** [comment]
Thanks for reporting this. I pushed a quick fix (0.17.11) and will add a regression test to avoid that regression in the future.
