### ISSUE TITLE
Lambda for phenomic?

### ISSUE THREAD

**Issue by sammkj** [MoOx/phenomic#842]
Hello there, I recently started to use phenomic to create my company's landing and support sites. Lovng it so far! But I'm facing a problem in deployment. The sites are generated based some data from my server. And I need to regenerate the sites when some data change. I thought of using lambda to do that but I don't have experience with it at all. How would you go about that?

**Comment by facelesspanda** [comment]
I'm wondering why you're going about building a static site for dynamic data. Wouldn't a normal react webapp be preferable?
Or are your data changes rare enough to call it "static"? In which case I don't think the overhead of manually re-deploying the website is overwhelming.

**Comment by sammkj** [comment]
@facelesspanda I have a CMS for the support site whereby admins can edit and save questions and answers. So every time they make changes to these Q&As, the site has to be updated. I think a react app will be overkill for this. Having a server to just to serve static support site doesn't seem like a good idea either.

**Comment by DavidWells** [comment]
@sammkj see: https://github.com/netlify/netlify-cms for a CMS layer

**Comment by sammkj** [comment]
@DavidWells , thanks for the suggestion. I previously investigated Netlify already. Quick question, is serverless's blog using netlify?

**Comment by DavidWells** [comment]
@sammkj yep. The entire site is on netlify. You can see the src here https://github.com/serverless/site

We dynamically pull in the blog on build from https://github.com/serverless/blog

**Comment by DavidWells** [comment]
You can trigger netlify rebuilds with webhooks.

So you can trigger the netlify rebuild webhook when your source of data changes.

You can use the AWS lambda Cron to run your "check data src and trigger site rebuild if data changed" function.

Check out this tutorial on how to setup lambda Cron jobs https://parall.ax/blog/view/3202/tutorial-serverless-scheduled-tasks



- David Wells

**Comment by sammkj** [comment]
After a day of back and forth with my team, we decided to use lambda to build our static support and landing sites since we already have a built-in CMS in our company dashboard. 

@DavidWells , @facelesspanda ,thank you all for your suggestions!
