### ISSUE TITLE
Bug: Html in markdown causes invarient

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#843]
On https://serverless.com/framework/docs/ we are using normal HTML in the markdown. (ref: https://raw.githubusercontent.com/serverless/serverless/master/docs/README.md)

This is causing a react Invariant Violation and breaking divs lower in the page

"Uncaught Invariant Violation: Minified React error #32; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=32&args[]=110 for the full message or use the non-minified dev environment for full errors and additional helpful warnings."

When I remove the custom HTML from the page the error goes away.

Note: this only occurs when the https://serverless.com/framework/docs/ is hard reloaded. It works fine from react-router <Link>s

![image](https://cloud.githubusercontent.com/assets/532272/19675925/025ffc42-9a46-11e6-8527-df0b13b3f9a2.png)

Is there a way to update the markdown parser to handle custom html in the markdown or should I hardcode this page in another layout component?

**Comment by MoOx** [comment]
Currently we can see a huge difference from address bar access or router access:

- the fresh view have a weird whitespace at the bottom
- the router access offer a "correct" render.

So I imagine that the inlined html produce incorrect dom. Maybe div inside p or something like that?

That's probably related to the way the markdown parser/stringifier read and output the html (maybe invalid html, correctly adjusted without warning during client side navigation?)

I advice you to compare html string (the file served) with dom to html string (generated dom rendered as a string). I bet you will find a huge difference in the tree (I already got this kind of issues in the past).

We might need to adjust the html generated by the loader :/

**Comment by DavidWells** [comment]
Welp it was a non closing `<div>` issue...

Sorry about that.

It might be interesting to think about validating `.md` content to detect any malformed HTML when `phenomic start` runs and throw an error until it's fixed =)

**Comment by MoOx** [comment]
That will be nice if we find a way to automate this detection somehow. I tested your html it looked fine from a linter :/

**Comment by DavidWells** [comment]
it was this lil bastard: https://github.com/serverless/serverless/pull/2540/files#diff-e70100059cc3a7376740bbe9751a082eR94

**Comment by MoOx** [comment]
Hum it's not really a div then. That's exactly the same issue I got. Pretty weird this does not render correctly. I would like to find the thing that does not understand `<img> ` like they should.

**Comment by MoOx** [comment]
Probably not relevant anymore with v1 as we transform markdown to a json tree.
