### ISSUE TITLE
How is Homepage loaded at root?

### ISSUE THREAD

**Issue by indiesquidge** [MoOx/phenomic#844]
Playing around in the source files, I'm a bit confused as to how the application knows to render the `Homepage` layout at the root. The default routing looks like this

```jsx
export default (
  <Route component={ AppContainer }>
    <Route path="*" component={ PageContainer } />
  </Route>
)
```

But I am having trouble understanding how it knows to render the `Homepage` component.

If I add my own component for a specific path like this

```jsx
import Home from './components/Home'

// ...

export default (
  <Route component={ AppContainer }>
    <Route path="/" component={ Home } />
    <Route path="*" component={ PageContainer } />
  </Route>
)
```

Then the root page loads that component, as expected, and the children of `<Content>` makes sense
<img width="1139" alt="screen shot 2016-10-25 at 12 59 08 pm" src="https://cloud.githubusercontent.com/assets/3409645/19702066/ed6009d2-9ab2-11e6-9342-72e0cd8279ae.png">

But removing my custom route (i.e., leaving the app as it comes by default) loads `Homepage` and the children of `<Content>` makes less sense
<img width="1139" alt="screen shot 2016-10-25 at 12 58 26 pm" src="https://cloud.githubusercontent.com/assets/3409645/19702121/173160d0-9ab3-11e6-920d-36b71c1dccb6.png">

If I could just get some help understanding what's happening here I would greatly appreciate it! 💛

**Comment by MoOx** [comment]
The (your)PageContainer/Connect(PageContainer)/(Phenomic)PageContainer thing is just the Phenomic part that handle the path="*". This component handle click in markdown & load proper json when require. It also takes care of the loading component & error pages.

The base theme have a index.md that contains a "layout" metadata that is "Homepage". https://github.com/MoOx/phenomic/blob/55093695f4e70177031bcf914f8d54c83cef9e70/themes/phenomic-theme-base/content/index.md

That's supposed to be explained here:

- https://phenomic.io/docs/getting-started/#how-can-i-use-a-custom-layout-for-my-page
- https://phenomic.io/docs/usage/layouts/

**Comment by indiesquidge** [comment]
Ah, perfect, I see now. Thank you!
