### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by tscanlin** [MoOx/phenomic#848]
I was curious if there is currently a recommended way of updating when new versions of phenomic come out? I searched the docs and tried searching open issues. Let me know if you have given this any thought.

**Comment by MoOx** [comment]
The recommended way is pretty simple: read [releases notes](https://github.com/MoOx/phenomic/blob/master/CHANGELOG.md).
The thing your should consider are:
- Breaking changes: you might need to change some code
- Change in base theme: you might want to incorporate some changes too.

Just to let you know, we plan to add way to reduce the boilerplate and provide even more solid defaults in the future so config will be minimal, like create-react-app or next.js.

**Comment by MoOx** [comment]
@tscanlin do you need more information on that? It looks like a standard way to update dependency but maybe I am not considering everything I should?

**Comment by tscanlin** [comment]
No, that should work fine. Maybe after v1 there could be a way to try and install the new version locally and transfer files to the new dir to make sure it compiles properly, but let's cross that path when we get to it. Closing for now, thanks.
