### ISSUE TITLE
Idea: Replace Helmet with <Head>

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#850]
Was toying around with next.js and it looks like they have some pretty nice components built out.

Their `<Head>` component is 9000 times easier to use than react `<Helmet>` https://github.com/zeit/next.js/blob/master/lib/head.js

It mimics raw html instead of weird config arrays like Helmet

```
// this just works like normal html... pretty cool!
<Head>
      <title>My page title</title>
      <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      <script>
        console.log('hi')
      </script>
</Head>
```

**Comment by MoOx** [comment]
I like this idea. Is there a way to make a proxy? (like phenomic/lib/head => next/head or something like this?)
Btw, curious how they handle next/head to be head/dist/lib/head.js

**Comment by DavidWells** [comment]
I will look.

The flat directory structure is achieved by publishing flat modules. The trick there is moving the projects package.json file into the built /lib's folder and `npm publishing` from there. (at least thats how I do it)

**Comment by DavidWells** [comment]
actually nvm. They have `"main": "./dist/lib/index.js",` in their package (which doesn't seem to exist)

![image](https://cloud.githubusercontent.com/assets/532272/19821116/89bcde08-9d11-11e6-981e-081253596c42.png)

So not sure how that works heh.

But I have published flat packages with my method =P. `npm version patch` runs through my method below:

```
  "scripts": {
    "preversion": "npm run build",
    "postversion": "git push && git push --tags && npm run dist",
    "predist": "cp -rf package.json lib",
    "dist": "cd lib && npm publish && echo 'New Version Deployed to NPM!'"
  }
```

This makes the `npm publish` command run from my built output folder inside of my project root

**Comment by MoOx** [comment]
@DavidWells you are going to be very happy with new helmet api https://github.com/nfl/react-helmet

**Comment by MoOx** [comment]
helmet v5 is just like next/head api
