### ISSUE TITLE
Add config to configure routes for blog posts

### ISSUE THREAD

**Issue by mdotasia** [MoOx/phenomic#856]
At the moment blog posts are routed using Phenomic's default route. Example: file `blog/bla-bla-post.md` results in URL `blog/bla-bla-post/`. It would be great to have a config that allows tweaking this to get more blog like URLs like this: `blog/2016/10/31/title-of-bla-bla-post/`.

**Comment by MoOx** [comment]
I plan to support this. We should extract date and transform this into params (year, month, date) and allow people to use those param in router directly.

We may start by adding a custom code for date extraction here https://github.com/MoOx/phenomic/blob/88d73fd3ba2b27f00fbefbe93cd78c6d4df03e68/src/static/routes-to-urls/index.js#L29

**Comment by MoOx** [comment]
Closing in favor of #700. We will create key from date that will allow you to use :year, :month, :day in react router routes definition, should be enough.
