### ISSUE TITLE
Rewrite internal links

### ISSUE THREAD

**Issue by mdotasia** [MoOx/phenomic#857]
At them moment when linking to another generated page, you need to know the rendered URL. It would be great to rewrite linked URLs to the rendered URL. Example: to link from one post to another without knowing that posts URL I might just use this Markdown link:

```
[Link to another post](./another-post.md)
```

and then Phenomic replaces it with the actual link.

**Comment by MoOx** [comment]
This is an pretty good idea and should not be that hard. We should implement this using a custom remark plugin.

**Comment by MoOx** [comment]
Probably not relevant anymore with v1 (you can do whatever you want during rendering as your markdown become a json object)
