### ISSUE TITLE
Allows possibility of disabling desktop notification

### ISSUE THREAD

**Issue by ScreamZ** [MoOx/phenomic#859]
As I asked on gitter, can we expect a configuration option or something like that, that disable desktop notification ?

Thanks

**Comment by DavidWells** [comment]
I second this. I would rather not see the growl notice and just rely on the console :)

Having a disable option would be nice. Or having this off by default (and turned on by an option) might be good. Maybe a poll would be good to see what folks prefer

**Comment by MoOx** [comment]
We can just remove this and tell people to use the plugin themselves.
Should consist of removing the following things:

- https://github.com/MoOx/phenomic/blob/7ee247618f23d126d81a0b523f810f81eff79b7d/package.json#L83
- https://github.com/MoOx/phenomic/blob/e6eaf3fbe75a688c81ce7ec475b54c5b5ed66f16/src/builder/server.js#L8
- https://github.com/MoOx/phenomic/blob/e6eaf3fbe75a688c81ce7ec475b54c5b5ed66f16/src/builder/server.js#L72

Maybe we can add instead a "notify" option (disable by default) that add a custom notification (not just a "webpack" notification) when build is ready during dev, and also when the entire static generation is made. We can do this in 2 steps :)

So feel free to make a PR to remove as a first step :)

**Comment by ScreamZ** [comment]
Thanks buddy
