### ISSUE TITLE
Uncaught TypeError: filters[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by lapidus** [MoOx/phenomic#860]
Row 111 in enhance-collection/index.js:
`for (var _iterator = filters[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
`
Gives me this error on iPhone: 
> Uncaught TypeError: filters[Symbol.iterator] is not a function

Any clue what that could be?

**Comment by MoOx** [comment]
What version of node are you using please?

**Comment by MoOx** [comment]
Oh my bad, it looks like a browser issue.

**Comment by MoOx** [comment]
Can you give use more detail about the snippet causing this (your code, not phenomic code)

**Comment by lapidus** [comment]
When logging I get this:
 console.log("filters", filters, filters[Symbol.iterator])
![image](https://cloud.githubusercontent.com/assets/66601/19904769/58311514-a074-11e6-905a-4a07fcf475e8.png)

**Comment by MoOx** [comment]
Can you give me:

- iphone/ios version
- your snippet using enhanceCollection

Can you try to ``import "babel-polyfill"`` in top of you `scripts/phenomic.browser.js`` to see if this solve the issue?

**Comment by lapidus** [comment]
The Symbol Iterator itself looks a bit odd to me? 
![image](https://cloud.githubusercontent.com/assets/66601/19904856/b17f0018-a074-11e6-8bee-2f77a36f1d56.png)

**Comment by MoOx** [comment]
This is the result of babel transpiled code, so don't try to debug this.

Please answer my previous questions.

**Comment by lapidus** [comment]
iphone/ios version = 5+6
your snippet using enhanceCollection = 

 const latestProjects = enhanceCollection(context.collection, {
      filter: { featured: "frontpage", layout: "Project" },
      sort: "order",
      reverse: false,
    })
    .slice(0, numberOfLatestProjects)

    const pageData = enhanceCollection(context.collection, {
      filter: { layout: "Homepage" },
    })[0]

**Comment by MoOx** [comment]
ios6, okkkk. So please try adding babel-poyfill like I said, should fix your issue. Your browser is pretty old.

**Comment by lapidus** [comment]
Hm, didn't work. Let me try to do some more debugging before taking your valuable time! Thanks!

**Comment by MoOx** [comment]
Any update on this?

**Comment by lapidus** [comment]
Nope, sorry, took a break from it. But I will try again (maybe with an updated version of Phenomic) as I need to try to get this site live soon :) Will post again here asap. Likely the weekend.
