### ISSUE TITLE
Add Support for Glamor / Aphrodite (CSS-in-JS)

### ISSUE THREAD

**Issue by AWebOfBrown** [MoOx/phenomic#864]
Currently, glamor (and im guessing aphrodite) styles aren't rendered by Phenomic in the build process.

**Comment by MoOx** [comment]
We will need to find a way to detect when this libs are used (maybe just trying to require those?) and adjust the rendering method automatically by handling this requirements:

- https://github.com/threepointone/glamor/blob/master/docs/server.md
- https://github.com/Khan/aphrodite#server-side-rendering

Or alternatively, we can offer user a way to handle global html generation, like requested in #826 (but I guess we can do both, plug and play is what I want at the end)

**Comment by AWebOfBrown** [comment]
@MoOx 

Hi Moox. I think i fixed an issue with my site's homepage address and it is rendering glamor styles correctly now. 

The only slight problem is the flash of unstyled content while it loads the styles. I'm not super experienced but I assume the fix is to make sure these are being rendered in the document <head> somehow?

**Comment by MoOx** [comment]
> The only slight problem is the flash of unstyled content while it loads the styles. I'm not super experienced but I assume the fix is to make sure these are being rendered in the document somehow? 

Exactly, we need to implement this. Should be pretty easy to do.

I guess detection of glamor/aphrodite can be made using a simple try catch :)

**Comment by AWebOfBrown** [comment]
Ahh okay, at first my issue was the Glamor styles not loading at all (which was my fault, not Phenomics) so I thought I had misrepresented the issue. Glad we're on the same page.

**Comment by MoOx** [comment]
@mxstbr is there any similar requirement for styled-components (for static rendering as css)?

**Comment by mxstbr** [comment]
Absolutely none, you can use CSS just as-is! Would love for you to try it and let me know how it goes, I haven't done your use case yet so it might break?

**Comment by MoOx** [comment]
@mxstbr I see there is an open issue about that https://github.com/styled-components/styled-components/issues/124 and I understand from the very first lines that you use Glamor under the hood, so I guess adding support from glamor ssr will make it work for styled-components as well.
The idea is to be able to pre-render styles as CSS so pages work without JavaScript.
