### ISSUE TITLE
Errors logs after clean install of version 0.18.0

### ISSUE THREAD

**Issue by caillou** [MoOx/phenomic#868]
I just tried to set up a new project with version 0.18.0. After going through the [setup instructions](https://phenomic.io/docs/setup/), I get the following error logs in the browser when navigating to http://localhost:3334/ :

```
Warning: Failed prop type: Page: prop type `isLoading` is invalid; it must be a function, usually from React.PropTypes.
Warning: Failed prop type: Required prop `__filename` was not specified in `Page`.
Warning: Failed prop type: Required prop `__url` was not specified in `Page`.
```

**Comment by iamvlado** [comment]
I also noticed this problem on an existing project after updating Phenomic

**Comment by MoOx** [comment]
Thanks for reporting this. I have faced this small warnings as well. I updated some files too quickly, hard to cover this with automated testing :) (doable but tedious).
Will fix this asap.

**Comment by MoOx** [comment]
FYI it only happen for new projects or for projects using the new way to load pages.

You basically need to update your layouts that use this propTypes definitions:

![image](https://cloud.githubusercontent.com/assets/157534/20089668/ce8635f0-a588-11e6-90b5-5f415c764460.png)
