### ISSUE TITLE
Plugins don't work. TypeError: plugin is not a function

### ISSUE THREAD

**Issue by MrToph** [MoOx/phenomic#871]
I tried to create a custom plugin as described [here](https://phenomic.io/docs/usage/plugins/), but as soon as I change the plugins to use `[...require("phenomic/lib/loader-preset-default").default]`, I get a `Module build failed: TypeError: plugin is not a function` build error.

I digged around a bit and found out that using any functions in `plugins` doesn't work, they get replaced by `null`s. It's not an import error, as the type error happens even when I don't require anything and just hardcode a function there:
```js
loaders: [
   // webpack 2
   // rules: [
     {
       test: /\.(md|markdown)$/,
       loader: phenomicLoader,
       query: {
          context: path.join(config.cwd, config.source),
          plugins: [id => id]
```

In [phenomicLoader](https://github.com/MoOx/phenomic/blob/master/src/loader/index.js#L22) `webpackInstance.query` is an array of `null`s, whereas numbers/strings in webpack.config's plugins are correctly received.
So what's the issue with putting functions there?

**Comment by MoOx** [comment]
My bad on this. The current documentation is for webpack 2 and webpack 1 does not accept anything that can't be converted to JSON in query. 

With webpack 1, you actually need to pass what you pass as a ``query`` in a global object in webpack config (like for postcss for example, at the same level of webpack ``module``)

```js

// ...

export default (config = {}) => {
  // ..
  return {
    phenomic: {
      context: path.join(__dirname, config.source),
      plugins: [
        ...require("phenomic/lib/loader-preset-markdown").default
      ]
    },
    module: {
      loaders: [
        // *.md => consumed via phenomic special webpack loader
        // allow to generate collection and rss feed.
        {
          // phenomic requirement
          test: /\.(md|markdown)$/,
          loader: phenomicLoader,
      },
```

I will fix the doc and base theme.

**Comment by MrToph** [comment]
Thanks, glad it's just a documentation mistake.
It works when I put the context into the query instead of phenomic:
```js
// ...

export default (config = {}) => {
  // ..
  return {
    phenomic: {
      plugins: [
        ...require("phenomic/lib/loader-preset-markdown").default
      ]
    },
    module: {
      loaders: [
        // *.md => consumed via phenomic special webpack loader
        // allow to generate collection and rss feed.
        {
          // phenomic requirement
          test: /\.(md|markdown)$/,
          loader: phenomicLoader,
          query: {
            context: path.join(__dirname, config.source),
          },
      },
```

**Comment by MoOx** [comment]
Reopening as it needs docs.
