### ISSUE TITLE
Generate purely static website

### ISSUE THREAD

**Issue by gmarty** [MoOx/phenomic#874]
It doesn't seem to be possible to generate purely static websites (that is without JS, only plain HTML and assets).
At the very least that'd be nice to have an option not to get the bundled JavaScript in the HTML files.

**Comment by MoOx** [comment]
[Next release](https://github.com/MoOx/phenomic/pull/876) will have a "clientScripts" option (boolean, true by default) to control the output of the javascript inserted in html files.
By turning this off (clientScripts: false in package.json phenomic section or --no-client-scripts in package.json script section), you should turn Phenomic into a standard static website generator.

**Comment by gmarty** [comment]
👍  That was fast!
I can't wait for the next version to be released.

**Comment by gmarty** [comment]
As a followup, I think it makes sense to call `ReactDOMServer.renderToStaticMarkup()` instead of `ReactDOMServer.renderToString()` when in purely static mode as React additional attributes and tags are not used:
https://github.com/MoOx/phenomic/blob/e6eaf3fbe75a688c81ce7ec475b54c5b5ed66f16/src/static/to-html/url-as-html.js#L43-L47

**Comment by MoOx** [comment]
I already took care of that in 233b0ef ;)

**Comment by gmarty** [comment]
Oh! As I said, fast! 👍 👍 ;-)

**Comment by DavidWells** [comment]
@gmarty Just out of curiosity. What is the use case for purely static sites with no-js?

**Comment by dab** [comment]
@DavidWells you can use `w3m` to browse it

**Comment by MoOx** [comment]
You can already do that. Removing the JS only remove the client side enhancement. Phenomic works without JS out of the box.
