### ISSUE TITLE
Lint markdown in boilerplate with remark-lint

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#88]

**Comment by thangngoc89** [comment]
Some tools:

- https://github.com/DavidAnson/markdownlint
- https://github.com/wooorm/remark-lint (cli avaliable)

**Comment by thangngoc89** [comment]
This should be easy now since we are using remark as default markdown engine

**Comment by MoOx** [comment]
Boilerplate/base theme will be gone in 1.0 and the example will be minimalistic.
