### ISSUE TITLE
Need to have whole content in props.head instead of excerpt

### ISSUE THREAD

**Issue by dab** [MoOx/phenomic#881]
Hello here. Building a website with a lot of different content blocks. Was planning to implement separate markdowns for different page regions.
But if I using collections - I can get only short excerpt, there are no content fields inside the collection.

As I understand I need to dig inside https://phenomic.io/docs/usage/plugins/

Any suggestions or examples?

**Comment by MoOx** [comment]
By default indeed, collection does not contain all content, it contain only front-matter data in head, body is skipped and only available when the current page is viewed.
This will change in next major release with a new collection API
Meanwhile, you probably need to add a custom plugin to adjust data passed on head indeed.
