### ISSUE TITLE
Footer / header dynamic content (+ internal links)

### ISSUE THREAD

**Issue by daaain** [MoOx/phenomic#882]
I couldn't find any discussion around this, so thought worth asking!

What's the recommended / best way to make content in the header and footer dynamic / editable?

My current approach is to farm these out to a JSON file which is then wired up as settings page in Netlify CMS and loaded as a `metadata` field in Phenomic. In the header I generate navigation links with a `.map` loop and in the footer I inject the content as `dangerouslySetInnerHTML`.

This works quite well, but with one big caveat: in the footer text the internal links are not caught, so trigger a full page reload. I saw that you did some work on it, but only for Markdown?

My concrete use case is having a Legal page and linking to it from the footer (as well as to an external privacy policy, etc so would like to keep it user editable).

So maybe the easiest would be if I could run the content through the Markdown parser? I'm sure there's something already to make this happen with very little code, but not sure where to look...

**Comment by thangngoc89** [comment]
@daaain if it's in footer, use `<Link>` component from `react-router` instead of an `<a>` tag

**Comment by daaain** [comment]
@thangngoc89 the content comes from JSON, I just tried and the `<Link>` component wasn't rendered by React, it just became `<link>` in the DOM. Is there a way to render a text fragment as React?

**Comment by thangngoc89** [comment]
@daaain don't write HTML in JSON, try to make a list and use React to render that list

**Comment by daaain** [comment]
I have a list for social icons, but also need to put a sentence each (with
links in line) about privacy policy and legal notices.

**Comment by thangngoc89** [comment]
@daaain as I said, try to make a list from that and render it with React,

**Comment by daaain** [comment]
Ah, so you mean by wrapping each list item into a `Link` in React?

The way they are right now is that only certain words are linked, see below. To make things more complicated one will be internal and the other one an external link where I also need to have a class so their script can transform it into a button runtime.

```json
"footer_notices": "For company information and other legal bits, see our <a href=\"/legal\" title=\"legal page\">legal page</a>.<br/>We’re using cookies, hope that’s cool. Here’s our <a href=\"//www.iubenda.com/privacy-policy/xxxxxx\" class=\"iubenda-white iubenda-embed\" title=\"Privacy Policy\">Privacy Policy</a>."
```

So this is why I was thinking that maybe the best would be if there was a way to let the Markdown parser take care of it, if it's not only for body content?

**Comment by MoOx** [comment]
Indeed, we are doing something in the PageContainer, so all content displayed with it will catch links, but it's not super safe this way. We plan to convert text rendered to real react components.

I don't see a super easy solution atm with your requirements in mind (being able to edit that from netlify). You should use a custom text syntax on make some replacements when you render the footer.

**Comment by MoOx** [comment]
Probably not relevant anymore with v1.
