### ISSUE TITLE
Hide warnings about glamor and aphrodite

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#890]
Since we added support for glamor and aphordite, build might output things like this

```
✔ Warning: %s Module not found: Error: Cannot resolve module 'glamor/server' in /.../node_modules/phenomic/lib/components/Html +9.82s
✔ Warning: %s Module not found: Error: Cannot resolve module 'aphrodite' in /.../node_modules/phenomic/lib/components/Html
```

**Comment by bloodyowl** [comment]
Going to be fixed with #925 (moving to user-land)

**Comment by MoOx** [comment]
Are you sure we cannot handle this? It's not very a big deal and it could be nice to have this kind of thing working out of the box. Maybe a plugin?

**Comment by MoOx** [comment]
Probably not relevant anymore with v1. We might add plugins for this.
