### ISSUE TITLE
Netlify CMS instructions

### ISSUE THREAD

**Issue by brianrc** [MoOx/phenomic#891]
I tried following the directions on the website for adding Netlify CMS, but ran into trouble.
https://phenomic.io/docs/usage/cms/netlify/

It says:
`Note: PHENOMIC_SOURCE & ASSETS_FOLDER are configurable in your package.json`

but I couldn't find those variables set anywhere. Ended up just hard-coding in content/assets .

That got the Netlify CMS to finally load, but when I tried creating a new post, it would just hang and nothing new would show up in my github repository.

Other things were unclear in the instructions. It says to add the following, but there were other things listed under plugins. Does order matter? I just put it at the bottom.
```
plugins: [
    new CopyWebpackPlugin([
      {from: 'admin', to: 'admin'},
    ]),
  ]
```

Under "Netlify configuration," for creating a "new developer application" I did that under "Developer settings" -> "OAuth applications." I think that's right, but it should probably be said explicitly. 

Thanks for all you do.

**Comment by daaain** [comment]
It's a bit of a trial and error and Netlify CMS is a moving target...

I think the only thing you miss is adding a `layout` property so it gets written into the new post's YAML front matter:

```
- {label: "Layout", name: "layout", widget: "string", default: "Post"}
```

But have a look at this, I have a repo where I'm experimenting with it:
https://github.com/daaain/phenomic-netlify-CMS-test/blob/master/admin/config.yml

**Comment by brianrc** [comment]
Hmm. Thanks. I added that in, but Netlify still isn't updating my repo. :/

**Comment by MoOx** [comment]
@xuopled any idea?

**Comment by MoOx** [comment]
@brianrc 

>  Note: PHENOMIC_SOURCE & ASSETS_FOLDER are configurable in your package.json

Those are actual values to replace by hand, sorry if doc is not clear.

**Comment by xuopled** [comment]
In your `package.json` (https://phenomic.io/docs/usage/configuration/core/), that is the equivalent : 

```
"phenomic": {
   "source": PHENOMIC_SOURCE
   "assets": ASSETS_FOLDER,
}
```

**Comment by brianrc** [comment]
Ok, well the default install doesn't have those values set which is why it's confusing. All I see in package.json is:
```
  "phenomic": {
    "CNAME": false
  },
```
Maybe have the instructions say to add those would help. Thanks all!

**Comment by xuopled** [comment]
Thank you we will add instructions for this

**Comment by brianrc** [comment]
Also, I opened a ticket on Netlify CMS. 
https://github.com/netlify/netlify-cms/issues/171
