### ISSUE TITLE
Provides flow interfaces + add flow annotations in base theme + setup question to strip those 

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#896]
Will be a good idea to provides our flow interfaces.
Base theme can have annotation by default that we can strip during the setup using https://babeljs.io/docs/plugins/transform-flow-strip-types/ if people don't want to use flow

That might be interesting https://medium.com/@ryyppy/shipping-flowtype-definitions-in-npm-packages-c987917efb65#.oo98khhsd

**Comment by montogeek** [comment]
@MoOx I could do this :)

**Comment by MoOx** [comment]
Yes please!

**Comment by montogeek** [comment]
Say no more!

**Comment by MoOx** [comment]
Probably not relevant anymore with v1.
