### ISSUE TITLE
offline-plugin v4 release

### ISSUE THREAD

**Issue by NekR** [MoOx/phenomic#905]
@MoOx hey! I recently released `v4` of `offline-plugin`. Would you like to update to it or you are comfortable with you custom branch?

**Comment by MoOx** [comment]
We should definitely update it! Do you want to help us on that?

**Comment by NekR** [comment]
Yeah, of course, I'll do the PR.

**Comment by NekR** [comment]
@MoOx Sorry, I'm holding a bit with this because there potentially could be some problems with the last release of `offline-plugin`. Trying to investigate and figure out what might wrong. If you are interested, here is the issue: https://github.com/NekR/offline-plugin/issues/142

**Comment by NekR** [comment]
@MoOx I'm ready to do the PR. What's the correct branch for it?

**Comment by MoOx** [comment]
Please use master as it's the only stable branch. I will make any necessary change on next!
