### ISSUE TITLE
devtool sourcemap configured for node config, but not used?

### ISSUE THREAD

**Issue by arlair** [MoOx/phenomic#906]
I am trying to get source maps for a static build.

The config is defaulted as expected [here](https://github.com/MoOx/phenomic/blob/35ce1aa96fc695b08321841345ff9489ccab691b/src/builder/webpack/config.node.js#L68).

But the only two properties that seem to get used from this `config.node.js` default are `path` and `filename` in the code [here](https://github.com/MoOx/phenomic/blob/6572a607fd226352bdb6a9c6efbb48e776bf42e7/src/builder/index.js#L107).

Is this correct, or am I missing something? Thanks.

**Comment by MoOx** [comment]
You are missing this line https://github.com/MoOx/phenomic/blob/6572a607fd226352bdb6a9c6efbb48e776bf42e7/src/builder/index.js#L100 which is the one passing (and using) the webpack config for the static build. The line you are referring to is the execution of the webpack static build file.
