### ISSUE TITLE
Inline Critical CSS in html files

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#908]
I have a working script that inlines critical above the fold CSS https://github.com/serverless/site/blob/master/scripts/build/inlineCSS.js (<-- runs on a post `phenomic build` npm script)

One caveat: it adds about a minute to the build time.

Perf > build time?  ¯\_(ツ)_/¯

Related: https://github.com/MoOx/phenomic/issues/459
Reference: https://www.smashingmagazine.com/2015/08/understanding-critical-css/#what-is-critical-css

**Comment by montogeek** [comment]
This is amazing, Can we add it as an option?
I agree with user performance is more important than build time :)

**Comment by MoOx** [comment]
I think with a smarter approach we could handle that on the static rendering directly. Closing this one as it's a dup of #459
