### ISSUE TITLE
Embedding video/objects in markdown

### ISSUE THREAD

**Issue by brianrc** [MoOx/phenomic#909]
How do I embed things in the markdown files? This is the current embed code for Instagram which doesn't work when I add it to a .md file. It's ugly, but it's all they give.

`<blockquote class="instagram-media" data-instgrm-version="7" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50.0% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURczMzPf399fX1+bm5mzY9AMAAADiSURBVDjLvZXbEsMgCES5/P8/t9FuRVCRmU73JWlzosgSIIZURCjo/ad+EQJJB4Hv8BFt+IDpQoCx1wjOSBFhh2XssxEIYn3ulI/6MNReE07UIWJEv8UEOWDS88LY97kqyTliJKKtuYBbruAyVh5wOHiXmpi5we58Ek028czwyuQdLKPG1Bkb4NnM+VeAnfHqn1k4+GPT6uGQcvu2h2OVuIf/gWUFyy8OWEpdyZSa3aVCqpVoVvzZZ2VTnn2wU8qzVjDDetO90GSy9mVLqtgYSy231MxrY6I2gGqjrTY0L8fxCxfCBbhWrsYYAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div><p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;"><a href="https://www.instagram.com/p/5DGrQtxCIR/" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_blank">A video posted by Micki Mooney (@acrojunkie)</a> on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2015-07-12T19:52:33+00:00">Jul 12, 2015 at 12:52pm PDT</time></p></div></blockquote> <script async defer src="//platform.instagram.com/en_US/embeds.js"></script>`

Link: https://www.instagram.com/p/5DGrQtxCIR/

It would be nice to be able to just paste the url on it's own line and have it auto-embed [like WordPress does](https://codex.wordpress.org/Embeds). Failing that, perhaps passing the URL into a short code system like [Hugo supports](https://gohugo.io/extras/shortcodes#shortcodes-with-markdown).

Thank you!

**Comment by brianrc** [comment]
Think I found a method that works via http://embedresponsively.com/ ! 

`<style>.embed-container {position: relative; padding-bottom: 120%; height: 0; overflow: hidden;} .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='//instagram.com/p/5DGrQtxCIR/embed/' frameborder='0' scrolling='no' allowtransparency='true'></iframe></div>`

Still, it'd be great to get a shortcode or something even easier. :D

**Comment by MoOx** [comment]
I guess you can probably do that using a plugin. See https://phenomic.io/docs/usage/plugins/ for more info. You should be able to write sort of shortcode.

**Comment by MoOx** [comment]
User land problem :)
