### ISSUE TITLE
Get rid of fs-extra explicit dependency?

### ISSUE THREAD

**Issue by ivan-kleshnin** [MoOx/phenomic#912]
From https://www.npmjs.com/package/fs-promise

> fs-promise is now a thin wrapper on top of mz/fs adding support for async functions from fs-extra. If you do not need the functions from fs-extra, consider using mz directly.
> Proxies async fs and fs-extra methods exposing them as ES 2015 (ES6) compatible promises.

**Comment by thangngoc89** [comment]
Hi there, I'm aware of this. But last time I check, phenomic used fs-extra in several places.

**Comment by ivan-kleshnin** [comment]
> But last time I check, phenomic usew fs-extra in several places.

Yes. And all those places can be replaced with fs-promise. Basically now we have two versions of fs-extra: one for fs-promise and one for phenomic.

**Comment by MoOx** [comment]
If you can improve anything, PR appreciated! :)

**Comment by ivan-kleshnin** [comment]
@MoOx ok, great, I'll try to come up with proposed changes soon.

**Comment by bloodyowl** [comment]
Going to be fixed with #925

**Comment by ivan-kleshnin** [comment]
@bloodyowl great! I'm closing this to keep you concentrated on the major parts.
