### ISSUE TITLE
Proposal for shrinking page object for large site implementations

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#913]
Here is an idea to attempt to solve the large site problem. (aka growing page object issue):

1. On a tag click, check if is internal link. `<a href='url/with/slashes/replaced/with/underscore'>internal</a>`

2. If internal link, fetch corresponding json data from /data/url_with_slashes_replaced_with_underscore.json 

If no json found in `/data` folder, hard reload to URL path (aka it's referencing a file outside of phenomic scope).

![image](https://cloud.githubusercontent.com/assets/532272/21174078/ee9a5cc2-c18f-11e6-9499-86033aa8d373.png)

This should solve large site issue. However, we lose the optimistic loading based off of the inlined pages object.

So I propose a mix of both. All page data living in one place and a streamlined smaller page object inlined. The smaller inlined object only has 

```js
{ 
  the_url_path: 'PageType',
  another_path: 'DifferentPageTemplate',
  ... 
}
```

If the site were to grow to say 10,000+ pages (maybe even smaller), the inlined object again might be a problem. People could [toggle an option](https://github.com/MoOx/phenomic/issues/902) to not inline it and simply rely on the internal link setup pulling from the single `/data` folder

Related: https://github.com/MoOx/phenomic/issues/816
https://github.com/MoOx/phenomic/issues/713
https://github.com/MoOx/phenomic/issues/680

**Comment by MoOx** [comment]
The huge object might go away with the incoming collection API or will be reduced.
Meanwhile one thing we can do is to remove inlined data in a separate js file.
It's hard to scale that much and keep the optimistic loading experience that load the right layout.

**Comment by MoOx** [comment]
v1 should scale like a pro. We will add bench for perfs (compared with others ssg)
