### ISSUE TITLE
Extra closing parenthesis in aphrodite init code

### ISSUE THREAD

**Issue by xuopled** [MoOx/phenomic#922]
In `phenomic/lib/components/Html/index.js`, there is this code to initialize `aphrodite`:

`script: [{ "innerHTML": "window._aphrodite = " + JSON.stringify(aproditeResult.css.renderedClassNames) + ");" }]`

There is an extra closing parenthesis but the opening one is missing. 

So, in production, I have a SyntaxError: `Uncaught SyntaxError: Unexpected token )`

**Comment by MoOx** [comment]
Oops. Looks like a bug. 
Can you fix it? It's right here https://github.com/MoOx/phenomic/blob/e58c70872f9661b55c4fcb410a6d289910619831/src/components/Html/index.js#L71
You might have to adjust some tests.

**Comment by xuopled** [comment]
Ok I will fix it
