### ISSUE TITLE
Styleint doesn't play nice with css-module's `compose`

### ISSUE THREAD

**Issue by muhajirframe** [MoOx/phenomic#924]
trying to use css-module's `compose` feature, but styling said 'unexpected unknown property "composes" (property-no-unknown) , thought the css works perfectly.
is there anyway maybe to reorder the way the css loads so we can prevent this ?

**Comment by MoOx** [comment]
Tell me if this thread helps you https://github.com/MoOx/phenomic/pull/849

**Comment by MoOx** [comment]
No more css assumption in v1.
