### ISSUE TITLE
Zero friction inline content editing

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#929]
This is pretty awesome https://github.com/gatsbyjs/gatsby/issues/149#issuecomment-268925810

Provides an easy inline editor to automagically submit a PR without the person needing a github account

**Comment by MoOx** [comment]
So the interesting thing is

https://github.com/wiki-hub
https://jekyll-anon.surge.sh/gods/2015/02/18/vesta.html (live demo)

Pretty sure we just need to add this in the docs (for our docs and in the docs) but I guess this does not require anything in our codebase?

**Comment by DavidWells** [comment]
@MoOx yeah I think that's the case.

Going to investigate and add to serverless.com docs when I get some free time

**Comment by MoOx** [comment]
Probably a user land problem. Might revisit later.
