### ISSUE TITLE
Bug with custom routes static rendering

### ISSUE THREAD

**Issue by Strainy** [MoOx/phenomic#941]
I'm new to the Phenomic generator, but from what I've experienced so far it appears to be heading in a very promising direction - so great work so far guys :)

I'd like to include a registration process on my site separate from my set of pages Phonemic currently generates. I've built all the screens for this process, and added the necessary routes (as below).

```
<Route` component={ AppContainer }>

    {/* Registration Process */}
    <Route path="/register" component={ Register }>
      <IndexRoute component={ RegistrationForm } />
      <Route path="/register/review" component={ RegistrationReview } />
      <Route path="/register/checkout" component={ RegistrationCheckout } />
      <Route path="/register/thankyou" component={ RegistrationThankyou } />
    </Route>

    {/* Core CMS Routes */}
    <Route path="*" component={ PageContainer } />

  </Route>
```

All seems to be working nicely when running with `phenomic start`. However, during the build process Phenomic seems to be falling over:

```
> phenomic build

/bin/sh: yarn: command not found
ℹ Phenomic is starting +0.29s
✔ Copying assets +1.17s
✔ Building client files +19.13s
✔ Preparing static build +8.95s
⠋ Building static files phenomic: PageContainer: /register/register/review/ is a page not found.
phenomic: PageContainer: page /register/register/review/ should be an object

phenomic: PageContainer: /register/register/checkout/ is a page not found.
phenomic: PageContainer: page /register/register/checkout/ should be an object
phenomic: PageContainer: /register/register/thankyou/ is a page not found.
phenomic: PageContainer: page /register/register/thankyou/ should be an object
phenomic: BodyContainer: multiple childs
✔ Building static files +0.52s
✖ Build failed
TypeError:

Cannot read property 'listen' of null

    [ truncated stack ]


npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/5.11.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! espress-website@ build: `phenomic build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the espress-website@ build script 'phenomic build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the espress-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     phenomic build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs espress-website
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls espress-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jamesstrain/Documents/Personal/Electric Bike/espress-website/npm-debug.log
npm ERR! Test failed.  See above for more details.
```

When I remove the nested route for the registration process the build completes successfully.

Any guidance you can offer for correctly setting up this nested route would be greatly appreciated :)

Thanks again!

Strainy

**Comment by MoOx** [comment]
The correct way to write nested routes using react-router v3 API is like this

```
<Route path="/register" component={ Register }>
      <IndexRoute component={ RegistrationForm } />
      <Route path="review" component={ RegistrationReview } />
      <Route path="checkout" component={ RegistrationCheckout } />
      <Route path="thankyou" component={ RegistrationThankyou } />
    </Route>
```

Please try that and tell us how it works.

**Comment by Strainy** [comment]
Hey @MoOx, thanks for the quick response!

So I've made the suggested change, and again everything works fine with `phonemic start`, but still falls over at `build`. Here's the log output with the change:

```
/bin/sh: yarn: command not found
ℹ Phenomic is starting +0.28s

✔ Copying assets +1.4s
✔ Building client files +13.73s
✔ Preparing static build +5s
⠋ Building static files phenomic: PageContainer: /registerreview/ is a page not found.
phenomic: PageContainer: page /registerreview/ should be an object
phenomic: PageContainer: /registercheckout/ is a page not found.
phenomic: PageContainer: page /registercheckout/ should be an object
phenomic: PageContainer: /registerthankyou/ is a page not found.
phenomic: PageContainer: page /registerthankyou/ should be an object
phenomic: BodyContainer: multiple childs
✔ Building static files +0.27s
✖ Build failed
TypeError:

Cannot read property 'listen' of null

    [ truncated stack ]


npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! espress-website@ build: `phenomic build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the espress-website@ build script 'phenomic build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the espress-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     phenomic build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs espress-website
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls espress-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jamesstrain/projects/espress-website/npm-debug.log
npm ERR! Test failed.  See above for more details.
```

Also, here's my entire `routes.js` file if that helps:

```
import React from "react"
import { Route, IndexRoute } from "react-router"
import { PageContainer as PhenomicPageContainer } from "phenomic"

import AppContainer from "./AppContainer"
import AppBarLayout from "./layouts/AppBarLayout"
import Page from "./layouts/Page"
import Post from "./layouts/Post"
import PageError from "./layouts/PageError"
import Homepage from "./pages/Homepage"

// Custom Pages Seperate from Content Management are given custom routes (see export below)
import Register from "./pages/Register"
import RegistrationForm from "./fragments/RegistrationForm"
import RegistrationReview from "./fragments/RegistrationReview"
import RegistrationCheckout from "./fragments/RegistrationCheckout"
import RegistrationThankyou from "./fragments/RegistrationThankyou"

// Re-usable layouts that can be utilised to create content can be specified here
const PageContainer = (props) => (
  <PhenomicPageContainer
    { ...props }
    layouts={{
      Page,
      PageError,
      Homepage,
      AppBarLayout,
      Post,
    }}
  />
)

export default (
  <Route component={ AppContainer }>

    {/* Registration Process */}
    <Route path="/register" component={ Register }>
      <IndexRoute component={ RegistrationForm } />
      <Route path="review" component={ RegistrationReview } />
      <Route path="checkout" component={ RegistrationCheckout } />
      <Route path="thankyou" component={ RegistrationThankyou } />
    </Route>

    {/* Core CMS Routes */}
    <Route path="*" component={ PageContainer } />

  </Route>
)
```

Thanks again! :)

**Comment by MoOx** [comment]
So here I think there is 2 bugs.

One is that routes are not correctly "glued" so try this instead

```
<Route path="/register" component={ Register }>
      <IndexRoute component={ RegistrationForm } />
      <Route path="/review" component={ RegistrationReview } />
      <Route path="/checkout" component={ RegistrationCheckout } />
      <Route path="/thankyou" component={ RegistrationThankyou } />
    </Route>
```

For the other (the "listen" thing) it's probably (when a bug come at this point in the process) that you are using a client side library only so you might try find the one and only load it on the client (`let stuff; if typeof window !== "undefined) { stuff = require("stuff") }; /* and later */ if (stuff) ...`

**Comment by DavidWells** [comment]
Sounds like you have code calling a browser API and document/window isn't available inside the server side rendering context.

Search your code base and deps for .listen and make sure this call is wrapped in (type of window !== undefined)

**Comment by thangngoc89** [comment]
@MoOx the truncated stack, it should be displayed

**Comment by Strainy** [comment]
Hey guys,

So you're right, there are two issues here. One with the nested route and the other has something to do with this `.listen` function.

I've run a search over my codebase and found that I use the `.listen` function of the `browserHistory` API (the one included under `phenomic/lib/client`) to respond to routing changes in the `Register` container component and apply some UI changes to the container. Commenting out where I use this function seems to result in a "successful" build. I'm refactoring my application to take a lot of the UI state into Redux, so I can probably do this differently if using the `listen` function is a deal breaker for the build process. Is there a quick fix for this?

Additionally, I've applied the changes to `routes.js` as suggested by @MoOx, but I'm still receiving those warnings during the build process. See the latest log output below:

```
/bin/sh: yarn: command not found
ℹ Phenomic is starting +0.17s
✔ Copying assets +0.56s
✔ Building client files +11.77s
✔ Preparing static build +5.19s
⠋ Building static files phenomic: PageContainer: /register/review/ is a page not found.
phenomic: PageContainer: page /register/review/ should be an object
phenomic: PageContainer: /register/checkout/ is a page not found.
phenomic: PageContainer: page /register/checkout/ should be an object
phenomic: PageContainer: /register/thankyou/ is a page not found.
phenomic: PageContainer: page /register/thankyou/ should be an object
phenomic: BodyContainer: multiple childs
✔ Building static files +0.3s
ℹ 7 files written
✔ .nojekyll created
ℹ Build successful +17.99s
```

**Comment by MoOx** [comment]
@Strainy for the listen thing, you should just wrap the call like we explained, so the code is only executed on the client (it don't make sense when rendered as static html files).

For the route bug, it's probably a bug. Can you share your project for quick debugging or not (my time is limited atm)?

**Comment by Strainy** [comment]
Hi @MoOx,

So the listen thing is all sorted now - thanks :)

You can check my repo here: 
https://bitbucket.org/Strainy/espress-website

For now though, I can see that with react-router if I specify my nested routes like this it works in the development environment:

```
    <Route path="/register" component={ Register }>
      <IndexRoute component={ RegistrationForm } />
      <Route path="review" component={ RegistrationReview } />
      <Route path="checkout" component={ RegistrationCheckout } />
      <Route path="thankyou" component={ RegistrationThankyou } />
    </Route>
```
But when building and testing the resulting static site those nested routes are inaccessible (throws a 404). I believe this is because the directory of the built site looks like so:

```
+ register
+ registerreview
+ registercheckout
+ registerthankyou
```
I suspected this is because you're figuring out the directory structure from the routes and splitting based on the forward slash. So I added a forward slash to each of the nested routes, which fixes the structure of the directory for the built site, but now I get that 404 error on the development and the static site.

Thanks for helping out despite being short on time, I really appreciate it .

**Comment by MoOx** [comment]
Can you try like this?

```
    <Route path="register" component={ Register }>
      <IndexRoute component={ RegistrationForm } />
      <Route path="review" component={ RegistrationReview } />
      <Route path="checkout" component={ RegistrationCheckout } />
      <Route path="thankyou" component={ RegistrationThankyou } />
    </Route>
```

**Comment by Strainy** [comment]
@MoOx, you're a legend. This works :)

Thanks all!

**Comment by MoOx** [comment]
If it's working on the client, it should work during the static build, so I am reopening to fix this.

**Comment by daaain** [comment]
I ran into this (or similar) issue too just now, works perfectly in development, errors out on build.

Slashless routes didn't help either 😿

Here's the app, the debug output is a bit too big to paste here so have a look: https://github.com/daaain/daily-journal

**Comment by thangngoc89** [comment]
@daaain could you past it in gitst.github.com ? Too lazy to pull the repo

**Comment by daaain** [comment]
@thangngoc89 sure, here you go: https://gist.github.com/daaain/ead3cb7bacb6a3c4c874e726597762a1

**Comment by MoOx** [comment]
@daaain Not sure we support your usage of routes here https://github.com/daaain/daily-journal/blob/38f667cae7e2b6a344d2642f889b4f85bd2ca2a1/src/routes.js#L27-L29
Maybe an issue with index and/or :date.

**Comment by daaain** [comment]
I tried to follow the docs and this thread, so happy to refactor to a
supported way! How would you approach it? What I'm doing here is to
dynamically render journal pages based on what's in PouchDB, but I set up
the Node adapter so Phenomic should gracefully cancel rendering these date
based pages after getting an empty database. I might have messed something
up of course...

**Comment by MoOx** [comment]
@daaain please try with latest version 0.20.4 and tell me if that's better.
