### ISSUE TITLE
hot module reload without inotify

### ISSUE THREAD

**Issue by jampy** [MoOx/phenomic#943]
AFAIK Phenomic should support hot module reloading out of the box when running `npm start`, meaning that changing the content/ a rebuild and page update should be triggered.

This does not work on my machine (no reaction), but I guess that the problem is that my source folder is a shared directory (Linux-Windows bridge) and that Phenomic (or one of it's dependencies) is using something like the Linux Inotify subsystem to get file modification events. Such events don't work with some file system types, especially shares.

The solution is to activate **polling**. For the Webpack dev server (not related to Phenomic) I successfully use a configuration like...

```
    watchOptions: {
      aggregateTimeout: 300, // Delay the rebuilt after the first change. Value is a time in ms.
      poll: 1000  // poll since we are on Windows
    }
```

Is there a way to enable file system polling via opt-in?

**Comment by jampy** [comment]
Maybe related to #779.

**Comment by jampy** [comment]
Never mind, I found the solution:

Just set the environment variable `CHOKIDAR_USEPOLLING=1` and Chokidar will switch to polling mode.

Hope this helps others...

**Comment by MoOx** [comment]
We can probably add doc for this somewhere.
