### ISSUE TITLE
link not active on child route

### ISSUE THREAD

**Issue by westlicht** [MoOx/phenomic#945]
I have a website using child pages. In the main navigation, I would like links to be active even when a child page is displayed, for example, have a "News" link that should stay active even if individual pages containing the news entries are displayed. The one exception would be the "Home" link, which is the global index page. But I could move this page into it's own folder if necessary. I found that creating custom routes seems to fix the problem, as react-router's Link uses that behaviour by default. Before I dig into this more, I wanted to know if there is a simpler solution to this.

**Comment by MoOx** [comment]
Did you check react-router Link specific option?

https://github.com/ReactTraining/react-router/blob/master/docs/guides/IndexRoutes.md#index-links

**Comment by MoOx** [comment]
Feel free to provide more info.

**Comment by westlicht** [comment]
Hi, sorry for the delay. Using IndexLink will solve the second half of the problem. My current problem however is not solved. I'm NOT using custom routes for now, but rely on the filesystem based routes. Now, the problem is that routes represented by the top level folders (e.g. news, services, ...) are not active when pages within these folders are displayed. Suppose we have the following structure:

```
/news/index.md
/news/article1.md
/news/article2.md
```
and have a navigation link like

```
<Link to="news">News</Link>
```

When showing the URL `/news` the link is rendered as active, however, when `/news/article1` or `/news/article2` is rendered the link is inactive. If the same structure is setup using explicit routes in react router, things seem to work fine. So I was wondering if this behaviour is expected or if this can be solved using implicit routes defined by the filesystem structure.

**Comment by MoOx** [comment]
Sorry I can't help here. It's more a react-router issue than a Phenomic one.
