### ISSUE TITLE
Don't use any global selector in the default boilerplate

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#95]
Following this https://github.com/postcss/postcss.org/issues/115

**Comment by mxstbr** [comment]
:+1:

**Comment by marcustisater** [comment]
Awesome :+1:

**Comment by MoOx** [comment]
@ben-eb noted that global CSS will still be required (eg: font-face) so I thin we might much more visible (but very small by default) global CSS for things like reset/normalize & font-face things.

**Comment by MoOx** [comment]
New boilerplate will support global CSS via `*.global.css` files.
That said, I removed almost every kind of global rules that can create conflict, except a default color for ``a`` tag with a comment so people are aware of the issue this can create.
We still need global CSS for html and body tags, as well as some rules for highlighted code (at least for now).
