### ISSUE TITLE
Service Worker forcing hard reloads?

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#950]
I started noticing our site doing a hard refresh after fresh deploys from netlify.

It looks like the service worker is reloading the page after the site is already loaded. 

Has anyone else noticed this?

See:

![hard-reload](https://cloud.githubusercontent.com/assets/532272/22312825/7e281862-e30e-11e6-8c6e-b4a90ba3949b.gif)

If you visit serverless.com (in chrome, haven't tested with other browsers yet) you will see the page load then reload if you don't already have the service-worker installed.

**Comment by MoOx** [comment]
I think this happen on update only, to get up to date content.

https://github.com/MoOx/phenomic/blob/e6eaf3fbe75a688c81ce7ec475b54c5b5ed66f16/src/_utils/offline/runtime.js#L24

**Comment by brianrc** [comment]
I think I was noticing this too on my site when I enabled offline access. I turned that feature off and was meaning to ask about why I was getting so many loading spinners just browsing around when I wasn't with offline access off.

**Comment by MoOx** [comment]
Currently I am not happy with the result of offline-plugin integration. Maybe it's because of the configuration used.
How would you handle the case when someone goes on your website with out of date content?
I guess since we have network first approach now we should disable this?

**Comment by DavidWells** [comment]
I wonder if it's possible to do an ajax request to reload over the current page, rather than a full page reload here: https://github.com/MoOx/phenomic/blob/e6eaf3fbe75a688c81ce7ec475b54c5b5ed66f16/src/_utils/offline/runtime.js#L24

**Comment by MoOx** [comment]
Problem is that this will trigger a full page load anyway, especially if the bundle have changed. This will be a bit tricky to handle. Another solution is to show a banner. But using network first we should not really face this, not sure why we are getting some... Otherwise it's for background stuff (not currently loaded) so this line could be deleted. Sorry I don't have time to investigate in this as it's not specific to pehnomic (but more offline-plugin... well more directly SW).

**Comment by DavidWells** [comment]
It's on my list of things to looking into. =)

Maybe something with `updatestrategy` https://github.com/NekR/offline-plugin#updatestrategy-changed--all

**Comment by DavidWells** [comment]
Okay I might have come up with a solution:

Instead of doing [window.location.reload](https://github.com/MoOx/phenomic/blob/e6eaf3fbe75a688c81ce7ec475b54c5b5ed66f16/src/_utils/offline/runtime.js#L24) on `onUpdated` what if we disabled client side router temporarily when `onUpdated` fires and when the visitor clicks on another page link, the hard-reload will happen once while navigating to the new page.

This will solve odd page reload issue from a UX perspective.

One caveat, the user might have stale content on the first page viewed.

**Comment by MoOx** [comment]
I think we could mix that with a banner?

**Comment by DavidWells** [comment]
@MoOx yeah I think that works too.

I really wish we could swap it out without user intervention but if we can't a prompt would be ok

**Comment by MoOx** [comment]
For now no more offline feature in v1. We will review this later.
