### ISSUE TITLE
Generate content from HTML/JSX

### ISSUE THREAD

**Issue by wdavidw** [MoOx/phenomic#953]
Is there any way to write content in html, js or jsx and get it rendered just as markdown is ? Shall I write my own loader ? Thanks for your time.

**Comment by MoOx** [comment]
You can create your own routes. See https://phenomic.io/docs/usage/routing/ and tell me if that helps.

**Comment by wdavidw** [comment]
Not sure, my understanding of routing is that the page will be independant. I want my jsx to be treated just like any markdown page, with layout and metadata

**Comment by MoOx** [comment]
Oh. We don't have this out of the box yet. Do you want to write .js file treated as markdown? How would you define metadata and stuff?
You can probably handle that using a plugin that will convert your jsx files to a format that can be consumed by the loader (see https://phenomic.io/docs/usage/plugins/)

**Comment by wdavidw** [comment]
For js and jsx, we could return/export an objet, just like the one documented in the loader documentation `{head: metadata, body: "..."}`. The use case is that markdown is great for 98% of the usecases but when u need more flexibility (eg the homepage) then it isnt as good. Of cource, I could write an empty markdown inside content, with a custom/dedicated layout. This approache works great but isnt very pretty.

**Comment by MoOx** [comment]
Or you can using a custom route like it's in the default base theme for the homepage. You can add as many url as you want pointing to as many React component you want.

**Comment by wdavidw** [comment]
I think you're right for the homepage which usually have a different template. I more thinking about a regular page which share the same layout as others but with some custom content where markdown isnt the best fit.

**Comment by MoOx** [comment]
Interesting. We will support that for 1.0.

**Comment by wdavidw** [comment]
Keep up the good work, thanks for your time and involvement. Feel free to close or keep it open to keep track of it as a feature enhancement.

**Comment by MoOx** [comment]
Not going to be easy in v1, but can be solved by our own code (user land)
