### ISSUE TITLE
Build difference between local and Netlify

### ISSUE THREAD

**Issue by fesp21** [MoOx/phenomic#955]
ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' ../components/Icon in /opt/build/repo/src/fragments
at /opt/build/repo/node_modules/webpack/lib/Compilation.js:229:38
[...]
ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' ../../components/Icon in /opt/build/repo/src/components/SocialIcons
[...]
throw new Error("webpack build failed with errors");
^

Error: webpack build

**Comment by thangngoc89** [comment]
Hello, the error is simple, webpack can't resolve this component `../../components/Icon`. in this file: `/opt/build/repo/src/fragments` . Does it work in DEV mode? Did you try to build the project locally?

**Comment by MoOx** [comment]
Please provide more information if you want some help:

- What command did you get to have this errors
- Do you get your error during development or during the static build?
- What is your OS/ version of node/ version of npm (or yarn)?
- Can you share your code? A gist or a repo will be easier for a quick help.

---

With a first look it seems that some code is just missing a reference: maybe a page you didn't visit during development? Try checking the code require as it has been just said in the source file mentioned.

**Comment by fesp21** [comment]
The project runs fine locally. I have tried to deploy using netlify with npm run build command and this is what happened.

I am using Mac OS 10.12.2 

I am not using yarn and it is failing to install on netlify's instance.

Here is the link to my code. https://github.com/fesp21/Pillcycles.git

**Comment by fesp21** [comment]
The build works with no problems at all locally.  Its perfect its just when
I try to deploy it.

Thanks

Khoa

Frank

**Comment by MoOx** [comment]
Best guess: your macOS is non case sensitive and netlify is. Double check the case of the imported files and the imported reference.

**Comment by fesp21** [comment]
where are you hosting the phenomic site maybe i will try there to see if this works better. I tried to host it on AWS but the requirement is for an index.html site and I can't build the script.

Frank

**Comment by MoOx** [comment]
Did you take a look to what I said?
Also you can deploy that pretty easily: just `npm run build` on your machine on deploy `dist` folder. Works anywhere.

Here are 2 guides for auto deploy https://phenomic.io/docs/usage/#automatic-deployment but again, you can do it by hand first. Double check the case, I am pretty sure it should be the reason.
Maybe you have a `components/icon` in your file system instead of `components/Icon`. In this case you will need to do

```console
git mv -f src/components/icon src/components/Icon
```

**Comment by fesp21** [comment]
Maxime

Thanks for the info that was definitely the problem. I am not sure how that
happened but it did as there was no need for me to change that name
originally.



Frank

**Comment by MoOx** [comment]
It's because macOS is by default non sensitive to the case (so you cannot have the issue, unless you use a case sensitive partition), unlike most linux distrib.
