### ISSUE TITLE
Modern static* => JAMstack?

### ISSUE THREAD

**Issue by bdougie** [MoOx/phenomic#956]
hello @MoOx, has a quick question, sorry in advance if this is not that proper platform to discuss:

I see in the GitHub repo and on phenomic.io you point to static* and then describe. Any chance you would consider adding the term JAMstack instead or in addition of that.

JAMstack is a term to help describe what you are already describing. I realize as well that static doesn't quite cut it when describing what Phenomic and similar generators can do and I have noticed that as well, which is why I do a podcast on the very subject, [JAMstack Radio](http://www.heavybit.com/library/podcasts/jamstack-radio/), which I would love to have you on to chat about anytime in the future.

**Comment by MoOx** [comment]
I could add a mention but this term is still new imo so using it in place of static will create probably more confusion.

**Comment by bdougie** [comment]
You make a great point. I am hoping to make the term one that is more commonly used. Perhaps just adding a mention the in the description for static*: 😄 

---
All pages are available as HTML (works with no JavaScript) but users can get an enhanced navigation (when JavaScript is on). Phenomic provides a dynamic UX similar to apps, **aka JAMstack**. Try to navigate this website to see it by yourself.

I know it's still a stretch, but just trying to improve awareness for the term. As I mentioned, you are more than to come on the podcast to discuss the term `static*`. It is the exact conversation we are trying to have each week.

**Comment by MoOx** [comment]
I will definitely integrate this new word in upcoming website update (after v1).

Meanwhile, feel free to add "aka JAMstack" with a link on the home.

**Comment by MoOx** [comment]
Closed by #1000
