### ISSUE TITLE
Adding a static local file to <head>

### ISSUE THREAD

**Issue by Strainy** [MoOx/phenomic#957]
This may be a react-helmet specific query, but I'll try here first.

I need to add some local JavaScript files to the document head of my application. However, when I add to the script entries under `DefaultHeadMeta` and check the network tab when testing my application it just pulls in the relative page routes (which obviously just results in a 404 page being rendered).

```javascript
    <Helmet
      meta={ [
        {
          name: "generator", content: `${
          process.env.PHENOMIC_NAME } ${ process.env.PHENOMIC_VERSION }`,
        },
        { property: "og:site_name", content: config.companyName + " - " + config.tagLine },
        { name: "twitter:site", content: `@${ pkg.twitter }` },
        ...props.meta ? props.meta : [],
      ] }
      script={ [
        { src: "https://cdn.polyfill.io/v2/polyfill.min.js" },
        { src: "/path/to/my/script.js" },
        ...props.scripts ? props.scripts : [],
      ] }
    />
```

Are there any other ways I can get a static JS file loaded into the document head?

Appreciate any guidance you can offer!

Strainy

**Comment by MoOx** [comment]
You should consume this JS with file-loader so it's copied by webpack in the build output.
