### ISSUE TITLE
stylelint: 'declaration-block-no-ignored-properties' 

### ISSUE THREAD

**Issue by NekR** [MoOx/phenomic#960]
> stylelint: 'declaration-block-no-ignored-properties'  has been deprecated and in 8.0 will be removed.

I get this warning for fresh Phenomic setups. Should `declaration-block-no-ignored-properties` be removed?

**UPDATE:**
The latest version of `stylelint` is `7.8.0` which has this warning. If I install `7.2` manually there no warning.

**Comment by MoOx** [comment]
I guess indeed. Will update the config to avoid the noize but for us it will be a breaking change as the config won't work for older versions....

Getting this warning for each file is a bit brutal :D poke @davidtheclark @jeddy3

**Comment by NekR** [comment]
Maybe just use `"7.2.0"` instead of `"^7.2.0"` or this will be breaking change too?

**Comment by jeddy3** [comment]
> Getting this warning for each file is a bit brutal

I'm pretty sure our formatters dedupe the deprecation warnings per run. I think you'll [need to use](https://stylelint.io/user-guide/faq/#how-do-i-lint-using-my-task-runner-of-choice) stylelint as a standalone tool, rather than an PostCSS plugin though. Perhaps https://github.com/JaKXz/stylelint-webpack-plugin would help here?

**Comment by dpfranklin** [comment]
Not a solution - but - silenced warning for now by ignoring deprecated rule in new Phenomic project package.json.  Per [Stylelint configuration object](https://stylelint.io/user-guide/configuration/#the-configuration-object) and [Stylelint rule deprecation discussion](https://github.com/stylelint/stylelint/issues/2047#issuecomment-261382105).

  
```
"stylelint": {
    "extends": "./node_modules/phenomic/lib/stylelint-config-recommended/index.js",
    "rules": { 
      "declaration-block-no-ignored-properties": null
    }
```

**Comment by thierrybgentile** [comment]
trying Phenomic for the first time and yes 40+ warnings in the terminal plus a red error in the browser on first is pretty bad... Is this silenced for most people or is this how everybody first experiences Phenomic for now?

**Comment by MoOx** [comment]
> is this how everybody first experiences Phenomic for now?

It's like that indeed since 2 weeks at least.
