### ISSUE TITLE
IE 11 Script error

### ISSUE THREAD

**Issue by dawidvdh** [MoOx/phenomic#963]
After compile and testing on IE 11 i receive a ` Object doesn't support property or method 'find'` error, Tried to include babel-pollyfill but i receive `only one instance of babel-polyfill is allowed` error on build if i do.

Same thing happens on the https://phenomic.io/themes/base/demo/ site.

**Update:**

After further investigation it seems to be [component.js](https://github.com/MoOx/phenomic/blob/master/src/components/PageContainer/component.js) calling the .find method and for some reason not being polyfilled, however a conditional require of the polyfill in component.js like so:

```javascript
if (!global._babelPolyfill) {
  require("babel-polyfill")
}
```

seems to resolve the issue and also avoid the `only one instance of babel-polyfill is allowed` error. Not sure if this is the best solution though...

**Comment by dbrookes** [comment]
.find isn't provided by the polyfill.io service by default - https://polyfill.io/v2/docs/features/

I was able to resolve this by making IE11 fetch the full ES6 polyfill feature set:

https://cdn.polyfill.io/v2/polyfill.min.js?features=es6&flags=gated

**Comment by MoOx** [comment]
Maybe we should update our polyfill.io default include?
