### ISSUE TITLE
custom webpack.config.js path?

### ISSUE THREAD

**Issue by devdoomari** [MoOx/phenomic#964]
Is it possible to set webpack.config.js path?

**Comment by thangngoc89** [comment]
Yes. I dont remember the flag. But try phenomic --help command and see the flag

**Comment by MoOx** [comment]
It's not correctly visible using `phenomic --help`.
You need to do `phenomic start --help`
But it's `--webpack-config` so webpack-config and webpackConfig may work from the package.json too.
