### ISSUE TITLE
How I can add or generate robots.txt using phenomic?

### ISSUE THREAD

**Issue by alexzaporozhets** [MoOx/phenomic#968]
**robots.txt** is missing from the dist folder. Should I add it manually?

**Comment by MoOx** [comment]
For now you should use file-loader, hopefully we will offers a better solution with v1 (to avoid using webpack for this kind of needs).

**Comment by sergeylukin** [comment]
Or use [copy-webpack-plugin](https://www.npmjs.com/package/copy-webpack-plugin)

**Comment by MoOx** [comment]
With v1.x a simple public/robots.txt does the trick
