### ISSUE TITLE
is there a blog starter for this lib, similar to Ghost js?

### ISSUE THREAD

**Issue by jasan-s** [MoOx/phenomic#969]

**Comment by MoOx** [comment]
Default setup will create you a base project with the default theme, so yes. Just follow the [setup](https://phenomic.io/docs/setup/) and you will end up with [this](https://phenomic.io/themes/base/demo/)

**Comment by jasan-s** [comment]
@MoOx  in regards to writing posts , will that have to be done in an development offline environment? I'm wondering if this is right for me. I have an existing React app and I wanted to add a blog to a subdomain.  I was going to have remote blog writers add the content(no web dev experience).

**Comment by MoOx** [comment]
You can have a look to netlify with autodeploy per PR: people just add a markdown file and you get an online url to preview when build is done. No livepreview without dev env tho.

**Comment by thangngoc89** [comment]
I own a blog too and I suggest that you should not use a static site generator for writer with no dev experience. You'll end up with many many issues like: teaching them how to use markdown, where to upload images, ... 

IMHO, you should actually use Ghost.js if you want to have an ghost-like experience. If you still like a static site generator then hook Phenomic with [Ghost's API](https://api.ghost.org/v0.1/docs)

**Comment by MoOx** [comment]
"Static CMS" are also an option...

**Comment by thangngoc89** [comment]
@MoOx I hate "Static CMS". Most of them relies on Github backend and they create a commit mess :p

**Comment by jasan-s** [comment]
@thangngoc89 , @MoOx  Thanks, I was hoping to keep the entire App under the Firebase/Google Umbrella but It seems that deploying Ghost on Digital Ocean or AWS might be the right move for me. Surprised however, that there is not a Ghost like lib for react.  I may look into making one :)

**Comment by MoOx** [comment]
Maybe take a look to next.js

**Comment by thangngoc89** [comment]
Currently, I'm hosting 10 static blogs with Ghost as a backend on a $5 Digital Ocean droplet. So if you like the benefit of a static site generator and the UX of Ghost dashboard, I think you should give it a try.

**Comment by jasan-s** [comment]
@thangngoc89 are you using custom ghost image? I just checked Digitalocean and it requires minimum $10 droplet for the 1click install?

**Comment by thangngoc89** [comment]
@jasan-s I install everything with SSH, I don't use the 1click install. As I said above, I only use Ghost as a private backend and pull data from it on each build, it rarely receives any traffic.
