### ISSUE TITLE
Credentials are not sent with fetch

### ISSUE THREAD

**Issue by sitecorian** [MoOx/phenomic#972]
Hello,

I discovered that requests for page .json were failing with '401 Unauthorized' for the site under Windows authentication in IIS. That's after successful auth took place. After digging inside `redux/modules/pages.js` I noticed that the `jsonFetch` is not sending the creds. After adding it as a second arg, the issue is fixed and auth session is maintained properly.

```
{
  credentials: 'include'
}
```

More on this in [fetch](https://github.com/github/fetch/blob/49e80307b832ee4e49631ac3ea58cd8ed3cfef67/README.md) docs.

Looks like an easy fix. I will try to do a PR, posting this in case if anyone has a similar issue.

BTW, absolutely in love with the project!

**Comment by MoOx** [comment]
Will this affect non IIS server?

**Comment by sitecorian** [comment]
I believe it should be the case with any authentication model, not just IIS. I've seen same behavior on node with an ntlm module.

**Comment by MoOx** [comment]
So it's more a local problem, not a Phenomic one.
