### ISSUE TITLE
HMR error when editing markdown files requires a full reload after the first change

### ISSUE THREAD

**Issue by evenkiel** [MoOx/phenomic#973]
HMR live reloads stop working after the first change to an *.md file. To reproduce in the base default project/theme, edit the index.md file. Note that after the first change (which does live reload), you'll see the following error output in the chrome console:

<img width="664" alt="screenshot_29" src="https://cloud.githubusercontent.com/assets/1083590/23334459/87af132c-fb64-11e6-9542-437a5fb85892.png">

Subsequent changes to the same file will not cause the browser to live update.

I've identified the root cause and have a fix locally which resolves. Unfortunately I'm having trouble building from source on windows and keep getting a post-install error. Once I'm able to push past the build issue I plan on submitting a PR.

I'll cross post on Gitter chat in case someone there knows how to resolve the build problem.

**Comment by MoOx** [comment]
Seems to be a dup of #779
