### ISSUE TITLE
Unable to build from source on windows or ubuntu

### ISSUE THREAD

**Issue by evenkiel** [MoOx/phenomic#975]
When cloning the phenomic repo and running 'npm install' I receive an error when preparing docs:

```- Preparing docs
D:\dev\github\phenomic\scripts\utils\test-folder.js:147
              throw _context.t1;
              ^

Error: EPERM: operation not permitted, symlink 'D:\dev\github\phenomic\node_modules\react' -> 'D:\dev\github\phenomic\do
cs\node_modules\react'
    at Error (native)
child_process.js:526
    throw err;
    ^

Error: Command failed: D:\dev\github\phenomic\node_modules\.bin\babel-node.cmd scripts/docs.js
    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
    at toPrepare.forEach (D:\dev\github\phenomic\npm\postinstall.js:39:9)
    at Array.forEach (native)
    at D:\dev\github\phenomic\npm\postinstall.js:37:17
    at FSReqWrap.oncomplete (fs.js:123:15)
```

This occurred on both windows 10 and ubuntu. I was able to install and build properly from a mac, but no other platforms.

**Comment by MoOx** [comment]
CI works on ubuntu so not sure what cause the issue.
For Windows, same, it's executed on CI (humm maybe not the test-folder thing). Can you try in admin cmd?

**Comment by evenkiel** [comment]
Running cmd in admin mode on windows 10 did the trick! Thanks for the quick reply and resolution on this one.

Haven't tried in ubuntu again yet, but am assuming it was some form of permissions issue on my end.

Love the project, thanks so much for putting this out there!!
