### ISSUE TITLE
unable to add bootstrap and jquery in app container...

### ISSUE THREAD

**Issue by iiitmanikanta** [MoOx/phenomic#980]
need to add bootstrap and jquery for all the page route....where to include these files

**Comment by MoOx** [comment]
You should check out react-bootstrap and not use bootstrap and jquery directly...

**Comment by iiitmanikanta** [comment]
i am using npm jquery for ajax network calls .. during dev mode it is fine but while in production build it is showing below error

**_jquery2.default.ajax is not a function**

**Comment by iiitmanikanta** [comment]
i am getting this error Bootstrap's JavaScript requires jQuery

**Comment by MoOx** [comment]
Sorry I don't know bootstrap so I can't help. Try using StackOverflow for this kind of problem not directly related to Phenomic. Thanks!

**Comment by iiitmanikanta** [comment]
okay
