### ISSUE TITLE
can we use plain class names with .scss

### ISSUE THREAD

**Issue by iiitmanikanta** [MoOx/phenomic#982]
for external .scss files i am using the below syntax

`import styles from './main.scss'`
....
`render {`
` return (`
`    <div className={styles.myClassName + "  nav nav-default">`
` )
}
`

it will assign  a class name like `src-layouts-component-index--myClassName--1K6rL`

instead of this is there any way to import `.scss` globally so that we can write classnames normally 
like below

`import ./main.scss`
....
`<div className="myClassName nav nav-default"`

**Comment by MoOx** [comment]
You have to tweak your webpack config for this. This is more a generic webpack problem. And I think default boilerplate have some comments on how to handle this. You can alternatively use `*.global.css` files to do that. Just read the webpack config full of comments please.
