### ISSUE TITLE
Why does me website shows readme.md

### ISSUE THREAD

**Issue by mrmeisen** [MoOx/phenomic#983]
i wanna to create a gitpage. I push the project to github, but when i open the url. The site only show detial of readme.md, I don't know what to do.Is there something wrong with my config? Please Help!!!!!

**Comment by MoOx** [comment]
I guess what you want it to have automatic build of your project when you push your code to github.
This should be what you want https://phenomic.io/docs/usage/gh-pages/.

Please don't use github issue as a support forum. We have a community chat https://gitter.im/MoOx/phenomic
