### ISSUE TITLE
Adding search, json output, and life cycle questions

### ISSUE THREAD

**Issue by wschenk** [MoOx/phenomic#987]
First, let me say that you are doing fantastic work on this project and I'm very excited to dig deeper into it.

I'm migrating my middleman blog to phenomic and I'm trying to figure out how to implement search. I'm trying to recreate the system I implemented here http://willschenk.com/adding-search-to-a-middleman-blog/

So I have 2 questions on how I can recreate this with phenomic.

1. The first thing I do is statically build an index of the site that gets published as JSON.  In middleman this is an .erb template that does some processing over all the blog articles, and then spits out JSON.

In phenomic, how would I do something equivalent?  I was going to base it off of the loader-feed-webpack-plugin plugin, which produces rss going enhanceCollection.

2. The second is around the component lifecycle.  In middleman, the JSON file be available during the development phase, so my javascript can just load it using fetch or jquery or whatever.  It's clear when the component will be running.  So for the UI part, the text box, loading the json, the searching while typing, etc. how to I build that is live after it's generated?  Or, if it's always alive, how do I load up the json data, if I do need to have different logic, how do I determine where my code is being run?

and finally bonus question, why doesn't console.log work?  I would love it to pring out stuff to the node console when the code is runningon the server and then on the browser console when running on the browser, but I'm new to javascript really do I don't know.

Thanks.

**Comment by MoOx** [comment]
1. We already do similar things for rss https://github.com/MoOx/phenomic/blob/91cf2d274ab7246ffc0868161a1db2f32aa31c7f/src/loader-sitemap-webpack-plugin/index.js (usage https://github.com/MoOx/phenomic/blob/91cf2d274ab7246ffc0868161a1db2f32aa31c7f/themes/phenomic-theme-base/webpack.config.js#L201)
2. it should be available at all time, you can just fetch the resource you create using normal ajax. No need for different logic.

console.log should just work, we have some in the core component (PageContainer). But depending on the JS part you are writing it, it may be visible in terminal or browser console - we don't have a bridge yet :)
