### ISSUE TITLE
Auto embed videos/tweets/etc

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#992]
Is it possible to extend the remark parser to `.use` other plugins?

I want to parody some of the https://codex.wordpress.org/Embeds like wordpress does.

Like a youtube video url: 

```
Check out this cool video:

http://www.youtube.com/watch?v=dQw4w9WgXcQ
```

Would turn into 

```
Check out this cool video:

<iframe src="http://www.youtube.com/watch?v=dQw4w9WgXcQ" width=blah height=foo />
```

This is an example of autolinking github references https://github.com/wooorm/remark-github I will probably need to roll my own for youtube/vimeo links

**Comment by DavidWells** [comment]
Tried to use the `plugins` array https://github.com/MoOx/phenomic/blame/6d8b023a7f2656d295be6a767ca54e34d8868255/docs/content/docs/usage/configuration/build.md#L88-L94 but no dice

**Comment by MoOx** [comment]
You need to replace this one https://github.com/MoOx/phenomic/blame/6d8b023a7f2656d295be6a767ca54e34d8868255/docs/content/docs/usage/configuration/build.md#L93
See https://github.com/MoOx/phenomic/issues/993
