### ISSUE TITLE
Is any way how I can disable adding `phenomic-HeadingAnchor` and the anhcor itself?

### ISSUE THREAD

**Issue by alexzaporozhets** [MoOx/phenomic#993]

**Comment by MoOx** [comment]
You can copy the default plugin https://github.com/MoOx/phenomic/blob/91cf2d274ab7246ffc0868161a1db2f32aa31c7f/src/loader-plugin-markdown-transform-body-property-to-html/index.js and use it like explained here https://phenomic.io/docs/usage/plugins/

**Comment by alexzaporozhets** [comment]
@MoOx what do you think about creating an option for this plugin?

**Comment by MoOx** [comment]
Yeah this can be a solution, but I am focused on v1 right now. Feel free to do a PR!
