### ISSUE TITLE
How to access global state or send state as props to components ?

### ISSUE THREAD

**Issue by iiitmanikanta** [MoOx/phenomic#997]
i created the store with some data....
`import { combineReducers } from 'redux'`
`import createStore from 'phenomic/lib/redux/createStore'`
`import * as phenomicReducers from 'phenomic/lib/redux/modules'`

`const additionalState = {test: 'hi'}`
`const combinedInitialStateObject = {`
`  ...(typeof window !== 'undefined') && window.__INITIAL_STATE__,`
`  ...additionalState`
`}`
`const store = createStore(`
`  combineReducers(phenomicReducers),`
`  combinedInitialStateObject`
`)`
`console.log('combinedStateObject', combinedInitialStateObject)`
`export default store` 

i am using react js as child components.!

how can i pass/access the global state to particular component.

**Comment by MoOx** [comment]
This is basic react-redux usage. Please read redux doc http://redux.js.org/docs/basics/UsageWithReact.html
